-- Adiciona em produtos_entrada_itens todos os campos que existem em EntradaEstoqueItens mas faltavam
-- Tipos e defaults iguais aos de EntradaEstoqueItens

ALTER TABLE produtos_entrada_itens ADD

-- Identificacao do item
    CodigoNota                  int            NOT NULL DEFAULT (0),
    Item                        smallint       NOT NULL DEFAULT (0),
    InformacoesAdicionaisProduto text               NULL,
    NCM                         varchar(8)     NOT NULL DEFAULT (''),
    Genero                      smallint       NOT NULL DEFAULT (0),
    CFOP                        smallint       NOT NULL DEFAULT (0),
    Referencia                  varchar(150)   NOT NULL DEFAULT (''),
    Adicionada                  bit            NOT NULL DEFAULT (0),

-- Unidade / Quantidade comercial
    UnidadeComercial            varchar(6)     NOT NULL DEFAULT (''),
    QuantidadeComercial         decimal(15,2)  NOT NULL DEFAULT (0),
    ValorUnitarioComercializacao decimal(15,2) NOT NULL DEFAULT (0),
    ValorTotalBruto             decimal(15,2)  NOT NULL DEFAULT (0),
    EANTrib                     varchar(14)    NOT NULL DEFAULT (''),
    UnidadeTributavel           varchar(6)     NOT NULL DEFAULT (''),
    ValorUnitarioTributario     decimal(15,2)  NOT NULL DEFAULT (0),

-- Totais do item
    ValorFrete                  decimal(15,2)  NOT NULL DEFAULT (0),
    ValorSeguro                 decimal(15,2)  NOT NULL DEFAULT (0),
    TipoDesconto                varchar(10)    NOT NULL DEFAULT (''),
    Desconto                    decimal(15,2)  NOT NULL DEFAULT (0),
    ValorDesconto               decimal(15,2)  NOT NULL DEFAULT (0),
    ValorTributos               decimal(15,2)  NOT NULL DEFAULT (0),
    vOutro                      decimal(15,2)  NOT NULL DEFAULT (0),
    vItem                       decimal(15,2)  NOT NULL DEFAULT (0),
    indTot                      tinyint        NOT NULL DEFAULT (1),

-- ICMS
    CST                         varchar(3)     NOT NULL DEFAULT (''),
    modBC                       varchar(31)    NOT NULL DEFAULT (''),
    pRedBC                      decimal(9,2)   NOT NULL DEFAULT (0),
    vBC                         decimal(15,2)  NOT NULL DEFAULT (0),
    pICMS                       decimal(9,2)   NOT NULL DEFAULT (0),
    vICMS                       decimal(15,2)  NOT NULL DEFAULT (0),
    modBCST                     varchar(37)    NOT NULL DEFAULT (''),
    pMVAST                      decimal(9,2)   NOT NULL DEFAULT (0),
    pRedBCST                    decimal(9,2)   NOT NULL DEFAULT (0),
    vBCST                       decimal(15,2)  NOT NULL DEFAULT (0),
    pICMSST                     decimal(9,2)   NOT NULL DEFAULT (0),
    vICMSST                     decimal(15,2)  NOT NULL DEFAULT (0),
    vICMSOp                     decimal(15,2)  NOT NULL DEFAULT (0),
    pDif                        decimal(9,2)   NOT NULL DEFAULT (0),
    vICMSDeson                  decimal(15,2)  NOT NULL DEFAULT (0),
    motDesICMS                  varchar(2)     NOT NULL DEFAULT (''),
    vBCFCPST                    decimal(15,2)  NOT NULL DEFAULT (0),
    pFCPST                      decimal(9,2)   NOT NULL DEFAULT (0),
    vFCPST                      decimal(15,2)  NOT NULL DEFAULT (0),
    vBCSTRet                    decimal(15,2)  NOT NULL DEFAULT (0),
    pST                         decimal(9,2)   NOT NULL DEFAULT (0),
    vICMSSubstituto             decimal(15,2)  NOT NULL DEFAULT (0),
    vICMSSTRet                  decimal(15,2)  NOT NULL DEFAULT (0),
    vBCFCPSTRet                 decimal(15,2)  NOT NULL DEFAULT (0),
    pFCPSTRet                   decimal(9,2)   NOT NULL DEFAULT (0),
    vFCPSTRet                   decimal(15,2)  NOT NULL DEFAULT (0),
    CEST                        varchar(7)     NOT NULL DEFAULT (''),
    indEscala                   varchar(1)     NOT NULL DEFAULT ('S'),
    nFCI                        varchar(36)    NOT NULL DEFAULT (''),
    TipoProduto                 varchar(11)    NOT NULL DEFAULT (''),

-- IPI
    IPIclEnq                    varchar(5)     NOT NULL DEFAULT (''),
    IPICNPJProd                 varchar(18)    NOT NULL DEFAULT (''),
    IPIcSelo                    varchar(15)    NOT NULL DEFAULT (''),
    IPIqSelo                    bigint         NOT NULL DEFAULT (0),
    IPIcEnq                     varchar(3)     NOT NULL DEFAULT (''),
    IPICST                      varchar(2)     NOT NULL DEFAULT (''),
    IPIvIPI                     decimal(15,2)  NOT NULL DEFAULT (0),
    IPIvBC                      decimal(15,2)  NOT NULL DEFAULT (0),
    IPIpIPI                     decimal(9,2)   NOT NULL DEFAULT (0),
    IPIvUnid                    decimal(15,2)  NOT NULL DEFAULT (0),
    IPIqUnid                    decimal(15,2)  NOT NULL DEFAULT (0),

-- II (Imposto de Importacao)
    IIvBC                       decimal(15,2)  NOT NULL DEFAULT (0),
    IIvDespAdu                  decimal(15,2)  NOT NULL DEFAULT (0),
    IIvII                       decimal(15,2)  NOT NULL DEFAULT (0),
    IIvIOF                      decimal(15,2)  NOT NULL DEFAULT (0),

-- PIS
    PISCST                      varchar(2)     NOT NULL DEFAULT (''),
    PISvBC                      decimal(15,2)  NOT NULL DEFAULT (0),
    PISpPIS                     decimal(9,2)   NOT NULL DEFAULT (0),
    PISvPIS                     decimal(15,2)  NOT NULL DEFAULT (0),
    PISqBCProd                  decimal(15,2)  NOT NULL DEFAULT (0),
    PISvAliqProd                decimal(15,2)  NOT NULL DEFAULT (0),

-- COFINS
    COFINSCST                   varchar(2)     NOT NULL DEFAULT (''),
    COFINSvBC                   decimal(15,2)  NOT NULL DEFAULT (0),
    COFINSpCOFINS               decimal(9,2)   NOT NULL DEFAULT (0),
    COFINSvCOFINS               decimal(15,2)  NOT NULL DEFAULT (0),
    COFINSqBCProd               decimal(15,2)  NOT NULL DEFAULT (0),
    COFINSvAliqProd             decimal(15,2)  NOT NULL DEFAULT (0),

-- ISS
    ISSvBC                      decimal(15,2)  NOT NULL DEFAULT (0),
    ISSvAliq                    decimal(9,2)   NOT NULL DEFAULT (0),
    ISSvISSQN                   decimal(15,2)  NOT NULL DEFAULT (0),
    ISScMunFG                   int            NOT NULL DEFAULT (0),
    ISScListServ                smallint       NOT NULL DEFAULT (0),

-- IBS/CBS (Reforma Tributaria NF-e 4.0)
    IBSCBSCST                   varchar(3)     NOT NULL DEFAULT (''),
    IBSCBScClassTrib            varchar(6)     NOT NULL DEFAULT (''),
    IBSCBSvBC                   decimal(15,2)  NOT NULL DEFAULT (0),
    IBSUFpAliq                  decimal(9,2)   NOT NULL DEFAULT (0),
    IBSUFpRedAliq               decimal(9,2)   NOT NULL DEFAULT (0),
    IBSUFpAliqEfet              decimal(9,2)   NOT NULL DEFAULT (0),
    IBSUFvIBS                   decimal(15,2)  NOT NULL DEFAULT (0),
    IBSMunpAliq                 decimal(9,2)   NOT NULL DEFAULT (0),
    IBSMunpRedAliq              decimal(9,2)   NOT NULL DEFAULT (0),
    IBSMunpAliqEfet             decimal(9,2)   NOT NULL DEFAULT (0),
    IBSMunvIBS                  decimal(15,2)  NOT NULL DEFAULT (0),
    IBSvIBS                     decimal(15,2)  NOT NULL DEFAULT (0),
    CBSpAliq                    decimal(9,2)   NOT NULL DEFAULT (0),
    CBSpRedAliq                 decimal(9,2)   NOT NULL DEFAULT (0),
    CBSpAliqEfet                decimal(9,2)   NOT NULL DEFAULT (0),
    CBSvCBS                     decimal(15,2)  NOT NULL DEFAULT (0),
    ISCST                       varchar(3)     NOT NULL DEFAULT (''),
    IScClassTrib                varchar(6)     NOT NULL DEFAULT (''),
    ISvBCIS                     decimal(15,2)  NOT NULL DEFAULT (0),
    ISpIS                       decimal(9,2)   NOT NULL DEFAULT (0),
    ISvIS                       decimal(15,2)  NOT NULL DEFAULT (0),
    IBSUFpDif                   decimal(9,2)   NOT NULL DEFAULT (0),
    IBSUFvDif                   decimal(15,2)  NOT NULL DEFAULT (0),
    IBSUFvDevTrib               decimal(15,2)  NOT NULL DEFAULT (0),
    IBSMunpDif                  decimal(9,2)   NOT NULL DEFAULT (0),
    IBSMunvDif                  decimal(15,2)  NOT NULL DEFAULT (0),
    IBSMunvDevTrib              decimal(15,2)  NOT NULL DEFAULT (0),
    CBSpDif                     decimal(9,2)   NOT NULL DEFAULT (0),
    CBSvDif                     decimal(15,2)  NOT NULL DEFAULT (0),
    CBSvDevTrib                 decimal(15,2)  NOT NULL DEFAULT (0),
    IBSCBSMonoqBCMono           decimal(15,2)  NOT NULL DEFAULT (0),
    IBSCBSMonoadRemIBS          decimal(15,2)  NOT NULL DEFAULT (0),
    IBSCBSMonoadRemCBS          decimal(15,2)  NOT NULL DEFAULT (0),
    IBSCBSMonovIBSMono          decimal(15,2)  NOT NULL DEFAULT (0),
    IBSCBSMonovCBSMono          decimal(15,2)  NOT NULL DEFAULT (0),
    IBSCBSMonoqBCMonoReten      decimal(15,2)  NOT NULL DEFAULT (0),
    IBSCBSMonoadRemIBSReten     decimal(15,2)  NOT NULL DEFAULT (0),
    IBSCBSMonovIBSMonoReten     decimal(15,2)  NOT NULL DEFAULT (0),
    IBSCBSMonoadRemCBSReten     decimal(15,2)  NOT NULL DEFAULT (0),
    IBSCBSMonovCBSMonoReten     decimal(15,2)  NOT NULL DEFAULT (0),
    IBSCBSMonoqBCMonoRet        decimal(15,2)  NOT NULL DEFAULT (0),
    IBSCBSMonoadRemIBSRet       decimal(15,2)  NOT NULL DEFAULT (0),
    IBSCBSMonovIBSMonoRet       decimal(15,2)  NOT NULL DEFAULT (0),
    IBSCBSMonoadRemCBSRet       decimal(15,2)  NOT NULL DEFAULT (0),
    IBSCBSMonovCBSMonoRet       decimal(15,2)  NOT NULL DEFAULT (0),
    IBSCBSMonovTotIBSMonoItem   decimal(15,2)  NOT NULL DEFAULT (0),
    IBSCBSMonovTotCBSMonoItem   decimal(15,2)  NOT NULL DEFAULT (0);
