-- Adiciona em produtos_entrada todos os campos que existem em EntradaEstoque mas faltavam
-- Tipos e defaults iguais aos de EntradaEstoque

ALTER TABLE produtos_entrada ADD
-- Identificacao
    cCodigoNota            int           NOT NULL DEFAULT (0),
    TipoDocumento          smallint      NOT NULL DEFAULT (0),
    TipoNota               smallint      NOT NULL DEFAULT (0),
    FinalidadeEmissaoNFe   varchar(21)   NOT NULL DEFAULT (''),
    IdentificadorDestino   varchar(26)   NOT NULL DEFAULT (''),
    ConsumidorFinal        bit           NOT NULL DEFAULT (0),
    IndicadorFormaPagamento varchar(21)  NOT NULL DEFAULT (''),
    FormatoImpressaoDANFE  varchar(38)   NOT NULL DEFAULT (''),
    FormatoEmissaoNFe      varchar(34)   NOT NULL DEFAULT (''),
    IndicadorPresencaComprador varchar(45) NOT NULL DEFAULT (''),
    IndicadorIEDestinatario varchar(101) NOT NULL DEFAULT (''),
    Origem                 varchar(2)    NOT NULL DEFAULT (''),
-- Emitente / endereço
    InscricaoEstadual      varchar(25)   NOT NULL DEFAULT (''),
    InscricaoMunicipal     varchar(15)   NOT NULL DEFAULT (''),
    Suframa                varchar(9)    NOT NULL DEFAULT (''),
    Logradouro             varchar(60)   NOT NULL DEFAULT (''),
    Numero                 varchar(20)   NOT NULL DEFAULT (''),
    Complemento            varchar(40)   NOT NULL DEFAULT (''),
    Bairro                 varchar(60)   NOT NULL DEFAULT (''),
    CodigoIBGE             int           NOT NULL DEFAULT (0),
    Municipio              varchar(60)   NOT NULL DEFAULT (''),
    UF                     varchar(9)    NOT NULL DEFAULT (''),
    CEP                    varchar(9)    NOT NULL DEFAULT (''),
    CodigoPais             smallint      NOT NULL DEFAULT (0),
    Pais                   varchar(60)   NOT NULL DEFAULT (''),
    Telefone               varchar(14)   NOT NULL DEFAULT (''),
-- Totais financeiros
    BaseICMS               decimal(15,2) NOT NULL DEFAULT (0),
    BaseICMSST             decimal(15,2) NOT NULL DEFAULT (0),
    ValorSeguro            decimal(15,2) NOT NULL DEFAULT (0),
    TipoDesconto           varchar(10)   NOT NULL DEFAULT (''),
    PercDesconto           decimal(9,2)  NOT NULL DEFAULT (0),
    ValorImportacao        decimal(15,2) NOT NULL DEFAULT (0),
    ValorPIS               decimal(15,2) NOT NULL DEFAULT (0),
    ValorCOFINS            decimal(15,2) NOT NULL DEFAULT (0),
    ValorOutrasDespesas    decimal(15,2) NOT NULL DEFAULT (0),
    ValorIsento            decimal(15,2) NOT NULL DEFAULT (0),
    ValorServico           decimal(15,2) NOT NULL DEFAULT (0),
    ValorBCISS             decimal(15,2) NOT NULL DEFAULT (0),
    ValorISS               decimal(15,2) NOT NULL DEFAULT (0),
    ValorPISISS            decimal(15,2) NOT NULL DEFAULT (0),
    ValorPISCOFINS         decimal(15,2) NOT NULL DEFAULT (0),
    ValorRetidoPIS         decimal(15,2) NOT NULL DEFAULT (0),
    ValorRetidoCOFINS      decimal(15,2) NOT NULL DEFAULT (0),
    ValorRetidoCSLL        decimal(15,2) NOT NULL DEFAULT (0),
    ValorBCIRRF            decimal(15,2) NOT NULL DEFAULT (0),
    ValorIRRF              decimal(15,2) NOT NULL DEFAULT (0),
    ValorRetidoBCPrev      decimal(15,2) NOT NULL DEFAULT (0),
    ValorRetidoPrev        decimal(15,2) NOT NULL DEFAULT (0),
    ValorFunRural          decimal(15,2) NOT NULL DEFAULT (0),
    ValorFCP               decimal(15,2) NOT NULL DEFAULT (0),
    ValorFCPST             decimal(15,2) NOT NULL DEFAULT (0),
    ValorFCPSTRet          decimal(15,2) NOT NULL DEFAULT (0),
    ValorIPIDevol          decimal(15,2) NOT NULL DEFAULT (0),
    vFCPUFDest             decimal(15,2) NOT NULL DEFAULT (0),
    vICMSUFDest            decimal(15,2) NOT NULL DEFAULT (0),
    vICMSUFRemet           decimal(15,2) NOT NULL DEFAULT (0),
    PagvPag                decimal(15,2) NOT NULL DEFAULT (0),
    vBCSTRetTotal          decimal(15,2) NOT NULL DEFAULT (0),
    vICMSSTRetTotal        decimal(15,2) NOT NULL DEFAULT (0),
    vICMSSubstitutoTotal   decimal(15,2) NOT NULL DEFAULT (0),
-- ICMS mono / totais gerais
    qBCMono                decimal(15,2) NOT NULL DEFAULT (0),
    vICMSMono              decimal(15,2) NOT NULL DEFAULT (0),
    qBCMonoReten           decimal(15,2) NOT NULL DEFAULT (0),
    vICMSMonoReten         decimal(15,2) NOT NULL DEFAULT (0),
    qBCMonoRet             decimal(15,2) NOT NULL DEFAULT (0),
    vICMSMonoRet           decimal(15,2) NOT NULL DEFAULT (0),
    vNFTot                 decimal(15,2) NOT NULL DEFAULT (0),
    TotTributos            decimal(15,2) NOT NULL DEFAULT (0),
-- IBS / CBS (Reforma Tributaria NF-e 4.0)
    TotIBSCBSvBC           decimal(15,2) NOT NULL DEFAULT (0),
    TotIBSUFvDif           decimal(15,2) NOT NULL DEFAULT (0),
    TotIBSUFvDevTrib       decimal(15,2) NOT NULL DEFAULT (0),
    TotIBSUFvIBS           decimal(15,2) NOT NULL DEFAULT (0),
    TotIBSMunvDif          decimal(15,2) NOT NULL DEFAULT (0),
    TotIBSMunvDevTrib      decimal(15,2) NOT NULL DEFAULT (0),
    TotIBSMunvIBS          decimal(15,2) NOT NULL DEFAULT (0),
    TotIBSvIBS             decimal(15,2) NOT NULL DEFAULT (0),
    TotIBSvCredPres        decimal(15,2) NOT NULL DEFAULT (0),
    TotIBSvCredPresCondSus decimal(15,2) NOT NULL DEFAULT (0),
    TotCBSvDif             decimal(15,2) NOT NULL DEFAULT (0),
    TotCBSvDevTrib         decimal(15,2) NOT NULL DEFAULT (0),
    TotCBSvCBS             decimal(15,2) NOT NULL DEFAULT (0),
    TotCBSvCredPres        decimal(15,2) NOT NULL DEFAULT (0),
    TotCBSvCredPresCondSus decimal(15,2) NOT NULL DEFAULT (0),
    TotISvIS               decimal(15,2) NOT NULL DEFAULT (0),
    TotIBSMonovIBSMono     decimal(15,2) NOT NULL DEFAULT (0),
    TotIBSMonovCBSMono     decimal(15,2) NOT NULL DEFAULT (0),
    TotIBSMonovIBSMonoReten decimal(15,2) NOT NULL DEFAULT (0),
    TotIBSMonovCBSMonoReten decimal(15,2) NOT NULL DEFAULT (0),
    TotIBSMonovIBSMonoRet  decimal(15,2) NOT NULL DEFAULT (0),
    TotIBSMonovCBSMonoRet  decimal(15,2) NOT NULL DEFAULT (0),
-- Transportadora (detalhes)
    TranspModFrete         tinyint       NOT NULL DEFAULT (9),
    TranspNome             varchar(60)   NOT NULL DEFAULT (''),
    TranspInscricaoEstadual varchar(14)  NOT NULL DEFAULT (''),
    TranspEndereco         varchar(60)   NOT NULL DEFAULT (''),
    TranspUF               varchar(2)    NOT NULL DEFAULT (''),
    TranspMunicipio        varchar(60)   NOT NULL DEFAULT (''),
    TranspCNPJ_CPF         varchar(18)   NOT NULL DEFAULT (''),
    TranspValorServico     decimal(15,2) NOT NULL DEFAULT (0),
    TranspBCRetencaoICMS   decimal(15,2) NOT NULL DEFAULT (0),
    TranspAliquotaRetencaoICMS decimal(9,2) NOT NULL DEFAULT (0),
    TranspValorRetencaoICMS decimal(15,2) NOT NULL DEFAULT (0),
    TranspCFOP             varchar(5)    NOT NULL DEFAULT (''),
    TranspcMunFG           int           NOT NULL DEFAULT (0),
    TranspPlaca            varchar(8)    NOT NULL DEFAULT (''),
    TranspPlacaUF          varchar(2)    NOT NULL DEFAULT (''),
    TranspRNTC             varchar(20)   NOT NULL DEFAULT (''),
    TranspReboquePlaca     varchar(8)    NOT NULL DEFAULT (''),
    TranspReboquePlacaUF   varchar(2)    NOT NULL DEFAULT (''),
    TranspReboqueRNTC      varchar(20)   NOT NULL DEFAULT (''),
-- Volumes
    VolumeQuantidade       bigint        NOT NULL DEFAULT (0),
    VolumeEspecie          varchar(60)   NOT NULL DEFAULT (''),
    VolumeMarca            varchar(60)   NOT NULL DEFAULT (''),
    VolumeNumeracao        varchar(60)   NOT NULL DEFAULT (''),
    VolumePesoLiquido      decimal(15,2) NOT NULL DEFAULT (0),
    VolumePesoBruto        decimal(15,2) NOT NULL DEFAULT (0),
    Lacres                 varchar(60)   NOT NULL DEFAULT (''),
-- Fatura / duplicata
    NumeroFatura           varchar(60)   NOT NULL DEFAULT (''),
    ValorOriginalFatura    decimal(15,2) NOT NULL DEFAULT (0),
    ValorDescontoFatura    decimal(15,2) NOT NULL DEFAULT (0),
    ValorLiquidoFatura     decimal(15,2) NOT NULL DEFAULT (0),
    NumeroDuplicata        varchar(60)   NOT NULL DEFAULT (''),
    VencimentoDuplicata    datetime          NULL,
    ValorDuplicata         decimal(15,2) NOT NULL DEFAULT (0),
-- Informacoes adicionais / embarque
    InformacoesAdicionais  varchar(255)  NOT NULL DEFAULT (''),
    InformacoesComplementares text            NULL,
    UFEmbarque             varchar(2)    NOT NULL DEFAULT (''),
    LocEmbarque            varchar(60)   NOT NULL DEFAULT (''),
    ChavedeAcessoAdicional varchar(36)   NOT NULL DEFAULT (''),
-- Protocolo / recibo
    NumeroRecibo           bigint        NOT NULL DEFAULT (0),
    DataHoraRecebimento    varchar(25)   NOT NULL DEFAULT (''),
    NumeroProtocolo        bigint        NOT NULL DEFAULT (0),
    DataHoraProcotolo      varchar(25)   NOT NULL DEFAULT (''),
-- Status / controle
    Enviada                bit           NOT NULL DEFAULT (0),
    Cancelada              bit           NOT NULL DEFAULT (0),
    Denegada               bit           NOT NULL DEFAULT (0),
    Justificativa          varchar(255)  NOT NULL DEFAULT (''),
    EmProcessamento        bit           NOT NULL DEFAULT (0),
    CodigoObservacao       int           NOT NULL DEFAULT (0),
    ContingenciaDataHora   varchar(25)   NOT NULL DEFAULT (''),
    ContingenciaJustificativa varchar(255) NOT NULL DEFAULT (''),
    Email                  varchar(100)  NOT NULL DEFAULT (''),
    CodigoVenda            int           NOT NULL DEFAULT (0),
    CanceladaProtocolo     bigint        NOT NULL DEFAULT (0),
    CodigoNatureza         smallint      NOT NULL DEFAULT (0);
