INSERT INTO Categorias (Categoria, Tipo_Empresa) VALUES 
-- 1. SUPERMERCADO
('ALIMENTOS', 1), ('ALIMENTOS (CESTA BÁSICA)', 1), ('HORTIFRÚTI', 1), ('CARNES', 1), ('FRIOS E LATICÍNIOS', 1), ('PADARIA E CONFEITARIA', 1), ('LIMPEZA', 1), ('HIGIENE E PERFUMARIA', 1), ('BEBIDAS', 1), ('BEBIDAS (ALCOÓLICAS)', 1), ('BEBIDAS (AÇUCARADAS)', 1), ('CONGELADOS', 1), ('LATICÍNIOS', 1), ('TABACARIA', 1), ('PET SHOP', 1), ('BAZAR E UTILIDADES', 1),

-- 2. FARMÁCIA
('ÉTICOS', 2), ('GENÉRICOS', 2), ('SIMILARES', 2), ('PERFUMARIA E COSMÉTICOS', 2), ('HIGIENE', 2), ('CUIDADOS INFANTIS', 2), ('DERMOCOSMÉTICOS', 2), ('SUPLEMENTOS E VITAMINAS', 2), ('PRIMEIROS SOCORROS', 2), ('CONVENIÊNCIA', 2),

-- 3. RESTAURANTE/LANCHONETE
('PRATOS EXECUTIVOS', 3), ('LANCHES E SANDUÍCHES', 3), ('PORÇÕES E PETISCOS', 3), ('PIZZAS', 3), ('SALGADOS', 3), ('SOBREMESAS', 3), ('BEBIDAS QUENTES', 3), ('ENTRADAS', 3), ('BEBIDAS', 3), ('BEBIDAS (ALCOÓLICAS)', 3), ('BEBIDAS (AÇUCARADAS)', 3), ('TABACARIA', 3),

-- 4. SAPATARIA/VESTUÁRIO
('CALÇADOS MASCULINOS', 4), ('CALÇADOS FEMININOS', 4), ('CALÇADOS INFANTIS', 4), ('MODA MASCULINA', 4), ('MODA FEMININA', 4), ('MODA ÍNTIMA', 4), ('MODA PRAIA', 4), ('ACESSÓRIOS E BOLSAS', 4), ('CINTOS E CARTEIRAS', 4), ('MEIAS', 4),

-- 5. AUTOPEÇA/MOTOPEÇA
('MOTOR E TRANSMISSÃO', 5), ('SUSPENSÃO E AMORTECEDORES', 5), ('FREIOS', 5), ('SISTEMA ELÉTRICO', 5), ('ILUMINAÇÃO', 5), ('LATARIA E ACESSÓRIOS', 5), ('PNEUS E RODAS', 5), ('ÓLEOS E LUBRIFICANTES', 5), ('ESCAPAMENTOS', 5), ('FERRAMENTAS AUTOMOTIVAS', 5),

-- 6. MATERIAL DE CONSTRUÇÃO
('ALVENARIA E ESTRUTURA', 6), ('HIDRÁULICA', 6), ('ELÉTRICA', 6), ('PISOS E REVESTIMENTOS', 6), ('TINTAS E ACESSÓRIOS', 6), ('FERRAGENS', 6), ('FERRAMENTAS', 6), ('ILUMINAÇÃO/LUMINÁRIAS', 6), ('LOUÇAS E METAIS', 6), ('MADEIRAS E TELHADOS', 6),

-- 7. DISTRIBUIDOR BEBIDA
 ('BEBIDAS', 7), ('BEBIDAS (ALCOÓLICAS)', 7), ('BEBIDAS (AÇUCARADAS)', 7), ('CONVENIÊNCIA', 7), ('ALIMENTOS', 7), ('GELO E CARVÃO', 7), ('PETISCOS/SNACKS', 7), ('TABACARIA', 7),

-- 8. DIVERSOS
('COMBUSTÍVEIS', 8), ('VASILHAMES', 8), ('SERVIÇOS', 8), ('PRODUTOS GERAIS', 8), ('BRINDES', 8), ('MANUTENÇÃO', 8), ('OUTROS', 8);
GO
