data = open('OnlineCommerce/Forms/NFe_Completa.frm', 'rb').read()

# =============================================================================
# 1. Inserir RecalcularItensNota apos AtualizarGrid_Itens
# =============================================================================
old_after_agrid = (
    b'End Sub\r\n'
    b'\r\n'
    b'Private Sub CalcularICMSInterItensGERAL()\r\n'
)

new_sub = (
    b'End Sub\r\n'
    b'\r\n'
    b'Private Sub RecalcularItensNota()\r\n'
    b'If txtCodNota.Text = "" Then Exit Sub\r\n'
    b'If GridNotasItens.rows <= 1 Then Exit Sub\r\n'
    b'\r\n'
    b'Dim rItens       As ADODB.Recordset\r\n'
    b'Dim vItem        As Integer\r\n'
    b'Dim vValProd     As Currency\r\n'
    b'Dim sCST         As String\r\n'
    b'Dim dblPICMS     As Double\r\n'
    b'Dim dblPRedBC    As Double\r\n'
    b'Dim sModBC       As String\r\n'
    b'Dim sItemIPICST  As String\r\n'
    b'Dim dblPIPI      As Double\r\n'
    b'Dim dblPPIS      As Double\r\n'
    b'Dim dblPCOFINS   As Double\r\n'
    b'Dim dblPMVA      As Double\r\n'
    b'Dim dblPICMSST   As Double\r\n'
    b'Dim dblPRedBCST  As Double\r\n'
    b'Dim vValorIPI    As Currency\r\n'
    b'Dim curBaseICMS  As Currency\r\n'
    b'Dim curVICMS     As Currency\r\n'
    b'Dim curBasePISCOFINS As Currency\r\n'
    b'Dim curVPIS      As Currency\r\n'
    b'Dim curVCOFINS   As Currency\r\n'
    b'Dim curIPIvBC    As Currency\r\n'
    b'Dim dblIPIpGravar As Double\r\n'
    b'Dim curVBCST     As Currency\r\n'
    b'Dim curVICMSST   As Currency\r\n'
    b'Dim sCurModBC    As String\r\n'
    b'Dim sIPIcEnq     As String\r\n'
    b'Dim bSimples     As Boolean\r\n'
    b'Dim bDevolucao   As Boolean\r\n'
    b'Dim sUpd         As String\r\n'
    b'\r\n'
    b'bSimples   = (vRegimeTributario = 1 Or vRegimeTributario = 2 Or vRegimeTributario = 5)\r\n'
    b'bDevolucao = (Left(cboFinalidade.Text, 1) = "4")\r\n'
    b'\r\n'
    b'sSQL = "SELECT ITEM, " & _\r\n'
    b'       "ValorUnitarioComercializacao * QuantidadeComercial AS vProd, " & _\r\n'
    b'       "CST, pICMS, pRedBC, modBC, " & _\r\n'
    b'       "IPICST, IPIpIPI, " & _\r\n'
    b'       "PISCST, PISpPIS, " & _\r\n'
    b'       "COFINSCST, cofinspcofins, " & _\r\n'
    b'       "pMVAST, pICMSST, pRedBCST " & _\r\n'
    b'       "FROM NotaFiscalItens WHERE CodigoNota = " & Val(txtCodNota.Text)\r\n'
    b'RsOpen rItens, sSQL\r\n'
    b'\r\n'
    b'Do While Not rItens.EOF\r\n'
    b'    vItem        = rItens("ITEM")\r\n'
    b'    vValProd     = CCur(rItens("vProd"))\r\n'
    b'    sCST         = Right(Format(rItens("CST"), "@"), 3)\r\n'
    b'    dblPICMS     = CDbl(IIf(IsNull(rItens("pICMS")),    0, rItens("pICMS")))\r\n'
    b'    dblPRedBC    = CDbl(IIf(IsNull(rItens("pRedBC")),   0, rItens("pRedBC")))\r\n'
    b'    sModBC       = Trim(IIf(IsNull(rItens("modBC")),    "", rItens("modBC")))\r\n'
    b'    sItemIPICST  = Trim(IIf(IsNull(rItens("IPICST")),   "", rItens("IPICST")))\r\n'
    b'    dblPIPI      = CDbl(IIf(IsNull(rItens("IPIpIPI")),  0, rItens("IPIpIPI")))\r\n'
    b'    dblPPIS      = CDbl(IIf(IsNull(rItens("PISpPIS")),  0, rItens("PISpPIS")))\r\n'
    b'    dblPCOFINS   = CDbl(IIf(IsNull(rItens("cofinspcofins")), 0, rItens("cofinspcofins")))\r\n'
    b'    dblPMVA      = CDbl(IIf(IsNull(rItens("pMVAST")),   0, rItens("pMVAST")))\r\n'
    b'    dblPICMSST   = CDbl(IIf(IsNull(rItens("pICMSST")),  0, rItens("pICMSST")))\r\n'
    b'    dblPRedBCST  = CDbl(IIf(IsNull(rItens("pRedBCST")), 0, rItens("pRedBCST")))\r\n'
    b'\r\n'
    b'    \' IPI antecipado (necessario para base do ICMS com consumidor final)\r\n'
    b'    If bSimples And Not bDevolucao Then\r\n'
    b'        vValorIPI = 0\r\n'
    b'    Else\r\n'
    b'        vValorIPI = CCur(Format(vValProd * dblPIPI / 100, "0.00"))\r\n'
    b'    End If\r\n'
    b'\r\n'
    b'    \' ICMS\r\n'
    b'    If bSimples And Not bDevolucao Then\r\n'
    b'        If sCST = "101" Or sCST = "201" Then\r\n'
    b'            curBaseICMS = vValProd\r\n'
    b'            If Left(cboConsumidorFinal.Text, 1) = "1" Then curBaseICMS = curBaseICMS + vValorIPI\r\n'
    b'            curVICMS = CCur(Format(curBaseICMS * dblPICMS / 100, "0.00"))\r\n'
    b'        Else\r\n'
    b'            curBaseICMS = 0\r\n'
    b'            curVICMS = 0\r\n'
    b'        End If\r\n'
    b'    Else\r\n'
    b'        If dblPRedBC > 0 Then\r\n'
    b'            curBaseICMS = CCur(vValProd * (1 - dblPRedBC / 100))\r\n'
    b'        Else\r\n'
    b'            curBaseICMS = vValProd\r\n'
    b'        End If\r\n'
    b'        If Left(cboConsumidorFinal.Text, 1) = "1" Then curBaseICMS = curBaseICMS + vValorIPI\r\n'
    b'        curVICMS = CCur(Format(curBaseICMS * dblPICMS / 100, "0.00"))\r\n'
    b'    End If\r\n'
    b'\r\n'
    b'    \' modBC: vazio se nao houver base\r\n'
    b'    If curBaseICMS = 0 Then\r\n'
    b'        sCurModBC = ""\r\n'
    b'    Else\r\n'
    b'        sCurModBC = IIf(sModBC = "" Or sModBC = "0", "3", sModBC)\r\n'
    b'    End If\r\n'
    b'\r\n'
    b'    \' PIS / COFINS\r\n'
    b'    If bSimples And Not bDevolucao Then\r\n'
    b'        curBasePISCOFINS = 0\r\n'
    b'        curVPIS   = 0\r\n'
    b'        curVCOFINS = 0\r\n'
    b'    Else\r\n'
    b'        curBasePISCOFINS = vValProd - curVICMS\r\n'
    b'        If curBasePISCOFINS < 0 Then curBasePISCOFINS = 0\r\n'
    b'        curVPIS    = CCur(Format(curBasePISCOFINS * dblPPIS   / 100, "0.00"))\r\n'
    b'        curVCOFINS = CCur(Format(curBasePISCOFINS * dblPCOFINS / 100, "0.00"))\r\n'
    b'    End If\r\n'
    b'\r\n'
    b'    \' IPI gravar\r\n'
    b'    If bSimples And Not bDevolucao Then\r\n'
    b'        sIPIcEnq     = "999"\r\n'
    b'        curIPIvBC    = 0\r\n'
    b'        dblIPIpGravar = 0\r\n'
    b'        vValorIPI    = 0\r\n'
    b'    Else\r\n'
    b'        If sItemIPICST = "99" Or sItemIPICST = "53" Or sItemIPICST = "52" Or sItemIPICST = "50" Then\r\n'
    b'            sIPIcEnq = "999"\r\n'
    b'        Else\r\n'
    b'            sIPIcEnq = ""\r\n'
    b'        End If\r\n'
    b'        curIPIvBC    = vValProd\r\n'
    b'        dblIPIpGravar = dblPIPI\r\n'
    b'    End If\r\n'
    b'\r\n'
    b'    \' ICMS-ST\r\n'
    b'    If chkICMSST.Value = 1 Then\r\n'
    b'        If bSimples And Not bDevolucao Then\r\n'
    b'            curVBCST   = 0\r\n'
    b'            curVICMSST = 0\r\n'
    b'        Else\r\n'
    b'            curVBCST = (vValProd + vValorIPI) * (1 + dblPMVA / 100)\r\n'
    b'            If dblPRedBCST > 0 Then curVBCST = curVBCST * (1 - dblPRedBCST / 100)\r\n'
    b'            curVICMSST = CCur(Format(curVBCST * dblPICMSST / 100, "0.00")) - curVICMS\r\n'
    b'            If curVICMSST < 0 Then curVICMSST = 0\r\n'
    b'        End If\r\n'
    b'    Else\r\n'
    b'        curVBCST   = 0\r\n'
    b'        curVICMSST = 0\r\n'
    b'    End If\r\n'
    b'\r\n'
    b'    sUpd = "UPDATE NotaFiscalItens SET " & _\r\n'
    b'           "modBC = \'" & sCurModBC & "\', " & _\r\n'
    b'           "vBC = " & FSQL(curBaseICMS, 2) & ", " & _\r\n'
    b'           "vICMS = " & FSQL(curVICMS, 2) & ", " & _\r\n'
    b'           "PISvBC = " & FSQL(curBasePISCOFINS, 2) & ", " & _\r\n'
    b'           "PISvPIS = " & FSQL(curVPIS, 2) & ", " & _\r\n'
    b'           "COFINSvBC = " & FSQL(curBasePISCOFINS, 2) & ", " & _\r\n'
    b'           "cofinsvcofins = " & FSQL(curVCOFINS, 2) & ", " & _\r\n'
    b'           "IPIcEnq = \'" & sIPIcEnq & "\', " & _\r\n'
    b'           "IPIvBC = " & FSQL(curIPIvBC, 2) & ", " & _\r\n'
    b'           "IPIpIPI = " & FSQL(dblIPIpGravar, 4) & ", " & _\r\n'
    b'           "IPIvIPI = " & FSQL(vValorIPI, 2) & ", " & _\r\n'
    b'           "vBCST = " & FSQL(curVBCST, 2) & ", " & _\r\n'
    b'           "vICMSST = " & FSQL(curVICMSST, 2) & " " & _\r\n'
    b'           "WHERE CodigoNota = " & Val(txtCodNota.Text) & " AND ITEM = " & vItem\r\n'
    b'    dbData.Execute sUpd\r\n'
    b'\r\n'
    b'    rItens.MoveNext\r\n'
    b'Loop\r\n'
    b'\r\n'
    b'Exibir_Itens\r\n'
    b'AtualizarTotaisNota\r\n'
    b'End Sub\r\n'
    b'\r\n'
    b'Private Sub CalcularICMSInterItensGERAL()\r\n'
)

c = data.count(old_after_agrid)
print(f'1. Inserir RecalcularItensNota: {c}')
if c == 1:
    data = data.replace(old_after_agrid, new_sub)

# =============================================================================
# 2. cboFinalidade_Click — chamar RecalcularItensNota
# =============================================================================
old_click = (
    b'Private Sub cboFinalidade_Click()\r\n'
    b'    AplicarVisibilidadeGridItens\r\n'
    b'End Sub\r\n'
)
new_click = (
    b'Private Sub cboFinalidade_Click()\r\n'
    b'    AplicarVisibilidadeGridItens\r\n'
    b'    RecalcularItensNota\r\n'
    b'End Sub\r\n'
)
c2 = data.count(old_click)
print(f'2. cboFinalidade_Click: {c2}')
if c2 == 1:
    data = data.replace(old_click, new_click)

# Normalizar CRLF
data = data.replace(b'\r\n', b'\n').replace(b'\r', b'\n').replace(b'\n', b'\r\n')
open('OnlineCommerce/Forms/NFe_Completa.frm', 'wb').write(data)
print('Salvo. Tamanho:', len(data))
