# -*- coding: utf-8 -*-
"""
Cria o form OrdemServico\\Forms\\frmOleoVencidos.frm: relatorio global
de trocas de oleo vencidas, baseado em OS.DATA_TERMINO x
OS_ControleOleo.LIMITE_PRAZO (meses), comparado com a data atual.

Como um veiculo pode ter varias OS com o mesmo produto, usa
ROW_NUMBER() OVER (PARTITION BY placa, produto ORDER BY DATA_TERMINO
DESC) para pegar so a ULTIMA OS de cada combinacao placa+produto, e so
lista quem ja venceu (Vencido <= GETDATE()).

Grid: COD.OS | CLIENTE | VEICULO/PLACA/KM | TROCA | VENCIDO | DIAS | OLEO
"""

PATH = r"C:\projeto\OrdemServico\Forms\frmOleoVencidos.frm"

OLEO_ACC = "\xd3LEO"

design = [
    "VERSION 5.00",
    'Object = "{5E9E78A0-531B-11CF-91F6-C2863C385E30}#1.0#0"; "msflxgrd.ocx"',
    "Begin VB.Form frmOleoVencidos ",
    "   BorderStyle     =   3  'Fixed Dialog",
    '   Caption         =   "Trocas de \xd3leo Vencidas"',
    "   ClientHeight    =   4560",
    "   ClientLeft      =   120",
    "   ClientTop       =   465",
    "   ClientWidth     =   11040",
    "   LinkTopic       =   \"Form1\"",
    "   ScaleHeight     =   4560",
    "   ScaleWidth      =   11040",
    "   StartUpPosition =   2  'CenterScreen",
    "   Begin VB.CommandButton cmdFechar ",
    '      Caption         =   "Fechar"',
    "      Height          =   420",
    "      Left            =   9540",
    "      TabIndex        =   2",
    "      Top             =   4020",
    "      Width           =   1400",
    "   End",
    "   Begin VB.CommandButton cmdAtualizar ",
    '      Caption         =   "Atualizar"',
    "      Height          =   420",
    "      Left            =   8040",
    "      TabIndex        =   1",
    "      Top             =   4020",
    "      Width           =   1400",
    "   End",
    "   Begin MSFlexGridLib.MSFlexGrid lstVencidos ",
    "      Height          =   3900",
    "      Left            =   60",
    "      TabIndex        =   0",
    "      Top             =   60",
    "      Width           =   10920",
    "      _ExtentX        =   19265",
    "      _ExtentY        =   6879",
    "      _Version        =   393216",
    "      Appearance      =   0",
    "   End",
    "End",
    'Attribute VB_Name = "frmOleoVencidos"',
    "Attribute VB_GlobalNameSpace = False",
    "Attribute VB_Creatable = False",
    "Attribute VB_PredeclaredId = True",
    "Attribute VB_Exposed = False",
]

code = [
    "Option Explicit",
    "",
    "Private Sub Form_Load()",
    "    ConfigurarGrid",
    "    CarregarGrid",
    "End Sub",
    "",
    "Private Sub ConfigurarGrid()",
    "    With lstVencidos",
    "        .Cols = 7",
    "        .Rows = 1",
    "        .FixedCols = 0",
    "        .ColWidth(0) = 700",
    "        .ColWidth(1) = 2000",
    "        .ColWidth(2) = 3300",
    "        .ColWidth(3) = 1000",
    "        .ColWidth(4) = 1000",
    "        .ColWidth(5) = 700",
    "        .ColWidth(6) = 2100",
    '        .TextMatrix(0, 0) = "COD.OS"',
    '        .TextMatrix(0, 1) = "CLIENTE"',
    '        .TextMatrix(0, 2) = "VEICULO / PLACA / KM"',
    '        .TextMatrix(0, 3) = "TROCA"',
    '        .TextMatrix(0, 4) = "VENCIDO"',
    '        .TextMatrix(0, 5) = "DIAS"',
    '        .TextMatrix(0, 6) = "%s"' % OLEO_ACC,
    "        .AllowUserResizing = 1",
    "        .SelectionMode = 1",
    "    End With",
    "End Sub",
    "",
    "Private Sub CarregarGrid()",
    "    Dim r As ADODB.Recordset",
    "    Dim sql As String",
    "    Dim n As Integer",
    "    Dim sVeiculo As String",
    "    Dim sVeiculoPlacaKm As String",
    "    Dim dVencido As Date",
    "",
    "    lstVencidos.Rows = 1",
    "",
    '    sql = "SELECT COD_OS, Cliente, FABRICANTE, MODELO, ANO, PLACA, KM, DATA_TERMINO, Oleo, Vencido " & _',
    '          "FROM (" & _',
    '          "    SELECT OS.COD_OS, cliente.nome AS Cliente, " & _',
    '          "        OS_Equipamento_Auto.fabricante AS FABRICANTE, OS_Equipamento_Auto.modelo AS MODELO, OS_Equipamento_Auto.ano AS ANO, " & _',
    '          "        OS_Equipamento_Auto.placa AS PLACA, OS_Equipamento_Auto.km AS KM, OS.DATA_TERMINO, " & _',
    '          "        produtos.descricao AS Oleo, " & _',
    '          "        DATEADD(month, OS_ControleOleo.LIMITE_PRAZO, OS.DATA_TERMINO) AS Vencido, " & _',
    '          "        ROW_NUMBER() OVER (PARTITION BY OS_Equipamento_Auto.placa, produtos.codigo ORDER BY OS.DATA_TERMINO DESC) AS rn " & _',
    '          "    FROM OS " & _',
    '          "    INNER JOIN cliente ON cliente.CODIGO = OS.COD_CLIENTE " & _',
    '          "    INNER JOIN OS_Equipamento_Auto ON OS_Equipamento_Auto.COD_OS = OS.COD_OS " & _',
    '          "    INNER JOIN pedidos_itens ON pedidos_itens.COD_PEDIDO = OS.COD_PEDIDO " & _',
    '          "    INNER JOIN produtos ON produtos.CODIGO = pedidos_itens.COD_PRODUTO " & _',
    '          "    INNER JOIN OS_ControleOleo ON OS_ControleOleo.COD_PRODUTO = produtos.CODIGO " & _',
    '          "    WHERE (OS.DATA_TERMINO IS NOT NULL) AND (OS_ControleOleo.LIMITE_PRAZO > 0) " & _',
    '          ") AS Ult " & _',
    '          "WHERE (rn = 1) AND (Vencido <= GETDATE()) " & _',
    '          "ORDER BY Vencido ASC"',
    "",
    "    RsOpen r, sql",
    "    n = 1",
    "    Do While Not r.EOF",
    '        sVeiculo = Trim(ValidateNull(r("FABRICANTE")) & " / " & ValidateNull(r("MODELO")) & " / " & ValidateNull(r("ANO")))',
    '        sVeiculoPlacaKm = sVeiculo & " / " & ValidateNull(r("PLACA")) & " / " & ValidateNull(r("KM"))',
    '        dVencido = r("Vencido")',
    "        With lstVencidos",
    "            .Rows = n + 1",
    '            .Row = n: .Col = 0: .Text = ValidateNull(r("COD_OS"))',
    '            .Row = n: .Col = 1: .Text = ValidateNull(r("Cliente"))',
    "            .Row = n: .Col = 2: .Text = sVeiculoPlacaKm",
    '            .Row = n: .Col = 3: .Text = Format(r("DATA_TERMINO"), "dd/mm/yy")',
    '            .Row = n: .Col = 4: .Text = Format(dVencido, "dd/mm/yy")',
    '            .Row = n: .Col = 5: .Text = DateDiff("d", dVencido, Date)',
    '            .Row = n: .Col = 6: .Text = ValidateNull(r("Oleo"))',
    "        End With",
    "        n = n + 1",
    "        r.MoveNext",
    "    Loop",
    "    If r.State <> 0 Then r.Close",
    "",
    "    If lstVencidos.Rows = 1 Then",
    '        MsgBox "Nenhuma troca de \xf3leo vencida encontrada!", vbInformation, "Aviso do Sistema"',
    "    End If",
    "End Sub",
    "",
    "Private Sub cmdAtualizar_Click()",
    "    CarregarGrid",
    "End Sub",
    "",
    "Private Sub cmdFechar_Click()",
    "    Unload Me",
    "End Sub",
    "",
]

all_lines = design + code
text = "\r\n".join(all_lines)
text = text.replace("\r\n", "\n").replace("\r", "\n").replace("\n", "\r\n")

with open(PATH, "wb") as f:
    f.write(text.encode("cp1252"))

print(f"OK - {PATH} criado, {len(all_lines)} linhas")
