# -*- coding: utf-8 -*-
"""
Cria o form OrdemServico\\Forms\\OS_ControleOleo.frm: tela de manutencao
da tabela OS_ControleOleo (LIMITE_KM / LIMITE_PRAZO em MESES por
produto). Grid com coluna de marcacao (igual ao padrao usado em
Produtos_AjusteTributos.frm: ImgMarcadaTODAS/imgDesmarcadaTODAS/
ImgMarcada/imgDesmarcada + lblMarcarTodas), optKM/optPrazo escolhem qual
campo o botao Atualizar grava para os produtos marcados.

IMPORTANTE: os controles de imagem (ImgMarcadaTODAS, imgDesmarcadaTODAS,
ImgMarcada, imgDesmarcada) e o lblMarcarTodas NAO sao criados por este
script - sao recursos binarios (.frx) que só existem copiados do form
Produtos_AjusteTributos.frm dentro do IDE do VB6 (Ctrl+C / Ctrl+V,
mantendo os mesmos nomes). O codigo abaixo ja referencia esses nomes;
o form so compila/roda depois que esses controles forem colados.
"""

PATH = r"C:\projeto\OrdemServico\Forms\OS_ControleOleo.frm"

OLEO_HDR = "\xd3LEO"
CODBARRA_HDR = "C\xd3D. BARRA"
CAPTION = "Controle de Troca de \xd3leo"

design = [
    "VERSION 5.00",
    'Object = "{5E9E78A0-531B-11CF-91F6-C2863C385E30}#1.0#0"; "msflxgrd.ocx"',
    "Begin VB.Form OS_ControleOleo ",
    "   BorderStyle     =   3  'Fixed Dialog",
    '   Caption         =   "%s"' % CAPTION,
    "   ClientHeight    =   4560",
    "   ClientLeft      =   120",
    "   ClientTop       =   465",
    "   ClientWidth     =   8940",
    "   LinkTopic       =   \"Form1\"",
    "   ScaleHeight     =   4560",
    "   ScaleWidth      =   8940",
    "   StartUpPosition =   2  'CenterScreen",
    "   Begin VB.CommandButton cmdFechar ",
    '      Caption         =   "Fechar"',
    "      Height          =   420",
    "      Left            =   7440",
    "      TabIndex        =   5",
    "      Top             =   4020",
    "      Width           =   1400",
    "   End",
    "   Begin VB.CommandButton cmdAtualizar ",
    '      Caption         =   "Atualizar"',
    "      Height          =   420",
    "      Left            =   5940",
    "      TabIndex        =   4",
    "      Top             =   4020",
    "      Width           =   1400",
    "   End",
    "   Begin VB.TextBox txtValor ",
    "      Height          =   315",
    "      Left            =   2640",
    "      TabIndex        =   3",
    "      Top             =   4050",
    "      Width           =   1200",
    "   End",
    "   Begin VB.OptionButton optPrazo ",
    '      Caption         =   "Prazo (meses)"',
    "      Height          =   255",
    "      Left            =   1020",
    "      TabIndex        =   2",
    "      Top             =   4080",
    "      Width           =   1500",
    "   End",
    "   Begin VB.OptionButton optKM ",
    '      Caption         =   "KM"',
    "      Height          =   255",
    "      Left            =   60",
    "      TabIndex        =   1",
    "      Top             =   4080",
    "      Width           =   900",
    "   End",
    "   Begin MSFlexGridLib.MSFlexGrid lstOleo ",
    "      Height          =   3900",
    "      Left            =   60",
    "      TabIndex        =   0",
    "      Top             =   60",
    "      Width           =   8820",
    "      _ExtentX        =   15558",
    "      _ExtentY        =   6879",
    "      _Version        =   393216",
    "      Appearance      =   0",
    "   End",
    "End",
    'Attribute VB_Name = "OS_ControleOleo"',
    "Attribute VB_GlobalNameSpace = False",
    "Attribute VB_Creatable = False",
    "Attribute VB_PredeclaredId = True",
    "Attribute VB_Exposed = False",
]

code = [
    "Option Explicit",
    "",
    "Private Sub Form_Load()",
    "    ConfigurarGrid",
    "    CarregarGrid",
    "",
    "    optKM.Value = True",
    "    optPrazo.Value = False",
    "    txtValor.Enabled = True",
    "End Sub",
    "",
    "Private Sub ConfigurarGrid()",
    "    With lstOleo",
    "        .Cols = 6",
    "        .Rows = 1",
    "        .FixedCols = 0",
    "        .ColWidth(0) = 360",
    "        .ColWidth(1) = 0",
    "        .ColWidth(2) = 1500",
    "        .ColWidth(3) = 4200",
    "        .ColWidth(4) = 1100",
    "        .ColWidth(5) = 1400",
    '        .TextMatrix(0, 2) = "%s"' % CODBARRA_HDR,
    '        .TextMatrix(0, 3) = "%s"' % OLEO_HDR,
    '        .TextMatrix(0, 4) = "KM TROCA"',
    '        .TextMatrix(0, 5) = "TEMPO TROCA"',
    "        .AllowUserResizing = 1",
    "        .SelectionMode = 1",
    "    End With",
    "End Sub",
    "",
    "Private Sub CarregarGrid()",
    "    Dim r As ADODB.Recordset",
    "    Dim sql As String",
    "    Dim n As Integer",
    "    Dim lChk As Long",
    "",
    "    lstOleo.Rows = 1",
    "",
    '    sql = "SELECT produtos.codigo AS var_cod, produtos.cod_barra AS var_codbarra, produtos.descricao AS var_desc, " & _',
    '          "OS_ControleOleo.LIMITE_KM AS var_km, OS_ControleOleo.LIMITE_PRAZO AS var_prazo " & _',
    '          "FROM produtos LEFT JOIN OS_ControleOleo ON OS_ControleOleo.COD_PRODUTO = produtos.codigo " & _',
    '          "WHERE (produtos.descricao LIKE \'%OLEO%\' OR produtos.descricao LIKE \'%' + OLEO_HDR + '%\') AND (produtos.ativo = 1) " & _',
    '          "ORDER BY produtos.descricao"',
    "",
    "    RsOpen r, sql",
    "    n = 1",
    "    Do While Not r.EOF",
    "        With lstOleo",
    "            .Rows = n + 1",
    '            .Row = n: .Col = 0: .Text = ""',
    '            .Row = n: .Col = 1: .Text = ValidateNull(r("var_cod"))',
    '            .Row = n: .Col = 2: .Text = ValidateNull(r("var_codbarra"))',
    '            .Row = n: .Col = 3: .Text = ValidateNull(r("var_desc"))',
    '            .Row = n: .Col = 4: .Text = ValidateNull(r("var_km"))',
    '            .Row = n: .Col = 5: .Text = ValidateNull(r("var_prazo"))',
    "        End With",
    "        n = n + 1",
    "        r.MoveNext",
    "    Loop",
    "    If r.State <> 0 Then r.Close",
    "",
    "    For lChk = 1 To lstOleo.Rows - 1",
    "        lstOleo.Row = lChk",
    "        lstOleo.Col = 0",
    "        Set lstOleo.CellPicture = imgDesmarcada.Picture",
    "        lstOleo.CellPictureAlignment = 4",
    "    Next lChk",
    "",
    "    imgDesmarcadaTODAS.Visible = True",
    "    ImgMarcadaTODAS.Visible = False",
    '    lblMarcarTodas.Caption = "Marcar Todas"',
    "End Sub",
    "",
    "Private Sub lstOleo_Click()",
    "    Dim iRow As Long",
    "",
    "    If lstOleo.Col <> 0 Then Exit Sub",
    "    iRow = lstOleo.Row",
    "    If iRow < 1 Then Exit Sub",
    "",
    '    If lstOleo.TextMatrix(iRow, 0) = "1" Then',
    '        lstOleo.TextMatrix(iRow, 0) = ""',
    "        lstOleo.Row = iRow: lstOleo.Col = 0",
    "        Set lstOleo.CellPicture = imgDesmarcada.Picture",
    "    Else",
    '        lstOleo.TextMatrix(iRow, 0) = "1"',
    "        lstOleo.Row = iRow: lstOleo.Col = 0",
    "        Set lstOleo.CellPicture = ImgMarcada.Picture",
    "    End If",
    "    lstOleo.CellPictureAlignment = 4",
    "End Sub",
    "",
    "Private Sub imgDesmarcadaTODAS_Click()",
    "    Dim i As Long",
    "",
    "    imgDesmarcadaTODAS.Visible = False",
    "    ImgMarcadaTODAS.Visible = True",
    '    lblMarcarTodas.Caption = "Desmarcar Todas"',
    "",
    "    For i = 1 To lstOleo.Rows - 1",
    '        lstOleo.TextMatrix(i, 0) = "1"',
    "        lstOleo.Row = i: lstOleo.Col = 0",
    "        Set lstOleo.CellPicture = ImgMarcada.Picture",
    "        lstOleo.CellPictureAlignment = 4",
    "    Next i",
    "End Sub",
    "",
    "Private Sub ImgMarcadaTODAS_Click()",
    "    Dim i As Long",
    "",
    "    ImgMarcadaTODAS.Visible = False",
    "    imgDesmarcadaTODAS.Visible = True",
    '    lblMarcarTodas.Caption = "Marcar Todas"',
    "",
    "    For i = 1 To lstOleo.Rows - 1",
    '        lstOleo.TextMatrix(i, 0) = ""',
    "        lstOleo.Row = i: lstOleo.Col = 0",
    "        Set lstOleo.CellPicture = imgDesmarcada.Picture",
    "        lstOleo.CellPictureAlignment = 4",
    "    Next i",
    "End Sub",
    "",
    "Private Sub optKM_Click()",
    "    txtValor.Enabled = True",
    "    If Me.Visible Then txtValor.SetFocus",
    "End Sub",
    "",
    "Private Sub optPrazo_Click()",
    "    txtValor.Enabled = True",
    "    If Me.Visible Then txtValor.SetFocus",
    "End Sub",
    "",
    "Private Sub txtValor_KeyPress(KeyAscii As Integer)",
    "    KeyAscii = aNumeros(KeyAscii)",
    "    If KeyAscii = 13 Then",
    "        KeyAscii = 0",
    "        cmdAtualizar_Click",
    "    End If",
    "End Sub",
    "",
    "Private Sub cmdAtualizar_Click()",
    "    Dim i As Long",
    "    Dim lCodProduto As Long",
    "    Dim lValor As Long",
    "    Dim rChk As ADODB.Recordset",
    "    Dim bAlgumMarcado As Boolean",
    "",
    '    If Trim(txtValor.Text) = "" Or Not IsNumeric(txtValor.Text) Then',
    '        MsgBox "Digite um valor num\xe9rico v\xe1lido!", vbInformation, "Aviso do Sistema"',
    "        Exit Sub",
    "    End If",
    "",
    "    lValor = Val(txtValor.Text)",
    "    bAlgumMarcado = False",
    "",
    "    For i = 1 To lstOleo.Rows - 1",
    '        If lstOleo.TextMatrix(i, 0) = "1" Then',
    "            bAlgumMarcado = True",
    "            lCodProduto = Val(lstOleo.TextMatrix(i, 1))",
    "",
    '            Set rChk = dbData.OpenRecordset("SELECT ID FROM OS_ControleOleo WHERE (COD_PRODUTO = " & lCodProduto & ")")',
    "            If rChk.EOF Then",
    "                If optKM.Value = True Then",
    '                    dbData.Execute "INSERT INTO OS_ControleOleo (COD_PRODUTO, LIMITE_KM) VALUES (" & lCodProduto & ", " & lValor & ")"',
    "                Else",
    '                    dbData.Execute "INSERT INTO OS_ControleOleo (COD_PRODUTO, LIMITE_PRAZO) VALUES (" & lCodProduto & ", " & lValor & ")"',
    "                End If",
    "            Else",
    "                If optKM.Value = True Then",
    '                    dbData.Execute "UPDATE OS_ControleOleo SET LIMITE_KM = " & lValor & " WHERE (COD_PRODUTO = " & lCodProduto & ")"',
    "                Else",
    '                    dbData.Execute "UPDATE OS_ControleOleo SET LIMITE_PRAZO = " & lValor & " WHERE (COD_PRODUTO = " & lCodProduto & ")"',
    "                End If",
    "            End If",
    "            rChk.Close",
    "",
    "            If optKM.Value = True Then",
    "                lstOleo.TextMatrix(i, 4) = lValor",
    "            Else",
    "                lstOleo.TextMatrix(i, 5) = lValor",
    "            End If",
    "        End If",
    "    Next i",
    "",
    "    If Not bAlgumMarcado Then",
    '        MsgBox "Nenhum produto marcado no grid!", vbInformation, "Aviso do Sistema"',
    "        Exit Sub",
    "    End If",
    "",
    '    MsgBox "Atualizado com sucesso!", vbInformation, "Aviso do Sistema"',
    "End Sub",
    "",
    "Private Sub cmdFechar_Click()",
    "    Unload Me",
    "End Sub",
    "",
]

all_lines = design + code
text = "\r\n".join(all_lines)
text = text.replace("\r\n", "\n").replace("\r", "\n").replace("\n", "\r\n")

with open(PATH, "wb") as f:
    f.write(text.encode("cp1252"))

print(f"OK - {PATH} criado, {len(all_lines)} linhas")
