# -*- coding: utf-8 -*-
# Gera OnlineCommerce\Forms\frmImportarIBPT.frm
# Form para importar TabelaIBPT a partir de arquivo .csv do IBPT

import os

OUT = 'C:/Projeto/OnlineCommerce/Forms/frmImportarIBPT.frm'

def w1252(s):
    return s.encode('windows-1252')

lines = []
def L(s=''):
    lines.append(s)

# ── Cabecalho ────────────────────────────────────────────────
L('VERSION 5.00')
L('Object = "{F9043C88-F6F2-101A-A3C9-08002B2F49FB}#1.2#0"; "ComDlg32.OCX"')
L('Begin VB.Form frmImportarIBPT ')
L('   BackColor       =   &H00F0F0F0&')
L('   BorderStyle     =   1  \'Fixed Single')
L('   Caption         =   "Importar Tabela IBPT"')
L('   ClientHeight    =   5400')
L('   ClientLeft      =   45')
L('   ClientTop       =   375')
L('   ClientWidth     =   9000')
L('   MaxButton       =   0   \'False')
L('   MinButton       =   0   \'False')
L('   StartUpPosition =   1  \'CenterOwner')

# CommonDialog
L('   Begin MSComDlg.CommonDialog dlgArquivo ')
L('      Left            =   8400')
L('      Top             =   120')
L('      _ExtentX        =   847')
L('      _ExtentY        =   847')
L('      _Version        =   393216')
L('   End')

# Frame principal
L('   Begin VB.Frame fraMain ')
L('      Caption         =   "Arquivo CSV"')
L('      Height          =   1095')
L('      Left            =   120')
L('      Top             =   120')
L('      Width           =   8760')

L('      Begin VB.TextBox txtArquivo')
L('         Height          =   315')
L('         Left            =   120')
L('         Locked          =   -1  \'True')
L('         TabIndex        =   0')
L('         Top             =   480')
L('         Width           =   7560')
L('      End')

L('      Begin VB.CommandButton cmdLocalizar')
L('         Caption         =   "..."')
L('         Height          =   315')
L('         Left            =   7800')
L('         TabIndex        =   1')
L('         Top             =   480')
L('         Width           =   855')
L('      End')

L('   End')  # fraMain

# Frame versoes
L('   Begin VB.Frame fraVersao ')
L('      Caption         =   "Vers\xe3o"')
L('      Height          =   975')
L('      Left            =   120')
L('      Top             =   1320')
L('      Width           =   8760')

L('      Begin VB.Label lblVersaoDB')
L('         BackColor       =   &H00FFFFFF&')
L('         BorderStyle     =   1')
L('         Height          =   285')
L('         Left            =   1920')
L('         Top             =   360')
L('         Width           =   2535')
L('      End')

L('      Begin VB.Label lblVersaoCSV')
L('         BackColor       =   &H00FFFFFF&')
L('         BorderStyle     =   1')
L('         Height          =   285')
L('         Left            =   6240')
L('         Top             =   360')
L('         Width           =   2415')
L('      End')

L('      Begin VB.Label Label1')
L('         Caption         =   "Vers\xe3o no banco:"')
L('         Height          =   255')
L('         Left            =   120')
L('         Top             =   390')
L('         Width           =   1695')
L('      End')

L('      Begin VB.Label Label2')
L('         Caption         =   "Vers\xe3o no CSV:"')
L('         Height          =   255')
L('         Left            =   4920')
L('         Top             =   390')
L('         Width           =   1215')
L('      End')

L('   End')  # fraVersao

# Barra de progresso (label animado)
L('   Begin VB.Label lblProgresso ')
L('      Alignment       =   2  \'Center')
L('      BackColor       =   &H00C0FFC0&')
L('      BorderStyle     =   1')
L('      ForeColor       =   &H00007700&')
L('      Height          =   375')
L('      Left            =   120')
L('      Top             =   2400')
L('      Visible         =   0  \'False')
L('      Width           =   8760')
L('   End')

# Status
L('   Begin VB.Label lblStatus ')
L('      BackColor       =   &H00FFFFFF&')
L('      BorderStyle     =   1')
L('      Height          =   1695')
L('      Left            =   120')
L('      Top             =   2880')
L('      Width           =   8760')
L('   End')

# Botoes
L('   Begin VB.CommandButton cmdImportar ')
L('      Caption         =   "Importar"')
L('      Enabled         =   0   \'False')
L('      Height          =   495')
L('      Left            =   120')
L('      TabIndex        =   2')
L('      Top             =   1920')
L('      Width           =   2055')
L('   End')

L('   Begin VB.CommandButton cmdFechar ')
L('      Caption         =   "Fechar"')
L('      Height          =   495')
L('      Left            =   6960')
L('      TabIndex        =   3')
L('      Top             =   1920')
L('      Width           =   1920')
L('   End')

L('   Begin VB.Label Label3 ')
L('      Caption         =   "Vigência Fim da tabela:"')
L('      Height          =   255')
L('      Left            =   2400')
L('      Top             =   1980')
L('      Width           =   2055')
L('   End')

L('   Begin VB.Label lblVigFim ')
L('      BackColor       =   &H00FFFFFF&')
L('      BorderStyle     =   1')
L('      ForeColor       =   &H000000FF&')
L('      Height          =   255')
L('      Left            =   4560')
L('      Top             =   1980')
L('      Width           =   1335')
L('   End')

L('End')  # Form

# ── Codigo ───────────────────────────────────────────────────
L('Attribute VB_Name = "frmImportarIBPT"')
L('Attribute VB_GlobalNameSpace = False')
L('Attribute VB_Creatable = False')
L('Attribute VB_PredeclaredId = True')
L('Attribute VB_Exposed = False')
L('Option Explicit')
L('')
L('Dim sArquivoCSV As String')
L('Dim sVersaoCSV  As String')
L('Dim sVigFimCSV  As String')
L('')

# Form_Load
L('Private Sub Form_Load()')
L('    CarregarVersaoDB')
L('End Sub')
L('')

# CarregarVersaoDB
L('Private Sub CarregarVersaoDB()')
L('    Dim sVer As String')
L('    Dim sVig As String')
L('    sVer = SQLExecutaRetorno("SELECT TOP 1 versao    FROM TabelaIBPT", "versao",    "")')
L('    sVig = SQLExecutaRetorno("SELECT TOP 1 vigenciafim FROM TabelaIBPT", "vigenciafim", "")')
L('    If sVer = "" Then')
L('        lblVersaoDB.Caption = "(vazia)"')
L('        lblVigFim.Caption   = ""')
L('    Else')
L('        lblVersaoDB.Caption = sVer')
L('        If sVig <> "" Then')
L('            lblVigFim.Caption = Format(CDate(sVig), "dd/mm/yyyy")')
L('            If CDate(sVig) <= Date + 15 Then lblVigFim.ForeColor = vbRed')
L('        End If')
L('    End If')
L('End Sub')
L('')

# cmdLocalizar_Click
L('Private Sub cmdLocalizar_Click()')
L('    On Error GoTo CancelaBrowse')
L('    dlgArquivo.Filter      = "Arquivos CSV (*.csv)|*.csv"')
L('    dlgArquivo.FilterIndex = 1')
L('    dlgArquivo.DialogTitle = "Selecionar Tabela IBPT"')
L('    dlgArquivo.Flags       = &H1000  \'OFN_FILEMUSTEXIST')
L('    dlgArquivo.ShowOpen')
L('    sArquivoCSV = dlgArquivo.FileName')
L('    If sArquivoCSV = "" Then Exit Sub')
L('    txtArquivo.Text = sArquivoCSV')
L('    LerVersaoCSV')
L('    Exit Sub')
L('CancelaBrowse:')
L('End Sub')
L('')

# LerVersaoCSV - le apenas a 1a linha de dados para pegar versao
L('Private Sub LerVersaoCSV()')
L('    Dim iFile As Integer')
L('    Dim sLinha As String')
L('    Dim aCampos() As String')
L('    iFile = FreeFile')
L('    Open sArquivoCSV For Input As #iFile')
L('    Line Input #iFile, sLinha  \' cabecalho - ignora')
L('    If Not EOF(iFile) Then')
L('        Line Input #iFile, sLinha')
L('        aCampos = Split(sLinha, ";")')
L('        If UBound(aCampos) >= 11 Then')
L('            sVersaoCSV = Trim(aCampos(11))')
L('            sVigFimCSV = Trim(aCampos(9))')
L('        End If')
L('    End If')
L('    Close #iFile')
L('    lblVersaoCSV.Caption = sVersaoCSV')
L('    cmdImportar.Enabled = (sVersaoCSV <> "")')
L('End Sub')
L('')

# VersaoMaisNova - compara "AA.N.L"
L('Private Function VersaoMaisNova(vCSV As String, vDB As String) As Boolean')
L('    If vDB = "" Or vDB = "(vazia)" Then VersaoMaisNova = True: Exit Function')
L('    If vCSV = vDB Then VersaoMaisNova = False: Exit Function')
L('    Dim aCSV() As String, aDB() As String')
L('    aCSV = Split(vCSV, ".")')
L('    aDB  = Split(vDB,  ".")')
L('    If UBound(aCSV) < 2 Or UBound(aDB) < 2 Then')
L('        VersaoMaisNova = (vCSV > vDB): Exit Function')
L('    End If')
L('    Dim nAnoCSV As Integer, nAnoDB As Integer')
L('    Dim nSeqCSV As Integer, nSeqDB As Integer')
L('    nAnoCSV = Val(aCSV(0)): nAnoDB = Val(aDB(0))')
L('    nSeqCSV = Val(aCSV(1)): nSeqDB = Val(aDB(1))')
L('    If nAnoCSV <> nAnoDB Then VersaoMaisNova = (nAnoCSV > nAnoDB): Exit Function')
L('    If nSeqCSV <> nSeqDB  Then VersaoMaisNova = (nSeqCSV > nSeqDB): Exit Function')
L('    VersaoMaisNova = (UCase(aCSV(2)) > UCase(aDB(2)))')
L('End Function')
L('')

# cmdImportar_Click
L('Private Sub cmdImportar_Click()')
L('    Dim sVersaoDB As String')
L('    sVersaoDB = lblVersaoDB.Caption')
L('')
L('    If Not VersaoMaisNova(sVersaoCSV, sVersaoDB) Then')
L('        lblStatus.Caption = "A tabela no banco (v" & sVersaoDB & ") j\xe1 est\xe1 atualizada. " & _')
L('                            "A vers\xe3o do CSV (" & sVersaoCSV & ") n\xe3o \xe9 mais nova."')
L('        Exit Sub')
L('    End If')
L('')
L('    Dim resp As Integer')
L('    resp = MsgBox("Ser\xe3o apagados todos os registros atuais e importados " & _')
L('                  "os dados da vers\xe3o " & sVersaoCSV & "." & vbCr & _')
L('                  "Deseja continuar?", vbQuestion + vbYesNo, "Confirmar Importa\xe7\xe3o")')
L('    If resp <> vbYes Then Exit Sub')
L('')
L('    cmdImportar.Enabled  = False')
L('    cmdLocalizar.Enabled = False')
L('    cmdFechar.Enabled    = False')
L('    lblProgresso.Visible = True')
L('    lblStatus.Caption    = ""')
L('')
L('    On Error GoTo ErrImport')
L('')
L('    \' Limpa tabela')
L('    lblProgresso.Caption = "Limpando tabela..."')
L('    DoEvents')
L('    dbData.Execute "DELETE FROM TabelaIBPT"')
L('')
L('    \' Le CSV e insere')
L('    Dim iFile   As Integer')
L('    Dim sLinha  As String')
L('    Dim aCampos() As String')
L('    Dim nTotal  As Long')
L('    Dim nLinha  As Long')
L('    Dim sSQL    As String')
L('')
L('    \' Conta linhas para progresso')
L('    iFile = FreeFile')
L('    Open sArquivoCSV For Input As #iFile')
L('    nTotal = 0')
L('    Do While Not EOF(iFile)')
L('        Line Input #iFile, sLinha')
L('        nTotal = nTotal + 1')
L('    Loop')
L('    Close #iFile')
L('    nTotal = nTotal - 1  \' desconta cabecalho')
L('')
L('    iFile = FreeFile')
L('    Open sArquivoCSV For Input As #iFile')
L('    Line Input #iFile, sLinha  \' pula cabecalho')
L('    nLinha = 0')
L('')
L('    dbData.Execute "BEGIN TRANSACTION"')
L('')
L('    Do While Not EOF(iFile)')
L('        Line Input #iFile, sLinha')
L('        sLinha = Trim(sLinha)')
L('        If sLinha = "" Then GoTo ProxLinha')
L('        aCampos = Split(sLinha, ";")')
L('        If UBound(aCampos) < 12 Then GoTo ProxLinha')
L('')
L('        Dim sCodigo   As String, sEx        As String')
L('        Dim sTipo     As String, sDesc      As String')
L('        Dim sNacFed   As String, sImpFed    As String')
L('        Dim sEstadual As String, sMunicipal As String')
L('        Dim sVigIni   As String, sVigFim    As String')
L('        Dim sChave    As String, sVersao    As String')
L('        Dim sFonte    As String')
L('')
L('        sCodigo   = Trim(aCampos(0))')
L('        sEx       = Trim(aCampos(1)): If sEx = "" Then sEx = "0"')
L('        sTipo     = Trim(aCampos(2)): If sTipo = "" Then sTipo = "0"')
L('        sDesc     = Trim(aCampos(3))')
L('        \' Remove aspas da descricao')
L('        If Left(sDesc, 1) = Chr(34) Then sDesc = Mid(sDesc, 2)')
L('        If Right(sDesc, 1) = Chr(34) Then sDesc = Left(sDesc, Len(sDesc) - 1)')
L('        sDesc     = Replace(sDesc, "\'", "\'\'")')
L('        sNacFed   = Trim(aCampos(4)):  If sNacFed   = "" Then sNacFed   = "0"')
L('        sImpFed   = Trim(aCampos(5)):  If sImpFed   = "" Then sImpFed   = "0"')
L('        sEstadual = Trim(aCampos(6)):  If sEstadual = "" Then sEstadual = "0"')
L('        sMunicipal= Trim(aCampos(7)):  If sMunicipal= "" Then sMunicipal= "0"')
L('        sVigIni   = Trim(aCampos(8))')
L('        sVigFim   = Trim(aCampos(9))')
L('        sChave    = Trim(aCampos(10))')
L('        sVersao   = Trim(aCampos(11))')
L('        sFonte    = Trim(aCampos(12))')
L('')
L('        \' Converte datas dd/mm/yyyy -> SQL CONVERT(date,...,103)')
L('        Dim sIniSQL As String, sFimSQL As String')
L('        sIniSQL = IIf(sVigIni <> "", "CONVERT(date,\'" & sVigIni & "\',103)", "NULL")')
L('        sFimSQL = IIf(sVigFim <> "", "CONVERT(date,\'" & sVigFim & "\',103)", "NULL")')
L('')
L('        sSQL = "INSERT INTO TabelaIBPT " & _')
L('               "(codigo,ex,tipo,descricao,nacionalfederal,importadosfederal," & _')
L('               "estadual,municipal,vigenciainicio,vigenciafim,chave,versao,fonte) VALUES (" & _')
L('               "\'" & sCodigo & "\'," & _')
L('               "\'" & sEx & "\'," & _')
L('               sTipo & "," & _')
L('               "\'" & sDesc & "\'," & _')
L('               sNacFed & "," & sImpFed & "," & sEstadual & "," & sMunicipal & "," & _')
L('               sIniSQL & "," & sFimSQL & "," & _')
L('               "\'" & sChave & "\'," & _')
L('               "\'" & sVersao & "\'," & _')
L('               "\'" & Replace(sFonte,"\'","\'\'") & "\')"')
L('')
L('        dbData.Execute sSQL')
L('        nLinha = nLinha + 1')
L('')
L('        If nLinha Mod 100 = 0 Then')
L('            lblProgresso.Caption = "Importando: " & nLinha & " de " & nTotal & " registros..."')
L('            DoEvents')
L('        End If')
L('ProxLinha:')
L('    Loop')
L('')
L('    Close #iFile')
L('    dbData.Execute "COMMIT TRANSACTION"')
L('')
L('    \' Sincroniza tbNCM: atualiza aliquotas dos NCMs ja existentes')
L('    lblProgresso.Caption = "Sincronizando tbNCM..."')
L('    DoEvents')
L('    dbData.Execute "UPDATE N SET " & _')
L('                   "    N.descricao         = I.descricao, " & _')
L('                   "    N.nacionalfederal   = I.nacionalfederal, " & _')
L('                   "    N.importadosfederal = I.importadosfederal, " & _')
L('                   "    N.estadual          = I.estadual, " & _')
L('                   "    N.municipal         = I.municipal " & _')
L('                   "FROM tbNCM N " & _')
L('                   "INNER JOIN TabelaIBPT I ON I.codigo = N.NCM AND I.ex = \'0\'"')
L('')
L('    \' Insere NCMs novos que ainda nao existem em tbNCM')
L('    dbData.Execute "INSERT INTO tbNCM (NCM, descricao, nacionalfederal, importadosfederal, estadual, municipal) " & _')
L('                   "SELECT I.codigo, I.descricao, I.nacionalfederal, I.importadosfederal, I.estadual, I.municipal " & _')
L('                   "FROM TabelaIBPT I " & _')
L('                   "WHERE I.ex = \'0\' " & _')
L('                   "AND NOT EXISTS (SELECT 1 FROM tbNCM N WHERE N.NCM = I.codigo)"')
L('')
L('    lblProgresso.Caption = "Conclu\xeddo! " & nLinha & " registros importados."')
L('    lblStatus.Caption = "Tabela IBPT vers\xe3o " & sVersaoCSV & " importada com sucesso!" & vbCr & _')
L('                        "Registros: " & nLinha & "  |  Vig\xeancia: " & sVigIni & " a " & sVigFim')
L('    CarregarVersaoDB')
L('    cmdFechar.Enabled    = True')
L('    cmdLocalizar.Enabled = True')
L('    Exit Sub')
L('')
L('ErrImport:')
L('    Dim sErr As String')
L('    sErr = Err.Description')
L('    On Error Resume Next')
L('    Close #iFile')
L('    dbData.Execute "ROLLBACK TRANSACTION"')
L('    lblProgresso.Caption = "Erro na importa\xe7\xe3o!"')
L('    lblProgresso.BackColor = vbRed')
L('    lblStatus.Caption = "ERRO: " & sErr')
L('    cmdImportar.Enabled  = True')
L('    cmdLocalizar.Enabled = True')
L('    cmdFechar.Enabled    = True')
L('End Sub')
L('')

# cmdFechar
L('Private Sub cmdFechar_Click()')
L('    Unload Me')
L('End Sub')

# ── Gravar ───────────────────────────────────────────────────
content = '\r\n'.join(lines) + '\r\n'
with open(OUT, 'wb') as f:
    f.write(content.encode('windows-1252', errors='replace'))

print(f'frmImportarIBPT.frm gerado: {OUT}')
