# -*- coding: utf-8 -*-
# Gera OnlineCommerce\Forms\frmNCM_Cadastro.frm
# CRUD completo para tbNCM com grid de consulta

OUT = 'C:/Projeto/OnlineCommerce/Forms/frmNCM_Cadastro.frm'

lines = []
def L(s=''): lines.append(s)

# ── Definicao do Form ────────────────────────────────────────
L('VERSION 5.00')
L('Object = "{5E9E78A0-531B-11CF-91F6-C2863C385E30}#1.0#0"; "MSFlxGrd.ocx"')
L('Begin VB.Form frmNCM_Cadastro ')
L('   Caption         =   "Cadastro de NCM"')
L('   ClientHeight    =   9600')
L('   ClientLeft      =   45')
L('   ClientTop       =   375')
L('   ClientWidth     =   15600')
L('   StartUpPosition =   1  \'CenterOwner')

# ── Filtro ──────────────────────────────────────────────────
L('   Begin VB.Frame fraFiltro ')
L('      Caption         =   "Consulta"')
L('      Height          =   615')
L('      Left            =   120')
L('      Top             =   120')
L('      Width           =   15360')
L('      Begin VB.ComboBox cboCriterio ')
L('         Height          =   315')
L('         Left            =   120')
L('         Style           =   2')
L('         TabIndex        =   0')
L('         Top             =   210')
L('         Width           =   1935')
L('      End')
L('      Begin VB.TextBox txtBusca ')
L('         Height          =   315')
L('         Left            =   2160')
L('         TabIndex        =   1')
L('         Top             =   210')
L('         Width           =   10215')
L('      End')
L('      Begin VB.CommandButton cmdConsultar ')
L('         Caption         =   "Consultar"')
L('         Height          =   315')
L('         Left            =   12480')
L('         TabIndex        =   2')
L('         Top             =   210')
L('         Width           =   1335')
L('      End')
L('      Begin VB.CommandButton cmdLimpar ')
L('         Caption         =   "Todos"')
L('         Height          =   315')
L('         Left            =   13920')
L('         TabIndex        =   3')
L('         Top             =   210')
L('         Width           =   1335')
L('      End')
L('   End')

# ── Grid ────────────────────────────────────────────────────
L('   Begin MSFlexGridLib.MSFlexGrid grdNCM ')
L('      Height          =   4215')
L('      Left            =   120')
L('      TabIndex        =   4')
L('      Top             =   840')
L('      Width           =   15360')
L('      _ExtentX        =   27090')
L('      _ExtentY        =   7435')
L('      _Version        =   393216')
L('      Rows            =   1')
L('      Cols            =   9')
L('      FixedRows       =   1')
L('      FixedCols       =   0')
L('      AllowUserResizing=  1')
L('   End')

# ── Frame windowed sobre o grid (Label windowless nao aparece sobre ActiveX) ──
L('   Begin VB.Frame fraCarregando ')
L('      BackColor       =   &H00FFFFFF&')
L('      BorderStyle     =   1')
L('      Caption         =   ""')
L('      Height          =   900')
L('      Left            =   5160')
L('      TabIndex        =   19')
L('      Top             =   2550')
L('      Visible         =   0')
L('      Width           =   5280')
L('      Begin VB.Label lblCarregando ')
L('         Alignment       =   2')
L('         BackColor       =   &H00FFFFFF&')
L('         BackStyle       =   1')
L('         Caption         =   "CARREGANDO..."')
L('         BeginProperty Font ')
L('            Name            =   "MS Sans Serif"')
L('            Size            =   15')
L('            Charset         =   0')
L('            Weight          =   700')
L('            Underline       =   0')
L('            Italic          =   0')
L('            Strikethrough   =   0')
L('         EndProperty')
L('         ForeColor       =   &H000000FF&')
L('         Height          =   600')
L('         Left            =   120')
L('         Top             =   120')
L('         Width           =   5040')
L('      End')
L('   End')

# ── Frame de edicao ─────────────────────────────────────────
L('   Begin VB.Frame fraEdicao ')
L('      Caption         =   "Dados do NCM"')
L('      Height          =   4215')
L('      Left            =   120')
L('      Top             =   5160')
L('      Width           =   15360')

# linha 1: NCM + Descricao
L('      Begin VB.Label lbl1 ')
L('         Caption         =   "NCM:"')
L('         Height          =   255')
L('         Left            =   120')
L('         Top             =   360')
L('         Width           =   615')
L('      End')
L('      Begin VB.TextBox txtNCM ')
L('         Height          =   315')
L('         Left            =   840')
L('         MaxLength       =   10')
L('         TabIndex        =   5')
L('         Top             =   330')
L('         Width           =   1455')
L('      End')
L('      Begin VB.Label lbl2 ')
L('         Caption         =   "Descri\xe7\xe3o:"')
L('         Height          =   255')
L('         Left            =   2400')
L('         Top             =   360')
L('         Width           =   855')
L('      End')
L('      Begin VB.TextBox txtDescricao ')
L('         Height          =   315')
L('         Left            =   3360')
L('         TabIndex        =   6')
L('         Top             =   330')
L('         Width           =   11880')
L('      End')

# linha 2: aliquotas
L('      Begin VB.Label lbl3 ')
L('         Caption         =   "Nac. Federal %:"')
L('         Height          =   255')
L('         Left            =   120')
L('         Top             =   780')
L('         Width           =   1455')
L('      End')
L('      Begin VB.TextBox txtNacFed ')
L('         Height          =   315')
L('         Left            =   1680')
L('         TabIndex        =   7')
L('         Top             =   750')
L('         Width           =   975')
L('      End')
L('      Begin VB.Label lbl4 ')
L('         Caption         =   "Imp. Federal %:"')
L('         Height          =   255')
L('         Left            =   2760')
L('         Top             =   780')
L('         Width           =   1455')
L('      End')
L('      Begin VB.TextBox txtImpFed ')
L('         Height          =   315')
L('         Left            =   4320')
L('         TabIndex        =   8')
L('         Top             =   750')
L('         Width           =   975')
L('      End')
L('      Begin VB.Label lbl5 ')
L('         Caption         =   "Estadual %:"')
L('         Height          =   255')
L('         Left            =   5400')
L('         Top             =   780')
L('         Width           =   1095')
L('      End')
L('      Begin VB.TextBox txtEstadual ')
L('         Height          =   315')
L('         Left            =   6600')
L('         TabIndex        =   9')
L('         Top             =   750')
L('         Width           =   975')
L('      End')
L('      Begin VB.Label lbl6 ')
L('         Caption         =   "Municipal %:"')
L('         Height          =   255')
L('         Left            =   7680')
L('         Top             =   780')
L('         Width           =   1095')
L('      End')
L('      Begin VB.TextBox txtMunicipal ')
L('         Height          =   315')
L('         Left            =   8880')
L('         TabIndex        =   10')
L('         Top             =   750')
L('         Width           =   975')
L('      End')

# linha 3: reforma IBS/CBS
L('      Begin VB.Label lbl7 ')
L('         Caption         =   "cClassTrib IBS:"')
L('         Height          =   255')
L('         Left            =   120')
L('         Top             =   1200')
L('         Width           =   1455')
L('      End')
L('      Begin VB.ComboBox cboClassIBS ')
L('         Height          =   315')
L('         Left            =   1680')
L('         TabIndex        =   11')
L('         Top             =   1170')
L('         Width           =   5895')
L('      End')

# linha 4: IS
L('      Begin VB.Label lbl8 ')
L('         Caption         =   "cClassTrib IS:"')
L('         Height          =   255')
L('         Left            =   120')
L('         Top             =   1650')
L('         Width           =   1455')
L('      End')
L('      Begin VB.ComboBox cboClassIS ')
L('         Height          =   315')
L('         Left            =   1680')
L('         TabIndex        =   12')
L('         Top             =   1620')
L('         Width           =   5895')
L('      End')
L('      Begin VB.Label lbl9 ')
L('         Caption         =   "Tipo C\xe1lculo IS:"')
L('         Height          =   255')
L('         Left            =   7800')
L('         Top             =   1650')
L('         Width           =   1455')
L('      End')
L('      Begin VB.ComboBox cboTipoCalcIS ')
L('         Height          =   315')
L('         Left            =   9360')
L('         Style           =   2')
L('         TabIndex        =   13')
L('         Top             =   1620')
L('         Width           =   2535')
L('      End')

# label status
L('      Begin VB.Label lblMsg ')
L('         ForeColor       =   &H000000FF&')
L('         Height          =   255')
L('         Left            =   120')
L('         Top             =   2160')
L('         Width           =   11895')
L('      End')

# botoes CRUD
L('      Begin VB.CommandButton cmdNovo ')
L('         Caption         =   "Novo"')
L('         Height          =   495')
L('         Left            =   120')
L('         TabIndex        =   14')
L('         Top             =   2520')
L('         Width           =   1335')
L('      End')
L('      Begin VB.CommandButton cmdSalvar ')
L('         Caption         =   "Salvar"')
L('         Enabled         =   0')
L('         Height          =   495')
L('         Left            =   1560')
L('         TabIndex        =   15')
L('         Top             =   2520')
L('         Width           =   1335')
L('      End')
L('      Begin VB.CommandButton cmdExcluir ')
L('         Caption         =   "Excluir"')
L('         Enabled         =   0')
L('         Height          =   495')
L('         Left            =   3000')
L('         TabIndex        =   16')
L('         Top             =   2520')
L('         Width           =   1335')
L('      End')
L('      Begin VB.CommandButton cmdCancelar ')
L('         Caption         =   "Cancelar"')
L('         Enabled         =   0')
L('         Height          =   495')
L('         Left            =   4440')
L('         TabIndex        =   17')
L('         Top             =   2520')
L('         Width           =   1335')
L('      End')
L('      Begin VB.CommandButton cmdFechar ')
L('         Caption         =   "Fechar"')
L('         Height          =   495')
L('         Left            =   13920')
L('         TabIndex        =   18')
L('         Top             =   2520')
L('         Width           =   1335')
L('      End')

L('   End')  # fraEdicao
L('End')     # Form

# ── Codigo ───────────────────────────────────────────────────
L('Attribute VB_Name = "frmNCM_Cadastro"')
L('Attribute VB_GlobalNameSpace = False')
L('Attribute VB_Creatable = False')
L('Attribute VB_PredeclaredId = True')
L('Attribute VB_Exposed = False')
L('Option Explicit')
L('')
L('Dim sModoEdicao As String  \' "Novo" ou "Editar"')
L('')

# Form_Load
L('Private Sub Form_Load()')
L('    cboCriterio.AddItem "NCM"')
L('    cboCriterio.AddItem "Descri\xe7\xe3o"')
L('    cboCriterio.ListIndex = 0')
L('')
L('    cboTipoCalcIS.AddItem "0 - N\xe3o tem IS"')
L('    cboTipoCalcIS.AddItem "1 - Ad Valorem (%)"')
L('    cboTipoCalcIS.AddItem "2 - Ad Rem (R$)"')
L('    cboTipoCalcIS.ListIndex = 0')
L('')
L('    PreencherClassIBS')
L('    PreencherClassIS')
L('    ConfigurarGrid')
L('    HabilitarEdicao False')
L('    txtBusca.Text = "0101"')
L('    cmdConsultar_Click')
L('End Sub')
L('')

# ConfigurarGrid
L('Private Sub ConfigurarGrid()')
L('    With grdNCM')
L('        .TextMatrix(0, 0) = "NCM"')
L('        .TextMatrix(0, 1) = "Descri\xe7\xe3o"')
L('        .TextMatrix(0, 2) = "Nac. Fed %"')
L('        .TextMatrix(0, 3) = "Imp. Fed %"')
L('        .TextMatrix(0, 4) = "Estadual %"')
L('        .TextMatrix(0, 5) = "Municipal %"')
L('        .TextMatrix(0, 6) = "ClassTrib IBS"')
L('        .TextMatrix(0, 7) = "ClassTrib IS"')
L('        .TextMatrix(0, 8) = "Tipo IS"')
L('        .ColWidth(0) = 1200')
L('        .ColWidth(1) = 6000')
L('        .ColWidth(2) = 1200')
L('        .ColWidth(3) = 1200')
L('        .ColWidth(4) = 1200')
L('        .ColWidth(5) = 1200')
L('        .ColWidth(6) = 1500')
L('        .ColWidth(7) = 1500')
L('        .ColWidth(8) = 1200')
L('    End With')
L('End Sub')
L('')

# PreencherClassIBS
L('Private Sub PreencherClassIBS()')
L('    Dim rCls As ADODB.Recordset')
L('    cboClassIBS.Clear')
L('    cboClassIBS.AddItem "(nenhum)"')
L('    RsOpen rCls, "SELECT DISTINCT cClassTrib FROM TbIBSCBSClassTrib ORDER BY cClassTrib"')
L('    Do While Not rCls.EOF')
L('        cboClassIBS.AddItem ValidateNull(rCls("cClassTrib"))')
L('        rCls.MoveNext')
L('    Loop')
L('    If rCls.State <> 0 Then rCls.Close')
L('    cboClassIBS.ListIndex = 0')
L('End Sub')
L('')

# PreencherClassIS
L('Private Sub PreencherClassIS()')
L('    cboClassIS.Clear')
L('    cboClassIS.AddItem "(nenhum)"')
L('    cboClassIS.AddItem "900001 - Vinhos, Espumantes e Cacha\xe7as"')
L('    cboClassIS.AddItem "900002 - Cervejas e Chopes"')
L('    cboClassIS.AddItem "900003 - U\xedsque, Gin, Vodka (Destilados)"')
L('    cboClassIS.AddItem "900010 - Refrigerantes e Sucos com A\xe7\xfacar"')
L('    cboClassIS.AddItem "900011 - Energ\xe9ticos e Bebidas Esportivas"')
L('    cboClassIS.AddItem "900020 - Ve\xedculos (Autom\xf3veis poluentes)"')
L('    cboClassIS.AddItem "900040 - Cigarros e fumo"')
L('    cboClassIS.ListIndex = 0')
L('End Sub')
L('')

# CarregarGrid
L('Private Sub CarregarGrid(sFiltroSQL As String, Optional bMostrarAnim As Boolean = False)')
L('    Const MAX_TODOS As Long = 1000')
L('    Dim rG As ADODB.Recordset')
L('    Dim sSQL As String')
L('    Dim i As Long')
L('    Dim nDots As Integer')
L('    Dim bLimitado As Boolean')
L('    bLimitado = False')
L('    If bMostrarAnim Then')
L('        fraCarregando.ZOrder 0')
L('        lblCarregando.Caption = "CARREGANDO..."')
L('        fraCarregando.Visible = True')
L('        DoEvents')
L('    End If')
L('    If sFiltroSQL = "" Then')
L('        sSQL = "SELECT TOP " & MAX_TODOS & " NCM, descricao, nacionalfederal, importadosfederal, " & _')
L('               "estadual, municipal, cClassTrib_IBS, cClassTrib_IS, tipo_calculo_is " & _')
L('               "FROM tbNCM ORDER BY NCM"')
L('        bLimitado = True')
L('    Else')
L('        sSQL = "SELECT NCM, descricao, nacionalfederal, importadosfederal, " & _')
L('               "estadual, municipal, cClassTrib_IBS, cClassTrib_IS, tipo_calculo_is " & _')
L('               "FROM tbNCM WHERE " & sFiltroSQL & " ORDER BY NCM"')
L('    End If')
L('    RsOpen rG, sSQL')
L('    grdNCM.Rows = 1')
L('    Do While Not rG.EOF')
L('        grdNCM.Rows = grdNCM.Rows + 1')
L('        i = grdNCM.Rows - 1')
L('        grdNCM.TextMatrix(i, 0) = ValidateNull(rG("NCM"))')
L('        grdNCM.TextMatrix(i, 1) = ValidateNull(rG("descricao"))')
L('        grdNCM.TextMatrix(i, 2) = FormatNumber(rG("nacionalfederal"),   2)')
L('        grdNCM.TextMatrix(i, 3) = FormatNumber(rG("importadosfederal"), 2)')
L('        grdNCM.TextMatrix(i, 4) = FormatNumber(rG("estadual"),          2)')
L('        grdNCM.TextMatrix(i, 5) = FormatNumber(rG("municipal"),         2)')
L('        grdNCM.TextMatrix(i, 6) = ValidateNull(rG("cClassTrib_IBS"))')
L('        grdNCM.TextMatrix(i, 7) = ValidateNull(rG("cClassTrib_IS"))')
L('        grdNCM.TextMatrix(i, 8) = ValidateNull(rG("tipo_calculo_is"))')
L('        If bMostrarAnim And (i Mod 100 = 0) Then')
L('            nDots = (nDots Mod 3) + 1')
L('            lblCarregando.Caption = "CARREGANDO" & String(nDots, ".")')
L('            DoEvents')
L('        End If')
L('        rG.MoveNext')
L('    Loop')
L('    If rG.State <> 0 Then rG.Close')
L('    If bMostrarAnim Then fraCarregando.Visible = False')
L('    If bLimitado Then')
L('        lblMsg.Caption = "Exibindo os primeiros " & MAX_TODOS & " registros. Use a busca para filtrar."')
L('    Else')
L('        lblMsg.Caption = grdNCM.Rows - 1 & " registro(s) encontrado(s)."')
L('    End If')
L('End Sub')
L('')

# HabilitarEdicao
L('Private Sub HabilitarEdicao(bHab As Boolean)')
L('    txtNCM.Enabled       = bHab')
L('    txtDescricao.Enabled = bHab')
L('    txtNacFed.Enabled    = bHab')
L('    txtImpFed.Enabled    = bHab')
L('    txtEstadual.Enabled  = bHab')
L('    txtMunicipal.Enabled = bHab')
L('    cboClassIBS.Enabled  = bHab')
L('    cboClassIS.Enabled   = bHab')
L('    cboTipoCalcIS.Enabled= bHab')
L('    cmdSalvar.Enabled    = bHab')
L('    cmdCancelar.Enabled  = bHab')
L('    txtNCM.Locked        = (sModoEdicao = "Editar")')
L('End Sub')
L('')

# LimparCampos
L('Private Sub LimparCampos()')
L('    txtNCM.Text      = ""')
L('    txtDescricao.Text= ""')
L('    txtNacFed.Text   = "0,00"')
L('    txtImpFed.Text   = "0,00"')
L('    txtEstadual.Text = "0,00"')
L('    txtMunicipal.Text= "0,00"')
L('    cboClassIBS.ListIndex  = 0')
L('    cboClassIS.ListIndex   = 0')
L('    cboTipoCalcIS.ListIndex= 0')
L('End Sub')
L('')

# PreencherCampos - a partir de uma linha do grid
L('Private Sub PreencherCampos(nRow As Integer)')
L('    txtNCM.Text       = grdNCM.TextMatrix(nRow, 0)')
L('    txtDescricao.Text = grdNCM.TextMatrix(nRow, 1)')
L('    txtNacFed.Text    = grdNCM.TextMatrix(nRow, 2)')
L('    txtImpFed.Text    = grdNCM.TextMatrix(nRow, 3)')
L('    txtEstadual.Text  = grdNCM.TextMatrix(nRow, 4)')
L('    txtMunicipal.Text = grdNCM.TextMatrix(nRow, 5)')
L('    SelecionarNoCombo cboClassIBS,   grdNCM.TextMatrix(nRow, 6)')
L('    SelecionarNoCombo cboClassIS,    Left(grdNCM.TextMatrix(nRow, 7), 6)')
L('    cboTipoCalcIS.ListIndex = Val(grdNCM.TextMatrix(nRow, 8))')
L('End Sub')
L('')

# SelecionarNoCombo local
L('Private Sub SelecionarNoCombo(cbo As ComboBox, sVal As String)')
L('    Dim i As Integer')
L('    cbo.ListIndex = 0')
L('    If sVal = "" Then Exit Sub')
L('    For i = 0 To cbo.ListCount - 1')
L('        If Left(cbo.List(i), Len(sVal)) = sVal Then')
L('            cbo.ListIndex = i')
L('            Exit Sub')
L('        End If')
L('    Next i')
L('End Sub')
L('')

# grdNCM_Click
L('Private Sub grdNCM_Click()')
L('    If grdNCM.Row < 1 Then Exit Sub')
L('    sModoEdicao = "Editar"')
L('    PreencherCampos grdNCM.Row')
L('    HabilitarEdicao True')
L('    cmdExcluir.Enabled = True')
L('    lblMsg.Caption = ""')
L('End Sub')
L('')

# cmdConsultar_Click
L('Private Sub cmdConsultar_Click()')
L('    Dim sFiltro As String')
L('    sFiltro = ""')
L('    If Trim(txtBusca.Text) <> "" Then')
L('        If cboCriterio.Text = "NCM" Then')
L('            If Len(Trim(txtBusca.Text)) >= 8 Then')
L('                sFiltro = "NCM = \'" & Trim(txtBusca.Text) & "\'"')
L('            Else')
L('                sFiltro = "NCM LIKE \'" & Trim(txtBusca.Text) & "%\'"')
L('            End If')
L('        Else')
L('            sFiltro = "descricao LIKE \'%" & Trim(txtBusca.Text) & "%\'"')
L('        End If')
L('    End If')
L('    CarregarGrid sFiltro')
L('End Sub')
L('')

# cmdLimpar_Click
L('Private Sub cmdLimpar_Click()')
L('    txtBusca.Text = ""')
L('    CarregarGrid "", True')
L('End Sub')
L('')

# cmdNovo_Click
L('Private Sub cmdNovo_Click()')
L('    sModoEdicao = "Novo"')
L('    LimparCampos')
L('    HabilitarEdicao True')
L('    cmdExcluir.Enabled = False')
L('    txtNCM.SetFocus')
L('End Sub')
L('')

# Funcao auxiliar para ler decimal do campo texto
L('Private Function LerDecimal(sTxt As String) As Double')
L('    LerDecimal = Val(Replace(Replace(Trim(sTxt), ".", ""), ",", "."))')
L('End Function')
L('')
# Converte Double para string com ponto decimal (locale-safe para SQL)
L('Private Function SQLNum(d As Double) As String')
L('    SQLNum = Replace(CStr(d), ",", ".")')
L('End Function')
L('')

# cmdSalvar_Click
L('Private Sub cmdSalvar_Click()')
L('    If Trim(txtNCM.Text) = "" Then')
L('        MsgBox "Informe o c\xf3digo NCM.", vbExclamation')
L('        txtNCM.SetFocus: Exit Sub')
L('    End If')
L('    Dim sNCM    As String: sNCM    = Trim(txtNCM.Text)')
L('    Dim sDesc   As String: sDesc   = Replace(Trim(txtDescricao.Text), "\'", "\'\'")')
L('    Dim dNF     As Double: dNF     = LerDecimal(txtNacFed.Text)')
L('    Dim dIF     As Double: dIF     = LerDecimal(txtImpFed.Text)')
L('    Dim dEst    As Double: dEst    = LerDecimal(txtEstadual.Text)')
L('    Dim dMun    As Double: dMun    = LerDecimal(txtMunicipal.Text)')
L('    Dim sCIBS   As String')
L('    Dim sCIS    As String')
L('    Dim nTipo   As Integer')
L('    sCIBS  = IIf(cboClassIBS.ListIndex <= 0,  "", Left(cboClassIBS.Text, 6))')
L('    sCIS   = IIf(cboClassIS.ListIndex  <= 0,  "", Left(cboClassIS.Text,  6))')
L('    nTipo  = cboTipoCalcIS.ListIndex')
L('    Dim sSQL As String')
L('    Dim nExiste As Long')
L('    On Error GoTo ErrSalvar')
L('    If sModoEdicao = "Novo" Then')
L('        nExiste = SQLExecutaRetorno("SELECT COUNT(*) AS N FROM tbNCM WHERE NCM=\'" & sNCM & "\'", "N", 0)')
L('        If nExiste > 0 Then')
L('            MsgBox "NCM " & sNCM & " j\xe1 est\xe1 cadastrado. Use o grid para editar.", vbExclamation')
L('            Exit Sub')
L('        End If')
L('        sSQL = "INSERT INTO tbNCM (NCM, descricao, nacionalfederal, importadosfederal, " & _')
L('               "estadual, municipal, cClassTrib_IBS, cClassTrib_IS, tipo_calculo_is) VALUES (" & _')
L('               "\'" & sNCM & "\', \'" & sDesc & "\', " & _')
L('               SQLNum(dNF) & ", " & SQLNum(dIF) & ", " & SQLNum(dEst) & ", " & SQLNum(dMun) & ", " & _')
L('               "\'" & sCIBS & "\', \'" & sCIS & "\', " & nTipo & ")"')
L('    Else')
L('        sSQL = "UPDATE tbNCM SET " & _')
L('               "descricao=\'" & sDesc & "\', " & _')
L('               "nacionalfederal=" & SQLNum(dNF) & ", importadosfederal=" & SQLNum(dIF) & ", " & _')
L('               "estadual=" & SQLNum(dEst) & ", municipal=" & SQLNum(dMun) & ", " & _')
L('               "cClassTrib_IBS=\'" & sCIBS & "\', " & _')
L('               "cClassTrib_IS=\'" & sCIS & "\', " & _')
L('               "tipo_calculo_is=" & nTipo & " " & _')
L('               "WHERE NCM=\'" & sNCM & "\'"')
L('    End If')
L('    dbData.Execute sSQL')
L('    lblMsg.Caption = "Registro salvo com sucesso."')
L('    cmdConsultar_Click')
L('    HabilitarEdicao False')
L('    cmdExcluir.Enabled = False')
L('    sModoEdicao = ""')
L('    Exit Sub')
L('ErrSalvar:')
L('    MsgBox "Erro ao salvar: " & Err.Description, vbCritical')
L('End Sub')
L('')

# cmdExcluir_Click
L('Private Sub cmdExcluir_Click()')
L('    If Trim(txtNCM.Text) = "" Then Exit Sub')
L('    If MsgBox("Excluir o NCM " & txtNCM.Text & "?", vbQuestion + vbYesNo) <> vbYes Then Exit Sub')
L('    On Error GoTo ErrExcluir')
L('    dbData.Execute "DELETE FROM tbNCM WHERE NCM=\'" & Trim(txtNCM.Text) & "\'"')
L('    lblMsg.Caption = "Registro exclu\xeddo."')
L('    LimparCampos')
L('    HabilitarEdicao False')
L('    cmdExcluir.Enabled = False')
L('    cmdConsultar_Click')
L('    Exit Sub')
L('ErrExcluir:')
L('    MsgBox "Erro ao excluir: " & Err.Description, vbCritical')
L('End Sub')
L('')

# cmdCancelar_Click
L('Private Sub cmdCancelar_Click()')
L('    LimparCampos')
L('    HabilitarEdicao False')
L('    cmdExcluir.Enabled = False')
L('    sModoEdicao = ""')
L('    lblMsg.Caption = ""')
L('End Sub')
L('')

# cmdFechar_Click
L('Private Sub cmdFechar_Click()')
L('    Unload Me')
L('End Sub')
L('')

# txtBusca Enter
L('Private Sub txtBusca_KeyPress(KeyAscii As Integer)')
L('    If KeyAscii = 13 Then cmdConsultar_Click')
L('End Sub')

# ── Gravar ───────────────────────────────────────────────────
content = '\r\n'.join(lines) + '\r\n'
with open(OUT, 'wb') as f:
    f.write(content.encode('windows-1252', errors='replace'))
print(f'OK: {OUT}')
