"""
criar_frmDIFAL_Cadastro.py

Gera C:\Projeto\OnlineCommerce\Forms\frmDIFAL_Cadastro.frm
e adiciona a referencia no OnlineCommerce.vbp.

Tabela: TribRegraDifalUF
Campos: ID, UF_Destino, AliquotaInterna, AliquotaFCP,
        DataInicioVigencia, DataFimVigencia, TipoCalculo,
        FCPCompoeBase, Observacao
"""
import sys, shutil, os

FRM  = r"C:\Projeto\OnlineCommerce\Forms\frmDIFAL_Cadastro.frm"
VBP  = r"C:\Projeto\OnlineCommerce\OnlineCommerce.vbp"
VBP_BAK = VBP + ".bak_difal_form"

def norm(b):
    return b.replace(b"\r\n", b"\n").replace(b"\r", b"\n").replace(b"\n", b"\r\n")

# ---------------------------------------------------------------------------
# Conteudo do .frm (cp1252)
# Caracteres especiais:
#   i-agudo  = \xed   (i com acento agudo: i)
#   a-agudo  = \xe1   (a com acento agudo: a)
#   e-circ   = \xea   (e com acento circunflexo: e)
#   o-til    = \xf5   (o com til: o)
#   c-cedil  = \xe7   (c cedilha: c)
#   a-til    = \xe3   (a com til: a)
#   u-agudo  = \xfa   (u agudo: u)
# ---------------------------------------------------------------------------

FRM_CONTENT = (
b"VERSION 5.00\r\n"
b"Object = \"{5E9E78A0-531B-11CF-91F6-C2863C385E30}#1.0#0\"; \"msflxgrd.ocx\"\r\n"
b"Begin VB.Form frmDIFAL_Cadastro \r\n"
b"   BorderStyle     =   3  'Fixed Dialog\r\n"
b"   Caption         =   \"Cadastro DIFAL - Regras por UF de Destino\"\r\n"
b"   ClientHeight    =   7560\r\n"
b"   ClientLeft      =   45\r\n"
b"   ClientTop       =   375\r\n"
b"   ClientWidth     =   14400\r\n"
b"   LinkTopic       =   \"Form1\"\r\n"
b"   MaxButton       =   0   'False\r\n"
b"   MinButton       =   0   'False\r\n"
b"   ScaleHeight     =   7560\r\n"
b"   ScaleWidth      =   14400\r\n"
b"   ShowInTaskbar   =   0   'False\r\n"
b"   StartUpPosition =   2  'CenterScreen\r\n"

# --- Grid principal ---
b"   Begin MSFlexGridLib.MSFlexGrid lstDIFAL \r\n"
b"      Height          =   4200\r\n"
b"      Left            =   120\r\n"
b"      TabIndex        =   0\r\n"
b"      Top             =   960\r\n"
b"      Width           =   14160\r\n"
b"      _ExtentX        =   24977\r\n"
b"      _ExtentY        =   7408\r\n"
b"      _Version        =   393216\r\n"
b"      Cols            =   9\r\n"
b"      FixedCols       =   0\r\n"
b"   End\r\n"

# --- Frame Filtros ---
b"   Begin VB.Frame frmFiltros \r\n"
b"      Caption         =   \"Filtros\"\r\n"
b"      Height          =   720\r\n"
b"      Left            =   120\r\n"
b"      TabIndex        =   15\r\n"
b"      Top             =   120\r\n"
b"      Width           =   14160\r\n"
b"      Begin VB.TextBox txtFiltroUF \r\n"
b"         Height          =   315\r\n"
b"         Left            =   600\r\n"
b"         MaxLength       =   2\r\n"
b"         TabIndex        =   1\r\n"
b"         Top             =   240\r\n"
b"         Width           =   720\r\n"
b"      End\r\n"
b"      Begin VB.CommandButton cmdLocalizar \r\n"
b"         Caption         =   \"Localizar\"\r\n"
b"         Height          =   375\r\n"
b"         Left            =   1440\r\n"
b"         TabIndex        =   2\r\n"
b"         Top             =   210\r\n"
b"         Width           =   1200\r\n"
b"      End\r\n"
b"      Begin VB.CommandButton cmdLimpar \r\n"
b"         Caption         =   \"Limpar\"\r\n"
b"         Height          =   375\r\n"
b"         Left            =   2760\r\n"
b"         TabIndex        =   3\r\n"
b"         Top             =   210\r\n"
b"         Width           =   1200\r\n"
b"      End\r\n"
b"      Begin VB.Label lblFiltroUF \r\n"
b"         Caption         =   \"UF:\"\r\n"
b"         Height          =   252\r\n"
b"         Left            =   120\r\n"
b"         TabIndex        =   16\r\n"
b"         Top             =   270\r\n"
b"         Width           =   480\r\n"
b"      End\r\n"
b"   End\r\n"

# --- Frame Dados ---
b"   Begin VB.Frame frmDados \r\n"
b"      Caption         =   \"Dados\"\r\n"
b"      Height          =   2400\r\n"
b"      Left            =   120\r\n"
b"      TabIndex        =   17\r\n"
b"      Top             =   5280\r\n"
b"      Width           =   14160\r\n"

# Row 1 - UF
b"      Begin VB.Label lblUF \r\n"
b"         Caption         =   \"UF Destino:\"\r\n"
b"         Height          =   252\r\n"
b"         Left            =   120\r\n"
b"         TabIndex        =   18\r\n"
b"         Top             =   240\r\n"
b"         Width           =   960\r\n"
b"      End\r\n"
b"      Begin VB.TextBox txtUF \r\n"
b"         Height          =   288\r\n"
b"         Left            =   120\r\n"
b"         MaxLength       =   2\r\n"
b"         TabIndex        =   4\r\n"
b"         Top             =   480\r\n"
b"         Width           =   720\r\n"
b"      End\r\n"

# Row 1 - AliqInterna
b"      Begin VB.Label lblAliqInterna \r\n"
b"         Caption         =   \"Al\xedq. Interna (%):\"\r\n"
b"         Height          =   252\r\n"
b"         Left            =   960\r\n"
b"         TabIndex        =   19\r\n"
b"         Top             =   240\r\n"
b"         Width           =   1680\r\n"
b"      End\r\n"
b"      Begin VB.TextBox txtAliqInterna \r\n"
b"         Height          =   288\r\n"
b"         Left            =   960\r\n"
b"         TabIndex        =   5\r\n"
b"         Top             =   480\r\n"
b"         Width           =   1200\r\n"
b"      End\r\n"

# Row 1 - AliqFCP
b"      Begin VB.Label lblAliqFCP \r\n"
b"         Caption         =   \"Al\xedq. FCP (%):\"\r\n"
b"         Height          =   252\r\n"
b"         Left            =   2280\r\n"
b"         TabIndex        =   20\r\n"
b"         Top             =   240\r\n"
b"         Width           =   1080\r\n"
b"      End\r\n"
b"      Begin VB.TextBox txtAliqFCP \r\n"
b"         Height          =   288\r\n"
b"         Left            =   2280\r\n"
b"         TabIndex        =   6\r\n"
b"         Top             =   480\r\n"
b"         Width           =   1200\r\n"
b"      End\r\n"

# Row 1 - TipoCalculo
b"      Begin VB.Label lblTipoCalculo \r\n"
b"         Caption         =   \"Tipo de C\xe1lculo:\"\r\n"
b"         Height          =   252\r\n"
b"         Left            =   3600\r\n"
b"         TabIndex        =   21\r\n"
b"         Top             =   240\r\n"
b"         Width           =   1680\r\n"
b"      End\r\n"
b"      Begin VB.ComboBox cboTipoCalculo \r\n"
b"         Height          =   315\r\n"
b"         Left            =   3600\r\n"
b"         Style           =   2  'Dropdown List\r\n"
b"         TabIndex        =   7\r\n"
b"         Top             =   480\r\n"
b"         Width           =   3480\r\n"
b"      End\r\n"

# Row 1 - FCPCompoeBase
b"      Begin VB.CheckBox chkFCPCompoeBase \r\n"
b"         Caption         =   \"FCP Comp\xf5e Base\"\r\n"
b"         Height          =   288\r\n"
b"         Left            =   7320\r\n"
b"         TabIndex        =   8\r\n"
b"         Top             =   480\r\n"
b"         Width           =   2160\r\n"
b"      End\r\n"

# Row 2 - DtInicio
b"      Begin VB.Label lblDtInicio \r\n"
b"         Caption         =   \"In\xedcio de Vig\xeancia:\"\r\n"
b"         Height          =   252\r\n"
b"         Left            =   120\r\n"
b"         TabIndex        =   22\r\n"
b"         Top             =   900\r\n"
b"         Width           =   1800\r\n"
b"      End\r\n"
b"      Begin VB.TextBox txtDtInicio \r\n"
b"         Height          =   288\r\n"
b"         Left            =   120\r\n"
b"         MaxLength       =   10\r\n"
b"         TabIndex        =   9\r\n"
b"         Top             =   1140\r\n"
b"         Width           =   1680\r\n"
b"      End\r\n"

# Row 2 - DtFim
b"      Begin VB.Label lblDtFim \r\n"
b"         Caption         =   \"Fim de Vig\xeancia:\"\r\n"
b"         Height          =   252\r\n"
b"         Left            =   1920\r\n"
b"         TabIndex        =   23\r\n"
b"         Top             =   900\r\n"
b"         Width           =   1800\r\n"
b"      End\r\n"
b"      Begin VB.TextBox txtDtFim \r\n"
b"         Height          =   288\r\n"
b"         Left            =   1920\r\n"
b"         MaxLength       =   10\r\n"
b"         TabIndex        =   10\r\n"
b"         Top             =   1140\r\n"
b"         Width           =   1680\r\n"
b"      End\r\n"

# Row 2 - Observacao
b"      Begin VB.Label lblObs \r\n"
b"         Caption         =   \"Observa\xe7\xe3o:\"\r\n"
b"         Height          =   252\r\n"
b"         Left            =   3720\r\n"
b"         TabIndex        =   24\r\n"
b"         Top             =   900\r\n"
b"         Width           =   1200\r\n"
b"      End\r\n"
b"      Begin VB.TextBox txtObservacao \r\n"
b"         Height          =   288\r\n"
b"         Left            =   3720\r\n"
b"         MaxLength       =   255\r\n"
b"         TabIndex        =   11\r\n"
b"         Top             =   1140\r\n"
b"         Width           =   8040\r\n"
b"      End\r\n"

# Row 3 - Botoes
b"      Begin VB.CommandButton cmdNovo \r\n"
b"         Caption         =   \"Novo\"\r\n"
b"         Height          =   375\r\n"
b"         Left            =   120\r\n"
b"         TabIndex        =   12\r\n"
b"         Top             =   1680\r\n"
b"         Width           =   840\r\n"
b"      End\r\n"
b"      Begin VB.CommandButton cmdSalvar \r\n"
b"         Caption         =   \"Salvar\"\r\n"
b"         Height          =   375\r\n"
b"         Left            =   1080\r\n"
b"         TabIndex        =   13\r\n"
b"         Top             =   1680\r\n"
b"         Width           =   840\r\n"
b"      End\r\n"
b"      Begin VB.CommandButton cmdExcluir \r\n"
b"         Caption         =   \"Excluir\"\r\n"
b"         Height          =   375\r\n"
b"         Left            =   2040\r\n"
b"         TabIndex        =   14\r\n"
b"         Top             =   1680\r\n"
b"         Width           =   840\r\n"
b"      End\r\n"

b"   End\r\n"
b"End\r\n"

# ---------------------------------------------------------------------------
# Atributos e codigo VB
# ---------------------------------------------------------------------------
b"Attribute VB_Name = \"frmDIFAL_Cadastro\"\r\n"
b"Attribute VB_GlobalNameSpace = False\r\n"
b"Attribute VB_Creatable = False\r\n"
b"Attribute VB_PredeclaredId = True\r\n"
b"Attribute VB_Exposed = False\r\n"
b"Option Explicit\r\n"
b"\r\n"
b"Dim vID As Long\r\n"
b"Dim vTipo As String\r\n"
b"\r\n"

# Form_Load
b"Private Sub Form_Load()\r\n"
b"    vID = 0\r\n"
b"    vTipo = \"Novo\"\r\n"
b"    cboTipoCalculo.AddItem \"1 - Base \xdanica (Simples)\"\r\n"
b"    cboTipoCalculo.ItemData(0) = 1\r\n"
b"    cboTipoCalculo.AddItem \"2 - Base Dupla (Por Dentro)\"\r\n"
b"    cboTipoCalculo.ItemData(1) = 2\r\n"
b"    cboTipoCalculo.ListIndex = 1\r\n"
b"    CarregarGrid\r\n"
b"End Sub\r\n"
b"\r\n"

# CarregarGrid
b"Private Sub CarregarGrid()\r\n"
b"    Dim rs As ADODB.Recordset\r\n"
b"    Dim sSQL As String, sWhere As String\r\n"
b"    Dim lRow As Long\r\n"
b"\r\n"
b"    sWhere = \" WHERE 1=1\"\r\n"
b"    If Trim(txtFiltroUF.Text) <> \"\" Then\r\n"
b"        sWhere = sWhere & \" AND UF_Destino LIKE '%\" & Replace(UCase(Trim(txtFiltroUF.Text)), \"'\", \"''\") & \"%'\"\r\n"
b"    End If\r\n"
b"\r\n"
b"    sSQL = \"SELECT ID, UF_Destino, AliquotaInterna, AliquotaFCP, \" & _\r\n"
b"           \"DataInicioVigencia, DataFimVigencia, TipoCalculo, FCPCompoeBase, Observacao \" & _\r\n"
b"           \"FROM TribRegraDifalUF\" & sWhere & \" ORDER BY UF_Destino, DataInicioVigencia\"\r\n"
b"\r\n"
b"    RsOpen rs, sSQL\r\n"
b"\r\n"
b"    With lstDIFAL\r\n"
b"        .Redraw = False\r\n"
b"        .Clear\r\n"
b"        .Cols = 9\r\n"
b"        .Rows = 2\r\n"
b"        .ColWidth(0) = 0\r\n"
b"        .ColWidth(1) = 600\r\n"
b"        .ColWidth(2) = 1800\r\n"
b"        .ColWidth(3) = 1500\r\n"
b"        .ColWidth(4) = 2100\r\n"
b"        .ColWidth(5) = 2100\r\n"
b"        .ColWidth(6) = 2700\r\n"
b"        .ColWidth(7) = 1800\r\n"
b"        .ColWidth(8) = 1560\r\n"
b"        .FixedRows = 1\r\n"
b"        .FixedCols = 0\r\n"
b"        .TextMatrix(0, 1) = \"UF\"\r\n"
b"        .TextMatrix(0, 2) = \"Al\xedq. Interna %\"\r\n"
b"        .TextMatrix(0, 3) = \"Al\xedq. FCP %\"\r\n"
b"        .TextMatrix(0, 4) = \"In\xedcio Vig\xeancia\"\r\n"
b"        .TextMatrix(0, 5) = \"Fim Vig\xeancia\"\r\n"
b"        .TextMatrix(0, 6) = \"Tipo C\xe1lculo\"\r\n"
b"        .TextMatrix(0, 7) = \"FCP Comp\xf5e Base\"\r\n"
b"        .TextMatrix(0, 8) = \"Observa\xe7\xe3o\"\r\n"
b"        .Row = 0\r\n"
b"        .Col = 0\r\n"
b"        .ColSel = .Cols - 1\r\n"
b"        lRow = 1\r\n"
b"        Do While Not rs.EOF\r\n"
b"            .Rows = lRow + 1\r\n"
b"            .TextMatrix(lRow, 0) = rs(\"ID\")\r\n"
b"            .TextMatrix(lRow, 1) = Trim(rs(\"UF_Destino\"))\r\n"
b"            .TextMatrix(lRow, 2) = Format(rs(\"AliquotaInterna\"), \"0.00\")\r\n"
b"            .TextMatrix(lRow, 3) = Format(rs(\"AliquotaFCP\"), \"0.00\")\r\n"
b"            .TextMatrix(lRow, 4) = Format(rs(\"DataInicioVigencia\"), \"dd/mm/yyyy\")\r\n"
b"            If IsNull(rs(\"DataFimVigencia\")) Then\r\n"
b"                .TextMatrix(lRow, 5) = \"\"\r\n"
b"            Else\r\n"
b"                .TextMatrix(lRow, 5) = Format(rs(\"DataFimVigencia\"), \"dd/mm/yyyy\")\r\n"
b"            End If\r\n"
b"            .TextMatrix(lRow, 6) = IIf(rs(\"TipoCalculo\") = 1, \"1 - Base \xdanica\", \"2 - Base Dupla\")\r\n"
b"            .TextMatrix(lRow, 7) = IIf(rs(\"FCPCompoeBase\") = True, \"Sim\", \"N\xe3o\")\r\n"
b"            .TextMatrix(lRow, 8) = IIf(IsNull(rs(\"Observacao\")), \"\", rs(\"Observacao\"))\r\n"
b"            lRow = lRow + 1\r\n"
b"            rs.MoveNext\r\n"
b"        Loop\r\n"
b"        .Redraw = True\r\n"
b"    End With\r\n"
b"\r\n"
b"    rs.Close\r\n"
b"    Set rs = Nothing\r\n"
b"    LimparCampos\r\n"
b"End Sub\r\n"
b"\r\n"

# lstDIFAL_Click
b"Private Sub lstDIFAL_Click()\r\n"
b"    If lstDIFAL.Row = 0 Then Exit Sub\r\n"
b"    If Trim(lstDIFAL.TextMatrix(lstDIFAL.Row, 0)) = \"\" Then Exit Sub\r\n"
b"    vID = CLng(lstDIFAL.TextMatrix(lstDIFAL.Row, 0))\r\n"
b"    vTipo = \"Edicao\"\r\n"
b"    txtUF.Text = lstDIFAL.TextMatrix(lstDIFAL.Row, 1)\r\n"
b"    txtAliqInterna.Text = lstDIFAL.TextMatrix(lstDIFAL.Row, 2)\r\n"
b"    txtAliqFCP.Text = lstDIFAL.TextMatrix(lstDIFAL.Row, 3)\r\n"
b"    txtDtInicio.Text = lstDIFAL.TextMatrix(lstDIFAL.Row, 4)\r\n"
b"    txtDtFim.Text = lstDIFAL.TextMatrix(lstDIFAL.Row, 5)\r\n"
b"    If Left(lstDIFAL.TextMatrix(lstDIFAL.Row, 6), 1) = \"1\" Then\r\n"
b"        cboTipoCalculo.ListIndex = 0\r\n"
b"    Else\r\n"
b"        cboTipoCalculo.ListIndex = 1\r\n"
b"    End If\r\n"
b"    chkFCPCompoeBase.Value = IIf(lstDIFAL.TextMatrix(lstDIFAL.Row, 7) = \"Sim\", 1, 0)\r\n"
b"    txtObservacao.Text = lstDIFAL.TextMatrix(lstDIFAL.Row, 8)\r\n"
b"End Sub\r\n"
b"\r\n"

# cmdNovo_Click
b"Private Sub cmdNovo_Click()\r\n"
b"    LimparCampos\r\n"
b"    txtUF.SetFocus\r\n"
b"End Sub\r\n"
b"\r\n"

# cmdSalvar_Click
b"Private Sub cmdSalvar_Click()\r\n"
b"    Dim sUF As String\r\n"
b"    Dim dAliqInt As Double, dAliqFCP As Double\r\n"
b"    Dim sDtInicio As String, sDtFim As String\r\n"
b"    Dim iTipoCalc As Integer, bFCPBase As Integer\r\n"
b"    Dim sObs As String, sSQL As String\r\n"
b"    Dim sAliqInt As String, sAliqFCP As String\r\n"
b"\r\n"
b"    sUF = UCase(Trim(txtUF.Text))\r\n"
b"    If Len(sUF) <> 2 Then\r\n"
b"        MsgBox \"Informe a UF com 2 caracteres!\", vbExclamation, \"Aviso\": Exit Sub\r\n"
b"    End If\r\n"
b"\r\n"
b"    If Not IsNumeric(Replace(Trim(txtAliqInterna.Text), \",\", \".\")) Then\r\n"
b"        MsgBox \"Al\xedquota Interna inv\xe1lida!\", vbExclamation, \"Aviso\": Exit Sub\r\n"
b"    End If\r\n"
b"    dAliqInt = CDbl(Replace(Trim(txtAliqInterna.Text), \",\", \".\"))\r\n"
b"\r\n"
b"    If Not IsNumeric(Replace(Trim(txtAliqFCP.Text), \",\", \".\")) Then\r\n"
b"        MsgBox \"Al\xedquota FCP inv\xe1lida!\", vbExclamation, \"Aviso\": Exit Sub\r\n"
b"    End If\r\n"
b"    dAliqFCP = CDbl(Replace(Trim(txtAliqFCP.Text), \",\", \".\"))\r\n"
b"\r\n"
b"    If Trim(txtDtInicio.Text) = \"\" Then\r\n"
b"        MsgBox \"Informe a data de in\xedcio de vig\xeancia!\", vbExclamation, \"Aviso\": Exit Sub\r\n"
b"    End If\r\n"
b"    If Not IsDate(txtDtInicio.Text) Then\r\n"
b"        MsgBox \"Data de in\xedcio inv\xe1lida! Use dd/mm/aaaa\", vbExclamation, \"Aviso\": Exit Sub\r\n"
b"    End If\r\n"
b"    sDtInicio = Format(CDate(txtDtInicio.Text), \"yyyy-mm-dd\")\r\n"
b"\r\n"
b"    sDtFim = \"\"\r\n"
b"    If Trim(txtDtFim.Text) <> \"\" Then\r\n"
b"        If Not IsDate(txtDtFim.Text) Then\r\n"
b"            MsgBox \"Data de fim inv\xe1lida! Use dd/mm/aaaa\", vbExclamation, \"Aviso\": Exit Sub\r\n"
b"        End If\r\n"
b"        sDtFim = Format(CDate(txtDtFim.Text), \"yyyy-mm-dd\")\r\n"
b"    End If\r\n"
b"\r\n"
b"    iTipoCalc = cboTipoCalculo.ItemData(cboTipoCalculo.ListIndex)\r\n"
b"    bFCPBase = chkFCPCompoeBase.Value\r\n"
b"    sObs = Replace(Trim(txtObservacao.Text), \"'\", \"''\")\r\n"
b"    sAliqInt = Replace(CStr(dAliqInt), \",\", \".\")\r\n"
b"    sAliqFCP = Replace(CStr(dAliqFCP), \",\", \".\")\r\n"
b"\r\n"
b"    If vTipo = \"Novo\" Then\r\n"
b"        sSQL = \"INSERT INTO TribRegraDifalUF \" & _\r\n"
b"               \"(UF_Destino, AliquotaInterna, AliquotaFCP, DataInicioVigencia, \" & _\r\n"
b"               \"DataFimVigencia, TipoCalculo, FCPCompoeBase, Observacao) VALUES ('\" & _\r\n"
b"               sUF & \"', \" & sAliqInt & \", \" & sAliqFCP & \", '\" & sDtInicio & \"', \" & _\r\n"
b"               IIf(sDtFim = \"\", \"NULL\", \"'\" & sDtFim & \"'\") & \", \" & iTipoCalc & \", \" & _\r\n"
b"               bFCPBase & \", \" & IIf(Len(sObs) = 0, \"NULL\", \"'\" & sObs & \"'\") & \")\"\r\n"
b"    Else\r\n"
b"        sSQL = \"UPDATE TribRegraDifalUF SET \" & _\r\n"
b"               \"UF_Destino='\" & sUF & \"', \" & _\r\n"
b"               \"AliquotaInterna=\" & sAliqInt & \", \" & _\r\n"
b"               \"AliquotaFCP=\" & sAliqFCP & \", \" & _\r\n"
b"               \"DataInicioVigencia='\" & sDtInicio & \"', \" & _\r\n"
b"               \"DataFimVigencia=\" & IIf(sDtFim = \"\", \"NULL\", \"'\" & sDtFim & \"'\") & \", \" & _\r\n"
b"               \"TipoCalculo=\" & iTipoCalc & \", \" & _\r\n"
b"               \"FCPCompoeBase=\" & bFCPBase & \", \" & _\r\n"
b"               \"Observacao=\" & IIf(Len(sObs) = 0, \"NULL\", \"'\" & sObs & \"'\") & _\r\n"
b"               \" WHERE ID=\" & vID\r\n"
b"    End If\r\n"
b"\r\n"
b"    On Error GoTo errSalvar\r\n"
b"    dbData.Execute sSQL\r\n"
b"    MsgBox \"Registro salvo com sucesso!\", vbInformation, \"Sucesso\"\r\n"
b"    CarregarGrid\r\n"
b"    Exit Sub\r\n"
b"errSalvar:\r\n"
b"    MsgBox \"Erro ao salvar: \" & Err.Description, vbCritical, \"Erro\"\r\n"
b"End Sub\r\n"
b"\r\n"

# cmdExcluir_Click
b"Private Sub cmdExcluir_Click()\r\n"
b"    If vID = 0 Then\r\n"
b"        MsgBox \"Selecione um registro no grid para excluir!\", vbExclamation, \"Aviso\": Exit Sub\r\n"
b"    End If\r\n"
b"    If MsgBox(\"Confirma a exclus\xe3o da UF '\" & txtUF.Text & \"'?\", _\r\n"
b"              vbQuestion + vbYesNo, \"Confirmar\") = vbNo Then Exit Sub\r\n"
b"    On Error GoTo errExcluir\r\n"
b"    dbData.Execute \"DELETE FROM TribRegraDifalUF WHERE ID=\" & vID\r\n"
b"    MsgBox \"Registro exclu\xeddo!\", vbInformation, \"Sucesso\"\r\n"
b"    CarregarGrid\r\n"
b"    Exit Sub\r\n"
b"errExcluir:\r\n"
b"    MsgBox \"Erro ao excluir: \" & Err.Description, vbCritical, \"Erro\"\r\n"
b"End Sub\r\n"
b"\r\n"

# cmdLocalizar / cmdLimpar
b"Private Sub cmdLocalizar_Click()\r\n"
b"    CarregarGrid\r\n"
b"End Sub\r\n"
b"\r\n"
b"Private Sub cmdLimpar_Click()\r\n"
b"    txtFiltroUF.Text = \"\"\r\n"
b"    CarregarGrid\r\n"
b"End Sub\r\n"
b"\r\n"

# LimparCampos
b"Private Sub LimparCampos()\r\n"
b"    vID = 0\r\n"
b"    vTipo = \"Novo\"\r\n"
b"    txtUF.Text = \"\"\r\n"
b"    txtAliqInterna.Text = \"\"\r\n"
b"    txtAliqFCP.Text = \"\"\r\n"
b"    txtDtInicio.Text = \"\"\r\n"
b"    txtDtFim.Text = \"\"\r\n"
b"    cboTipoCalculo.ListIndex = 1\r\n"
b"    chkFCPCompoeBase.Value = 1\r\n"
b"    txtObservacao.Text = \"\"\r\n"
b"End Sub\r\n"
)

# ---------------------------------------------------------------------------
# Salvar .frm
# ---------------------------------------------------------------------------
FRM_FINAL = norm(FRM_CONTENT)
with open(FRM, "wb") as f:
    f.write(FRM_FINAL)
print(f"OK: {FRM} criado ({len(FRM_FINAL)} bytes)")

# ---------------------------------------------------------------------------
# Atualizar VBP — inserir antes da linha IconForm=
# ---------------------------------------------------------------------------
shutil.copy2(VBP, VBP_BAK)
print(f"Backup VBP: {VBP_BAK}")

with open(VBP, "rb") as f:
    vbp = f.read()

NEW_FORM_LINE = b"Form=Forms\\frmDIFAL_Cadastro.frm\r\n"
if NEW_FORM_LINE in vbp:
    print("VBP: linha ja existe, nada a fazer.")
else:
    ANCHOR = b"IconForm="
    idx = vbp.find(ANCHOR)
    if idx == -1:
        print("ERRO: nao encontrou 'IconForm=' no VBP.")
        sys.exit(1)
    vbp = vbp[:idx] + NEW_FORM_LINE + vbp[idx:]
    with open(VBP, "wb") as f:
        f.write(vbp)
    print("OK: VBP atualizado com Form=Forms\\frmDIFAL_Cadastro.frm")

print("\nConcluido!")
