# -*- coding: utf-8 -*-
"""
Cria o novo form OrdemServico\\Forms\\frmHistoricoOleo.frm (historico de
trocas de oleo por placa) clonado de frmBuscarPlaca.frm.
Busca por txtPlacaF todas as OS daquela placa que tenham, em
pedidos_itens/produtos, algum produto vendido com 'OLEO' ou '\xd3LEO' na
descricao. Grid: COD.OS | DATA | CLIENTE | VEICULO | PLACA | KM | OLEO
(VEICULO = FABRICANTE/MODELO/ANO, vindo de OS_Equipamento_Auto).
"""

PATH = r"C:\projeto\OrdemServico\Forms\frmHistoricoOleo.frm"

OLEO_ACC = "\xd3LEO"  # OLEO acentuado (cp1252)

design = [
    "VERSION 5.00",
    'Object = "{5E9E78A0-531B-11CF-91F6-C2863C385E30}#1.0#0"; "msflxgrd.ocx"',
    "Begin VB.Form frmHistoricoOleo ",
    "   BorderStyle     =   3  'Fixed Dialog",
    '   Caption         =   "Hist\xf3rico de Trocas de \xd3leo por Placa"',
    "   ClientHeight    =   4560",
    "   ClientLeft      =   120",
    "   ClientTop       =   465",
    "   ClientWidth     =   9840",
    "   LinkTopic       =   \"Form1\"",
    "   ScaleHeight     =   4560",
    "   ScaleWidth      =   9840",
    "   StartUpPosition =   2  'CenterScreen",
    "   Begin VB.CommandButton cmdFechar ",
    '      Caption         =   "Fechar"',
    "      Height          =   450",
    "      Left            =   7380",
    "      TabIndex        =   3",
    "      Top             =   4020",
    "      Width           =   2400",
    "   End",
    "   Begin MSFlexGridLib.MSFlexGrid lstOleo ",
    "      Height          =   3300",
    "      Left            =   60",
    "      TabIndex        =   2",
    "      Top             =   600",
    "      Width           =   9700",
    "      _ExtentX        =   17118",
    "      _ExtentY        =   5821",
    "      _Version        =   393216",
    "      Appearance      =   0",
    "   End",
    "   Begin VB.CommandButton cmdFiltrar ",
    '      Caption         =   "Buscar"',
    "      Height          =   375",
    "      Left            =   2520",
    "      TabIndex        =   1",
    "      Top             =   120",
    "      Width           =   1200",
    "   End",
    "   Begin VB.TextBox txtPlacaF ",
    "      Height          =   315",
    "      Left            =   600",
    "      TabIndex        =   0",
    "      Top             =   150",
    "      Width           =   1800",
    "   End",
    "   Begin VB.Frame fraCarregando ",
    "      BackColor       =   &H00FFFFFF&",
    "      BorderStyle     =   1  'Fixed Single",
    '      Caption         =   ""',
    "      Height          =   600",
    "      Left            =   3500",
    "      TabIndex        =   5",
    "      Top             =   1900",
    "      Visible         =   0   'False",
    "      Width           =   2800",
    "      Begin VB.Label lblCarregando ",
    "         Alignment       =   2  'Center",
    "         BackStyle       =   0  'Transparent",
    '         Caption         =   "Carregando..."',
    "         BeginProperty Font ",
    '            Name            =   "MS Sans Serif"',
    "            Size            =   14",
    "            Charset         =   0",
    "            Weight          =   700",
    "            Underline       =   0   'False",
    "            Italic          =   0   'False",
    "            Strikethrough   =   0   'False",
    "         EndProperty",
    "         Height          =   420",
    "         Left            =   60",
    "         TabIndex        =   0",
    "         Top             =   90",
    "         Width           =   2680",
    "      End",
    "   End",
    "   Begin VB.Timer tmrCarregando ",
    "      Enabled         =   0   'False",
    "      Interval        =   400",
    "      Left            =   120",
    "      Top             =   4200",
    "   End",
    "   Begin VB.Label lblPlacaF ",
    '      Caption         =   "Placa:"',
    "      Height          =   195",
    "      Left            =   60",
    "      TabIndex        =   4",
    "      Top             =   180",
    "      Width           =   480",
    "   End",
    "End",
    'Attribute VB_Name = "frmHistoricoOleo"',
    "Attribute VB_GlobalNameSpace = False",
    "Attribute VB_Creatable = False",
    "Attribute VB_PredeclaredId = True",
    "Attribute VB_Exposed = False",
]

code = [
    "Option Explicit",
    "",
    "Private iDots As Integer",
    "",
    "Private Sub Form_Load()",
    "    iDots = 0",
    "    fraCarregando.Visible = False",
    "    ConfigurarGrid",
    "End Sub",
    "",
    "Private Sub Form_Activate()",
    "    txtPlacaF.SetFocus",
    "End Sub",
    "",
    "Private Sub Form_QueryUnload(Cancel As Integer, UnloadMode As Integer)",
    "    If UnloadMode = vbFormControlMenu Then",
    "        Cancel = 1",
    "        Me.Hide",
    "    End If",
    "End Sub",
    "",
    "Private Sub ConfigurarGrid()",
    "    With lstOleo",
    "        .Cols = 7",
    "        .Rows = 1",
    "        .ColWidth(0) = 700",
    "        .ColWidth(1) = 1000",
    "        .ColWidth(2) = 2100",
    "        .ColWidth(3) = 2100",
    "        .ColWidth(4) = 900",
    "        .ColWidth(5) = 800",
    "        .ColWidth(6) = 2100",
    '        .Row = 0: .Col = 0: .Text = "COD.OS"',
    '        .Row = 0: .Col = 1: .Text = "DATA"',
    '        .Row = 0: .Col = 2: .Text = "CLIENTE"',
    '        .Row = 0: .Col = 3: .Text = "VEICULO"',
    '        .Row = 0: .Col = 4: .Text = "PLACA": .CellBackColor = &HE0E0E0',
    '        .Row = 0: .Col = 5: .Text = "KM"',
    '        .Row = 0: .Col = 6: .Text = "OLEO"',
    "        .AllowUserResizing = 1",
    "        .SelectionMode = 1",
    "    End With",
    "End Sub",
    "",
    "Private Sub CarregarGrid()",
    "    Dim rOleo As ADODB.Recordset",
    "    Dim sql As String",
    "    Dim n As Integer",
    "    Dim sVeiculo As String",
    "",
    '    If Trim(txtPlacaF.Text) = "" Then',
    '        MsgBox "Digite a placa para consultar!", vbInformation, "Aviso do Sistema"',
    "        Exit Sub",
    "    End If",
    "",
    "    fraCarregando.Visible = True",
    "    fraCarregando.ZOrder 0",
    "    tmrCarregando.Enabled = True",
    "    Me.Refresh",
    "    DoEvents",
    "",
    "    lstOleo.Rows = 1",
    "",
    '    sql = "SELECT OS.COD_OS, OS.DATA_ENTRADA, cliente.nome, " & _',
    '          "OS_Equipamento_Auto.fabricante, OS_Equipamento_Auto.modelo, OS_Equipamento_Auto.ano, " & _',
    '          "OS_Equipamento_Auto.placa, OS_Equipamento_Auto.km, produtos.descricao AS var_oleo " & _',
    '          "FROM cliente INNER JOIN OS ON cliente.CODIGO = OS.COD_CLIENTE " & _',
    '          "INNER JOIN OS_Equipamento_Auto ON OS.COD_OS = OS_Equipamento_Auto.COD_OS " & _',
    '          "INNER JOIN pedidos_itens ON pedidos_itens.COD_PEDIDO = OS.COD_PEDIDO " & _',
    '          "INNER JOIN produtos ON produtos.CODIGO = pedidos_itens.COD_PRODUTO " & _',
    '          "WHERE (OS_Equipamento_Auto.placa LIKE \'%" & Replace(Trim(txtPlacaF.Text), "\'", "\'\'") & "%\') " & _',
    '          "AND (produtos.descricao LIKE \'%OLEO%\' OR produtos.descricao LIKE \'%' + OLEO_ACC + '%\') " & _',
    '          "ORDER BY OS.DATA_ENTRADA DESC"',
    "",
    "    RsOpen rOleo, sql",
    "    n = 1",
    "    Do While Not rOleo.EOF",
    '        sVeiculo = Trim(ValidateNull(rOleo("fabricante")) & "/" & ValidateNull(rOleo("modelo")) & "/" & ValidateNull(rOleo("ano")))',
    "        With lstOleo",
    "            .Rows = n + 1",
    '            .Row = n: .Col = 0: .Text = ValidateNull(rOleo("COD_OS"))',
    '            .Row = n: .Col = 1: .Text = Format(rOleo("DATA_ENTRADA"), "dd/mm/yyyy")',
    '            .Row = n: .Col = 2: .Text = ValidateNull(rOleo("nome"))',
    "            .Row = n: .Col = 3: .Text = sVeiculo",
    '            .Row = n: .Col = 4: .Text = ValidateNull(rOleo("placa"))',
    '            .Row = n: .Col = 5: .Text = ValidateNull(rOleo("km"))',
    '            .Row = n: .Col = 6: .Text = ValidateNull(rOleo("var_oleo"))',
    "        End With",
    "        n = n + 1",
    "        rOleo.MoveNext",
    "    Loop",
    "    If rOleo.State <> 0 Then rOleo.Close",
    "",
    "    tmrCarregando.Enabled = False",
    "    fraCarregando.Visible = False",
    "",
    "    If lstOleo.Rows = 1 Then",
    '        MsgBox "Nenhuma troca de \xf3leo encontrada para essa placa!", vbInformation, "Aviso do Sistema"',
    "    End If",
    "End Sub",
    "",
    "Private Sub txtPlacaF_KeyPress(KeyAscii As Integer)",
    "    If KeyAscii = 13 Then",
    "        KeyAscii = 0",
    "        CarregarGrid",
    "    End If",
    "    KeyAscii = Asc(UCase(Chr(KeyAscii)))",
    "End Sub",
    "",
    "Private Sub cmdFiltrar_Click()",
    "    CarregarGrid",
    "End Sub",
    "",
    "Private Sub cmdFechar_Click()",
    "    Me.Hide",
    "End Sub",
    "",
    "Private Sub tmrCarregando_Timer()",
    "    iDots = (iDots Mod 3) + 1",
    '    lblCarregando.Caption = "Carregando" & String(iDots, ".")',
    "End Sub",
    "",
]

all_lines = design + code
text = "\r\n".join(all_lines)
text = text.replace("\r\n", "\n").replace("\r", "\n").replace("\n", "\r\n")

with open(PATH, "wb") as f:
    f.write(text.encode("cp1252"))

print(f"OK - {PATH} criado, {len(all_lines)} linhas")
