"""
Gera C:\Projeto\Compartilhado\Forms\frmBuscarNCM.frm
- OptionButtons exclusivos para tipo de busca de texto
- Ao trocar opcao, limpa os outros campos de texto
- Busca por texto desvincula os filtros de combo
- Coluna NCM (col 3) em cinza claro
- Categorias sem repeticao (DISTINCT)
- Tags: primeira opcao = TODOS
"""
FILE = r"C:\Projeto\Compartilhado\Forms\frmBuscarNCM.frm"

frm = (
    b"VERSION 5.00\r\n"
    b"Object = \"{5E9E78A0-531B-11CF-91F6-C2863C385E30}#1.0#0\"; \"msflxgrd.ocx\"\r\n"
    b"Begin VB.Form frmBuscarNCM \r\n"
    b"   BorderStyle     =   3  'Fixed Dialog\r\n"
    b"   Caption         =   \"Buscar NCM\"\r\n"
    b"   ClientHeight    =   7005\r\n"
    b"   ClientLeft      =   120\r\n"
    b"   ClientTop       =   465\r\n"
    b"   ClientWidth     =   10980\r\n"
    b"   LinkTopic       =   \"Form1\"\r\n"
    b"   ScaleHeight     =   7005\r\n"
    b"   ScaleWidth      =   10980\r\n"
    b"   StartUpPosition =   2  'CenterScreen\r\n"
    # --- Botoes de acao ---
    b"   Begin VB.CommandButton cmdFechar \r\n"
    b"      Caption         =   \"Fechar\"\r\n"
    b"      Height          =   450\r\n"
    b"      Left            =   8460\r\n"
    b"      TabIndex        =   6\r\n"
    b"      Top             =   6480\r\n"
    b"      Width           =   2400\r\n"
    b"   End\r\n"
    b"   Begin VB.CommandButton cmdUsarNCM \r\n"
    b"      Caption         =   \"Usar NCM\"\r\n"
    b"      Height          =   450\r\n"
    b"      Left            =   120\r\n"
    b"      TabIndex        =   5\r\n"
    b"      Top             =   6480\r\n"
    b"      Width           =   2400\r\n"
    b"   End\r\n"
    # --- Grid ---
    b"   Begin MSFlexGridLib.MSFlexGrid lstProdutos \r\n"
    b"      Height          =   5340\r\n"
    b"      Left            =   120\r\n"
    b"      TabIndex        =   4\r\n"
    b"      Top             =   1080\r\n"
    b"      Width           =   10740\r\n"
    b"      _ExtentX        =   18944\r\n"
    b"      _ExtentY        =   9419\r\n"
    b"      _Version        =   393216\r\n"
    b"   End\r\n"
    # --- Frame com OptionButtons e campos de texto ---
    b"   Begin VB.Frame fraFiltro \r\n"
    b"      Caption         =   \"\"\r\n"
    b"      Height          =   510\r\n"
    b"      Left            =   120\r\n"
    b"      TabIndex        =   3\r\n"
    b"      Top             =   510\r\n"
    b"      Width           =   10740\r\n"
    b"      Begin VB.TextBox txtNCMF \r\n"
    b"         Height          =   315\r\n"
    b"         Left            =   9480\r\n"
    b"         TabIndex        =   5\r\n"
    b"         Top             =   90\r\n"
    b"         Width           =   1140\r\n"
    b"      End\r\n"
    b"      Begin VB.OptionButton optNCM \r\n"
    b"         Caption         =   \"NCM\"\r\n"
    b"         Height          =   315\r\n"
    b"         Left            =   8700\r\n"
    b"         TabIndex        =   4\r\n"
    b"         Top             =   90\r\n"
    b"         Width           =   720\r\n"
    b"      End\r\n"
    b"      Begin VB.TextBox txtDescF \r\n"
    b"         Height          =   315\r\n"
    b"         Left            =   5220\r\n"
    b"         TabIndex        =   3\r\n"
    b"         Top             =   90\r\n"
    b"         Width           =   3360\r\n"
    b"      End\r\n"
    b"      Begin VB.OptionButton optDesc \r\n"
    b"         Caption         =   \"Descri\xe7\xe3o\"\r\n"
    b"         Height          =   315\r\n"
    b"         Left            =   3900\r\n"
    b"         TabIndex        =   2\r\n"
    b"         Top             =   90\r\n"
    b"         Width           =   1260\r\n"
    b"      End\r\n"
    b"      Begin VB.TextBox txtCodBarraF \r\n"
    b"         Height          =   315\r\n"
    b"         Left            =   1500\r\n"
    b"         TabIndex        =   1\r\n"
    b"         Top             =   90\r\n"
    b"         Width           =   2280\r\n"
    b"      End\r\n"
    b"      Begin VB.OptionButton optCodBarra \r\n"
    b"         Caption         =   \"C\xf3d. Barra\"\r\n"
    b"         Height          =   315\r\n"
    b"         Left            =   60\r\n"
    b"         TabIndex        =   0\r\n"
    b"         Top             =   90\r\n"
    b"         Width           =   1380\r\n"
    b"      End\r\n"
    b"   End\r\n"
    # --- Linha 1: Combos e Buscar ---
    b"   Begin VB.CommandButton cmdFiltrar \r\n"
    b"      Caption         =   \"Buscar\"\r\n"
    b"      Height          =   375\r\n"
    b"      Left            =   9480\r\n"
    b"      TabIndex        =   2\r\n"
    b"      Top             =   120\r\n"
    b"      Width           =   1380\r\n"
    b"   End\r\n"
    b"   Begin VB.ComboBox cboTagsF \r\n"
    b"      Height          =   315\r\n"
    b"      Left            =   6360\r\n"
    b"      Style           =   2  'Dropdown List\r\n"
    b"      TabIndex        =   1\r\n"
    b"      Top             =   120\r\n"
    b"      Width           =   2940\r\n"
    b"   End\r\n"
    b"   Begin VB.ComboBox cboCategoriaF \r\n"
    b"      Height          =   315\r\n"
    b"      Left            =   1080\r\n"
    b"      Style           =   2  'Dropdown List\r\n"
    b"      TabIndex        =   0\r\n"
    b"      Top             =   120\r\n"
    b"      Width           =   4200\r\n"
    b"   End\r\n"
    b"   Begin VB.Label lblTagsF \r\n"
    b"      AutoSize        =   -1  'True\r\n"
    b"      Caption         =   \"Tags:\"\r\n"
    b"      Height          =   195\r\n"
    b"      Left            =   5760\r\n"
    b"      TabIndex        =   9\r\n"
    b"      Top             =   126\r\n"
    b"      Width           =   480\r\n"
    b"   End\r\n"
    b"   Begin VB.Label lblCategoriaF \r\n"
    b"      AutoSize        =   -1  'True\r\n"
    b"      Caption         =   \"Categoria:\"\r\n"
    b"      Height          =   195\r\n"
    b"      Left            =   120\r\n"
    b"      TabIndex        =   8\r\n"
    b"      Top             =   126\r\n"
    b"      Width           =   840\r\n"
    b"   End\r\n"
    b"End\r\n"
    # ===================== CODIGO =====================
    b"Attribute VB_Name = \"frmBuscarNCM\"\r\n"
    b"Attribute VB_GlobalNameSpace = False\r\n"
    b"Attribute VB_Creatable = False\r\n"
    b"Attribute VB_PredeclaredId = True\r\n"
    b"Attribute VB_Exposed = False\r\n"
    b"Public sNCMSelecionado As String\r\n"
    b"Public sCatInicial As String\r\n"
    b"Public sTagInicial As String\r\n"
    b"\r\n"
    b"Private Sub Form_Load()\r\n"
    b"    Dim i As Integer\r\n"
    b"    sNCMSelecionado = \"\"\r\n"
    b"    optDesc.Value = True\r\n"
    b"    CarregarCategorias\r\n"
    b"    If sCatInicial <> \"\" Then\r\n"
    b"        For i = 0 To cboCategoriaF.ListCount - 1\r\n"
    b"            If cboCategoriaF.List(i) = sCatInicial Then\r\n"
    b"                cboCategoriaF.ListIndex = i: Exit For\r\n"
    b"            End If\r\n"
    b"        Next i\r\n"
    b"        CarregarTags\r\n"
    b"        If sTagInicial <> \"\" Then\r\n"
    b"            For i = 0 To cboTagsF.ListCount - 1\r\n"
    b"                If cboTagsF.List(i) = sTagInicial Then\r\n"
    b"                    cboTagsF.ListIndex = i: Exit For\r\n"
    b"                End If\r\n"
    b"            Next i\r\n"
    b"        End If\r\n"
    b"    End If\r\n"
    b"    CarregarGrid\r\n"
    b"End Sub\r\n"
    b"\r\n"
    b"Private Sub Form_QueryUnload(Cancel As Integer, UnloadMode As Integer)\r\n"
    b"    If UnloadMode = vbFormControlMenu Then\r\n"
    b"        Cancel = 1\r\n"
    b"        sNCMSelecionado = \"\"\r\n"
    b"        Me.Hide\r\n"
    b"    End If\r\n"
    b"End Sub\r\n"
    b"\r\n"
    b"' --- Opcoes de pesquisa ---\r\n"
    b"Private Sub optCodBarra_Click()\r\n"
    b"    txtDescF.Text = \"\"\r\n"
    b"    txtNCMF.Text = \"\"\r\n"
    b"End Sub\r\n"
    b"\r\n"
    b"Private Sub optDesc_Click()\r\n"
    b"    txtCodBarraF.Text = \"\"\r\n"
    b"    txtNCMF.Text = \"\"\r\n"
    b"End Sub\r\n"
    b"\r\n"
    b"Private Sub optNCM_Click()\r\n"
    b"    txtCodBarraF.Text = \"\"\r\n"
    b"    txtDescF.Text = \"\"\r\n"
    b"End Sub\r\n"
    b"\r\n"
    b"' --- Carga de dados ---\r\n"
    b"Private Sub CarregarCategorias()\r\n"
    b"    Dim rCat As ADODB.Recordset\r\n"
    b"    cboCategoriaF.Clear\r\n"
    b"    cboCategoriaF.AddItem \"\"\r\n"
    b"    RsOpen rCat, \"SELECT DISTINCT Categoria FROM Categorias ORDER BY Categoria\"\r\n"
    b"    Do While Not rCat.EOF\r\n"
    b"        cboCategoriaF.AddItem Trim(rCat(\"Categoria\"))\r\n"
    b"        rCat.MoveNext\r\n"
    b"    Loop\r\n"
    b"    If rCat.State <> 0 Then rCat.Close\r\n"
    b"End Sub\r\n"
    b"\r\n"
    b"Private Sub CarregarTags()\r\n"
    b"    Dim rTags As ADODB.Recordset\r\n"
    b"    cboTagsF.Clear\r\n"
    b"    cboTagsF.AddItem \"TODOS\"\r\n"
    b"    If cboCategoriaF.Text = \"\" Then Exit Sub\r\n"
    b"    RsOpen rTags, \"SELECT DISTINCT TAGS FROM produtos WHERE TAGS IS NOT NULL AND TAGS <> '' AND categoria = '\" & Replace(cboCategoriaF.Text, \"'\", \"''\") & \"' ORDER BY TAGS\"\r\n"
    b"    Do While Not rTags.EOF\r\n"
    b"        cboTagsF.AddItem Trim(rTags(\"TAGS\"))\r\n"
    b"        rTags.MoveNext\r\n"
    b"    Loop\r\n"
    b"    If rTags.State <> 0 Then rTags.Close\r\n"
    b"End Sub\r\n"
    b"\r\n"
    b"Private Sub ConfigurarGrid()\r\n"
    b"    With lstProdutos\r\n"
    b"        .Cols = 6\r\n"
    b"        .ColWidth(0) = 0\r\n"
    b"        .ColWidth(1) = 2100\r\n"
    b"        .ColWidth(2) = 3900\r\n"
    b"        .ColWidth(3) = 1500\r\n"
    b"        .ColWidth(4) = 2100\r\n"
    b"        .ColWidth(5) = 1500\r\n"
    b"        .Row = 0: .Col = 0: .Text = \"codigo\"\r\n"
    b"        .Row = 0: .Col = 1: .Text = \"Cod. Barra\"\r\n"
    b"        .Row = 0: .Col = 2: .Text = \"Descri\xe7\xe3o\"\r\n"
    b"        .Row = 0: .Col = 3: .Text = \"NCM\": .CellBackColor = &H00C0C0C0\r\n"
    b"        .Row = 0: .Col = 4: .Text = \"Categoria\"\r\n"
    b"        .Row = 0: .Col = 5: .Text = \"Tags\"\r\n"
    b"        .AllowUserResizing = 1\r\n"
    b"        .SelectionMode = 1\r\n"
    b"    End With\r\n"
    b"End Sub\r\n"
    b"\r\n"
    b"Private Sub CarregarGrid()\r\n"
    b"    Dim rProd As ADODB.Recordset\r\n"
    b"    Dim sql As String, w As String\r\n"
    b"    Dim r As Integer\r\n"
    b"    Dim bTextSearch As Boolean\r\n"
    b"\r\n"
    b"    ConfigurarGrid\r\n"
    b"    lstProdutos.Rows = 1\r\n"
    b"\r\n"
    b"    bTextSearch = False\r\n"
    b"    w = \"WHERE 1=1\"\r\n"
    b"\r\n"
    b"    ' Campo de texto ativo desvincula filtros de combo\r\n"
    b"    If optCodBarra.Value And Trim(txtCodBarraF.Text) <> \"\" Then\r\n"
    b"        w = w & \" AND cod_barra LIKE '%\" & Replace(Trim(txtCodBarraF.Text), \"'\", \"''\") & \"%'\"\r\n"
    b"        bTextSearch = True\r\n"
    b"    ElseIf optDesc.Value And Trim(txtDescF.Text) <> \"\" Then\r\n"
    b"        w = w & \" AND descricao LIKE '%\" & Replace(Trim(txtDescF.Text), \"'\", \"''\") & \"%'\"\r\n"
    b"        bTextSearch = True\r\n"
    b"    ElseIf optNCM.Value And Trim(txtNCMF.Text) <> \"\" Then\r\n"
    b"        w = w & \" AND NCM LIKE '%\" & Replace(Trim(txtNCMF.Text), \"'\", \"''\") & \"%'\"\r\n"
    b"        bTextSearch = True\r\n"
    b"    End If\r\n"
    b"\r\n"
    b"    If Not bTextSearch Then\r\n"
    b"        If cboCategoriaF.Text <> \"\" Then\r\n"
    b"            w = w & \" AND categoria = '\" & Replace(cboCategoriaF.Text, \"'\", \"''\") & \"'\"\r\n"
    b"        End If\r\n"
    b"        If cboTagsF.Text <> \"\" And cboTagsF.Text <> \"TODOS\" Then\r\n"
    b"            w = w & \" AND TAGS = '\" & Replace(cboTagsF.Text, \"'\", \"''\") & \"'\"\r\n"
    b"        End If\r\n"
    b"    End If\r\n"
    b"\r\n"
    b"    sql = \"SELECT TOP 300 codigo, cod_barra, descricao, NCM, categoria, ISNULL(TAGS,'') AS TAGS \" & _\r\n"
    b"          \"FROM produtos \" & w & \" ORDER BY descricao\"\r\n"
    b"    RsOpen rProd, sql\r\n"
    b"    r = 1\r\n"
    b"    Do While Not rProd.EOF\r\n"
    b"        With lstProdutos\r\n"
    b"            .Rows = r + 1\r\n"
    b"            .Row = r: .Col = 0: .Text = CStr(rProd(\"codigo\"))\r\n"
    b"            .Row = r: .Col = 1: .Text = Trim(IIf(IsNull(rProd(\"cod_barra\")), \"\", rProd(\"cod_barra\")))\r\n"
    b"            .Row = r: .Col = 2: .Text = Trim(IIf(IsNull(rProd(\"descricao\")), \"\", rProd(\"descricao\")))\r\n"
    b"            .Row = r: .Col = 3: .Text = Trim(IIf(IsNull(rProd(\"NCM\")), \"\", rProd(\"NCM\"))): .CellBackColor = &H00E0E0E0\r\n"
    b"            .Row = r: .Col = 4: .Text = Trim(IIf(IsNull(rProd(\"categoria\")), \"\", rProd(\"categoria\")))\r\n"
    b"            .Row = r: .Col = 5: .Text = Trim(rProd(\"TAGS\"))\r\n"
    b"        End With\r\n"
    b"        r = r + 1\r\n"
    b"        rProd.MoveNext\r\n"
    b"    Loop\r\n"
    b"    If rProd.State <> 0 Then rProd.Close\r\n"
    b"End Sub\r\n"
    b"\r\n"
    b"' --- Eventos dos combos ---\r\n"
    b"Private Sub cboCategoriaF_Click()\r\n"
    b"    CarregarTags\r\n"
    b"    CarregarGrid\r\n"
    b"End Sub\r\n"
    b"\r\n"
    b"Private Sub cboTagsF_Click()\r\n"
    b"    CarregarGrid\r\n"
    b"End Sub\r\n"
    b"\r\n"
    b"Private Sub cmdFiltrar_Click()\r\n"
    b"    CarregarGrid\r\n"
    b"End Sub\r\n"
    b"\r\n"
    b"' --- Selecao e captura do NCM ---\r\n"
    b"Private Sub lstProdutos_DblClick()\r\n"
    b"    cmdUsarNCM_Click\r\n"
    b"End Sub\r\n"
    b"\r\n"
    b"Private Sub cmdUsarNCM_Click()\r\n"
    b"    If lstProdutos.Row < 1 Then MsgBox \"Selecione um produto.\", vbInformation: Exit Sub\r\n"
    b"    Dim sNCM As String\r\n"
    b"    sNCM = Trim(lstProdutos.TextMatrix(lstProdutos.Row, 3))\r\n"
    b"    If sNCM = \"\" Then MsgBox \"Produto sem NCM.\", vbInformation: Exit Sub\r\n"
    b"    sNCMSelecionado = sNCM\r\n"
    b"    Me.Hide\r\n"
    b"End Sub\r\n"
    b"\r\n"
    b"Private Sub cmdFechar_Click()\r\n"
    b"    sNCMSelecionado = \"\"\r\n"
    b"    Me.Hide\r\n"
    b"End Sub\r\n"
)

with open(FILE, "wb") as f:
    f.write(frm)
print(f"Criado: {FILE}")
print(f"Tamanho: {len(frm)} bytes")
