# -*- coding: windows-1252 -*-
path = 'C:/Projeto/Compartilhado/Forms/Categorias_Cadastro.frm'

content = (
'VERSION 5.00\r\n'
'Object = "{5E9E78A0-531B-11CF-91F6-C2863C385E30}#1.0#0"; "msflxgrd.ocx"\r\n'
'Begin VB.Form Categorias_Cadastro\r\n'
'   BackColor       =   &H00D8E9EC&\r\n'
'   BorderStyle     =   3  \'Fixed Dialog\r\n'
'   Caption         =   "Cadastro de Categorias"\r\n'
'   ClientHeight    =   5760\r\n'
'   ClientLeft      =   45\r\n'
'   ClientTop       =   330\r\n'
'   ClientWidth     =   8700\r\n'
'   MaxButton       =   0   \'False\r\n'
'   MinButton       =   0   \'False\r\n'
'   ScaleHeight     =   5760\r\n'
'   ScaleWidth      =   8700\r\n'
'   ShowInTaskbar   =   0   \'False\r\n'
'   StartUpPosition =   2  \'CenterScreen\r\n'
'   Begin VB.PictureBox picTitulo\r\n'
'      Appearance      =   0  \'Flat\r\n'
'      BackColor       =   &H00003399&\r\n'
'      BorderStyle     =   0  \'None\r\n'
'      ForeColor       =   &H80000008&\r\n'
'      Height          =   570\r\n'
'      Left            =   0\r\n'
'      ScaleHeight     =   570\r\n'
'      ScaleWidth      =   8700\r\n'
'      TabIndex        =   20\r\n'
'      Top             =   0\r\n'
'      Width           =   8700\r\n'
'      Begin VB.Label lblTitulo\r\n'
'         Alignment       =   2  \'Center\r\n'
'         Appearance      =   0  \'Flat\r\n'
'         BackColor       =   &H00003399&\r\n'
'         BackStyle       =   0  \'Transparent\r\n'
'         Caption         =   "CADASTRO DE CATEGORIAS"\r\n'
'         BeginProperty Font\r\n'
'            Name            =   "Arial"\r\n'
'            Size            =   14\r\n'
'            Charset         =   0\r\n'
'            Weight          =   700\r\n'
'            Underline       =   0   \'False\r\n'
'            Italic          =   0   \'False\r\n'
'            Strikethrough   =   0   \'False\r\n'
'         EndProperty\r\n'
'         ForeColor       =   &H00FFFFFF&\r\n'
'         Height          =   435\r\n'
'         Left            =   0\r\n'
'         TabIndex        =   21\r\n'
'         Top             =   60\r\n'
'         Width           =   8700\r\n'
'      End\r\n'
'   End\r\n'
'   Begin MSFlexGridLib.MSFlexGrid gridCategorias\r\n'
'      Height          =   2700\r\n'
'      Left            =   120\r\n'
'      TabIndex        =   0\r\n'
'      Top             =   630\r\n'
'      Width           =   8460\r\n'
'      _ExtentX        =   14923\r\n'
'      _ExtentY        =   4762\r\n'
'      _Version        =   393216\r\n'
'   End\r\n'
'   Begin VB.Frame fraEntrada\r\n'
'      BackColor       =   &H00D8E9EC&\r\n'
'      Caption         =   "Dados da Categoria"\r\n'
'      Height          =   1035\r\n'
'      Left            =   120\r\n'
'      TabIndex        =   10\r\n'
'      Top             =   3390\r\n'
'      Width           =   8460\r\n'
'      Begin VB.TextBox txtCategoria\r\n'
'         Height          =   315\r\n'
'         Left            =   1560\r\n'
'         MaxLength       =   50\r\n'
'         TabIndex        =   1\r\n'
'         Top             =   300\r\n'
'         Width           =   6735\r\n'
'      End\r\n'
'      Begin VB.Label lblCategoria\r\n'
'         BackStyle       =   0  \'Transparent\r\n'
'         Caption         =   "Categoria:"\r\n'
'         Height          =   285\r\n'
'         Left            =   120\r\n'
'         TabIndex        =   12\r\n'
'         Top             =   330\r\n'
'         Width           =   1335\r\n'
'      End\r\n'
'      Begin VB.Label lblAviso\r\n'
'         BackStyle       =   0  \'Transparent\r\n'
'         Caption         =   ""\r\n'
'         ForeColor       =   &H000000FF&\r\n'
'         Height          =   255\r\n'
'         Left            =   120\r\n'
'         TabIndex        =   14\r\n'
'         Top             =   690\r\n'
'         Width           =   8220\r\n'
'      End\r\n'
'   End\r\n'
'   Begin VB.CommandButton cmdSair\r\n'
'      BackColor       =   &H00E0E0E0&\r\n'
'      Caption         =   "Sair"\r\n'
'      Height          =   405\r\n'
'      Left            =   7260\r\n'
'      TabIndex        =   9\r\n'
'      Top             =   4920\r\n'
'      Width           =   1200\r\n'
'   End\r\n'
'   Begin VB.CommandButton cmdCancelar\r\n'
'      BackColor       =   &H00E0E0E0&\r\n'
'      Caption         =   "Cancelar"\r\n'
'      Enabled         =   0  \'False\r\n'
'      Height          =   405\r\n'
'      Left            =   5940\r\n'
'      TabIndex        =   8\r\n'
'      Top             =   4920\r\n'
'      Width           =   1200\r\n'
'   End\r\n'
'   Begin VB.CommandButton cmdExcluir\r\n'
'      BackColor       =   &H000000FF&\r\n'
'      Caption         =   "Excluir"\r\n'
'      Height          =   405\r\n'
'      Left            =   3780\r\n'
'      TabIndex        =   7\r\n'
'      Top             =   4920\r\n'
'      Width           =   1200\r\n'
'   End\r\n'
'   Begin VB.CommandButton cmdEditar\r\n'
'      BackColor       =   &H0000C0FF&\r\n'
'      Caption         =   "Editar"\r\n'
'      Height          =   405\r\n'
'      Left            =   2460\r\n'
'      TabIndex        =   6\r\n'
'      Top             =   4920\r\n'
'      Width           =   1200\r\n'
'   End\r\n'
'   Begin VB.CommandButton cmdSalvar\r\n'
'      BackColor       =   &H0000C000&\r\n'
'      Caption         =   "Salvar"\r\n'
'      Enabled         =   0  \'False\r\n'
'      Height          =   405\r\n'
'      Left            =   1200\r\n'
'      TabIndex        =   5\r\n'
'      Top             =   4920\r\n'
'      Width           =   1200\r\n'
'   End\r\n'
'   Begin VB.CommandButton cmdNovo\r\n'
'      BackColor       =   &H0000FF00&\r\n'
'      Caption         =   "Novo"\r\n'
'      Height          =   405\r\n'
'      Left            =   120\r\n'
'      TabIndex        =   4\r\n'
'      Top             =   4920\r\n'
'      Width           =   1200\r\n'
'   End\r\n'
'   Begin VB.Label lblRegistros\r\n'
'      BackStyle       =   0  \'Transparent\r\n'
'      Caption         =   ""\r\n'
'      Height          =   255\r\n'
'      Left            =   120\r\n'
'      TabIndex        =   22\r\n'
'      Top             =   3360\r\n'
'      Width           =   4800\r\n'
'   End\r\n'
'End\r\n'
'Attribute VB_Name = "Categorias_Cadastro"\r\n'
'Attribute VB_GlobalNameSpace = False\r\n'
'Attribute VB_Creatable = False\r\n'
'Attribute VB_PredeclaredId = True\r\n'
'Attribute VB_Exposed = False\r\n'
'Dim vTipoEdicao As String\r\n'
'Dim vIDCategoria As Long\r\n'
'Dim tipoEmpresa As Integer\r\n'
'\r\n'
'Private Sub Form_Load()\r\n'
'    Me.Left = (Screen.Width - Me.Width) / 2\r\n'
'    Me.Top = (Screen.Height - Me.Height) / 2\r\n'
'    Dim cCfg As Object\r\n'
'    Set cCfg = sysConfig("TIPO_EMPRESA")\r\n'
'    tipoEmpresa = CInt(cCfg.Value)\r\n'
'    DesabilitarEdicao\r\n'
'    ExibirGrid\r\n'
'End Sub\r\n'
'\r\n'
'Private Sub ExibirGrid()\r\n'
'    Dim r As ADODB.Recordset\r\n'
'    RsOpen r, "SELECT ID_Categoria, Categoria FROM Categorias WHERE Tipo_Empresa = " & tipoEmpresa & " ORDER BY Categoria"\r\n'
'    FormatarGrid r\r\n'
'    If r.State <> 0 Then r.Close\r\n'
'    lblRegistros.Caption = gridCategorias.Rows - 1 & " categoria(s) cadastrada(s)"\r\n'
'End Sub\r\n'
'\r\n'
'Private Sub FormatarGrid(rTabela As ADODB.Recordset)\r\n'
'    With gridCategorias\r\n'
'        .Visible = False\r\n'
'        .Redraw = False\r\n'
'        .Clear\r\n'
'        .Cols = 2\r\n'
'        .Rows = 2\r\n'
'        .FixedRows = 1\r\n'
'        .FixedCols = 0\r\n'
'        .ColWidth(0) = 600\r\n'
'        .ColWidth(1) = 7740\r\n'
'        .TextMatrix(0, 0) = "C\xf3d."\r\n'
'        .TextMatrix(0, 1) = "CATEGORIA"\r\n'
'        .Col = 0: .Row = 0: .CellFontBold = True: .CellAlignment = 4\r\n'
'        .Col = 1: .Row = 0: .CellFontBold = True: .CellAlignment = 4\r\n'
'        If Not rTabela Is Nothing Then\r\n'
'            Do While Not rTabela.EOF\r\n'
'                .TextMatrix(.Rows - 1, 0) = rTabela("ID_Categoria")\r\n'
'                .TextMatrix(.Rows - 1, 1) = rTabela("Categoria")\r\n'
'                rTabela.MoveNext\r\n'
'                .Rows = .Rows + 1\r\n'
'            Loop\r\n'
'        End If\r\n'
'        If .Rows > 1 Then .Rows = .Rows - 1\r\n'
'        .Visible = True\r\n'
'        .Redraw = True\r\n'
'    End With\r\n'
'End Sub\r\n'
'\r\n'
'Private Sub HabilitarEdicao()\r\n'
'    txtCategoria.Enabled = True\r\n'
'    cmdSalvar.Enabled = True\r\n'
'    cmdCancelar.Enabled = True\r\n'
'    cmdNovo.Enabled = False\r\n'
'    cmdEditar.Enabled = False\r\n'
'    cmdExcluir.Enabled = False\r\n'
'    lblAviso.Caption = ""\r\n'
'End Sub\r\n'
'\r\n'
'Private Sub DesabilitarEdicao()\r\n'
'    txtCategoria.Text = ""\r\n'
'    txtCategoria.Enabled = False\r\n'
'    cmdSalvar.Enabled = False\r\n'
'    cmdCancelar.Enabled = False\r\n'
'    cmdNovo.Enabled = True\r\n'
'    cmdEditar.Enabled = True\r\n'
'    cmdExcluir.Enabled = True\r\n'
'    vIDCategoria = 0\r\n'
'    vTipoEdicao = ""\r\n'
'    lblAviso.Caption = ""\r\n'
'End Sub\r\n'
'\r\n'
'Private Sub cmdNovo_Click()\r\n'
'    vTipoEdicao = "Novo"\r\n'
'    txtCategoria.Text = ""\r\n'
'    HabilitarEdicao\r\n'
'    txtCategoria.SetFocus\r\n'
'End Sub\r\n'
'\r\n'
'Private Sub cmdEditar_Click()\r\n'
'    If gridCategorias.Row < 1 Then\r\n'
'        MsgBox "Selecione uma categoria para editar!", vbExclamation, "Aten\xe7\xe3o"\r\n'
'        Exit Sub\r\n'
'    End If\r\n'
'    vIDCategoria = CLng(gridCategorias.TextMatrix(gridCategorias.Row, 0))\r\n'
'    Dim r As ADODB.Recordset\r\n'
'    RsOpen r, "SELECT Categoria FROM Categorias WHERE ID_Categoria = " & vIDCategoria\r\n'
'    If Not r.EOF Then\r\n'
'        txtCategoria.Text = r("Categoria")\r\n'
'    End If\r\n'
'    If r.State <> 0 Then r.Close\r\n'
'    vTipoEdicao = "Edicao"\r\n'
'    HabilitarEdicao\r\n'
'    txtCategoria.SetFocus\r\n'
'End Sub\r\n'
'\r\n'
'Private Sub cmdSalvar_Click()\r\n'
'    If Trim(txtCategoria.Text) = "" Then\r\n'
'        lblAviso.Caption = "* Informe o nome da Categoria!"\r\n'
'        txtCategoria.SetFocus\r\n'
'        Exit Sub\r\n'
'    End If\r\n'
'\r\n'
'    Dim vNome As String\r\n'
'    vNome = UCase(Trim(txtCategoria.Text))\r\n'
'\r\n'
'    If vTipoEdicao = "Novo" Then\r\n'
'        SQLExecuta "INSERT INTO Categorias (Categoria, Tipo_Empresa) VALUES (\'" & vNome & "\', " & tipoEmpresa & ")"\r\n'
'        MsgBox "Categoria cadastrada com sucesso!", vbInformation, "Online Commerce"\r\n'
'    Else\r\n'
'        SQLExecuta "UPDATE Categorias SET Categoria = \'" & vNome & "\' WHERE ID_Categoria = " & vIDCategoria\r\n'
'        MsgBox "Categoria alterada com sucesso!", vbInformation, "Online Commerce"\r\n'
'    End If\r\n'
'\r\n'
'    DesabilitarEdicao\r\n'
'    ExibirGrid\r\n'
'End Sub\r\n'
'\r\n'
'Private Sub cmdExcluir_Click()\r\n'
'    If gridCategorias.Row < 1 Then\r\n'
'        MsgBox "Selecione uma categoria para excluir!", vbExclamation, "Aten\xe7\xe3o"\r\n'
'        Exit Sub\r\n'
'    End If\r\n'
'    vIDCategoria = CLng(gridCategorias.TextMatrix(gridCategorias.Row, 0))\r\n'
'    Dim vNomeExc As String\r\n'
'    vNomeExc = gridCategorias.TextMatrix(gridCategorias.Row, 1)\r\n'
'    If MsgBox("Excluir a categoria \'" & vNomeExc & "\'?" & vbCrLf & "Esta a\xe7\xe3o n\xe3o pode ser desfeita.", vbQuestion + vbYesNo, "Confirmar Exclus\xe3o") = vbNo Then Exit Sub\r\n'
'    SQLExecuta "DELETE FROM Categorias WHERE ID_Categoria = " & vIDCategoria\r\n'
'    MsgBox "Categoria exclu\xedda com sucesso!", vbInformation, "Online Commerce"\r\n'
'    ExibirGrid\r\n'
'End Sub\r\n'
'\r\n'
'Private Sub cmdCancelar_Click()\r\n'
'    DesabilitarEdicao\r\n'
'End Sub\r\n'
'\r\n'
'Private Sub cmdSair_Click()\r\n'
'    Unload Me\r\n'
'End Sub\r\n'
'\r\n'
'Private Sub gridCategorias_DblClick()\r\n'
'    cmdEditar_Click\r\n'
'End Sub\r\n'
'\r\n'
'Private Sub txtCategoria_KeyPress(KeyAscii As Integer)\r\n'
'    KeyAscii = Asc(UCase(Chr(KeyAscii)))\r\n'
'End Sub\r\n'
)

out = content.encode('windows-1252')
out = out.replace(b'\r\n', b'\n').replace(b'\r', b'\n').replace(b'\n', b'\r\n')
open(path, 'wb').write(out)
print('Categorias_Cadastro.frm criado com sucesso!')
