data = open('OnlineCommerce/Forms/Entrada_Estoque.Frm', 'rb').read()

old_sub = (
    b'Sub cmdAtualProd_Click()\r\n'
    b'If ShowMsg("Deseja cadastrar o produto " & txtDescricaoSel & " ?", vbInformation + vbYesNo) = vbYes Then\r\n'
    b'    Load Produtos_Cadastro\r\n'
    b'    Produtos_Cadastro.SSTab1.Tab = 0\r\n'
    b'    \r\n'
    b'    Produtos_Cadastro.CriarNovoProduto\r\n'
    b'    \r\n'
    b'    If txtCodBarraSel.Text = "SEM GTIN" Then Produtos_Cadastro.txtCodBarra.Text = "" Else Produtos_Cadastro.txtCodBarra.Text = txtCodBarraSel.Text\r\n'
    b'    If txtCodBarraSel.Text = "SEM GTIN" Then Produtos_Cadastro.txtEAN.Text = "" Else Produtos_Cadastro.txtEAN.Text = txtCodBarraSel.Text\r\n'
    b'    Produtos_Cadastro.txtDescricao = TirarEspaco(txtDescricaoSel.Text)\r\n'
    b'    Produtos_Cadastro.cboUnidMedida = txtUnidMedSel.Text\r\n'
    b'    Produtos_Cadastro.txtNCM = txtNCMSel.Text\r\n'
    b'    If Mid(txtCFOPSel, 2, 1) = 4 Then Produtos_Cadastro.cboCFOP = "5405" Else Produtos_Cadastro.cboCFOP = "5102"\r\n'
    b'    If Mid(txtCFOPSel, 2, 1) = 4 Then Produtos_Cadastro.cboCST = "500" Else Produtos_Cadastro.cboCST = "102"\r\n'
    b'    \'Produtos_Cadastro.txtCfop = "5102"\r\n'
    b'    \'Produtos_Cadastro.txtCST = "102"\r\n'
    b'    Produtos_Cadastro.txtCusto = txtValorSel.Text\r\n'
    b'    Produtos_Cadastro.txtMargemVV = "0"\r\n'
    b'    Produtos_Cadastro.txtValorVV = "0"\r\n'
    b'    Produtos_Cadastro.txtMargemVP = "0"\r\n'
    b'    Produtos_Cadastro.txtValorVP = "0"\r\n'
    b'    Produtos_Cadastro.txtMargemAV = "0"\r\n'
    b'    Produtos_Cadastro.txtValorAV = "0"\r\n'
    b'    Produtos_Cadastro.txtMargemAP = "0"\r\n'
    b'    Produtos_Cadastro.txtValorAP = "0"\r\n'
    b'    Produtos_Cadastro.Show\r\n'
    b'End If\r\n'
    b'End Sub\r\n'
)

new_sub = (
    b'Sub cmdAtualProd_Click()\r\n'
    b'If ShowMsg("Deseja cadastrar o produto " & txtDescricaoSel & " ?", vbInformation + vbYesNo) = vbYes Then\r\n'
    b'\r\n'
    b'    If txtItem.Text = "" Or txtCodNota.Text = "" Then\r\n'
    b'        MsgBox "Selecione um item da nota antes de cadastrar.", vbExclamation\r\n'
    b'        Exit Sub\r\n'
    b'    End If\r\n'
    b'\r\n'
    b'    \' 1. Buscar todos os campos fiscais do item\r\n'
    b'    Dim rItem As ADODB.Recordset\r\n'
    b'    Set rItem = dbData.OpenRecordset( _\r\n'
    b'        "SELECT pICMS, pRedBC, modBC, modBCST, pMVAST, pICMSST, pRedBCST, " & _\r\n'
    b'        "PISCST, PISpPIS, COFINSCST, COFINSpCOFINS, IPICST, IPIpIPI, " & _\r\n'
    b'        "CEST, IBSCBSCST, IBSUFpAliq, IBSMunpAliq, CBSpAliq, ISCST, ISpIS, CFOP " & _\r\n'
    b'        "FROM EntradaEstoqueItens WHERE Item = " & Val(txtItem.Text) & " AND CodigoNota = " & Val(txtCodNota.Text))\r\n'
    b'\r\n'
    b'    If rItem.EOF Then\r\n'
    b'        rItem.Close: Set rItem = Nothing\r\n'
    b'        MsgBox "Item nao encontrado.", vbExclamation\r\n'
    b'        Exit Sub\r\n'
    b'    End If\r\n'
    b'\r\n'
    b'    \' 2. CRT da empresa para converter CFOP/CST\r\n'
    b'    Dim rEmp As ADODB.Recordset\r\n'
    b'    Set rEmp = dbData.OpenRecordset("SELECT TOP 1 CRT FROM empresa")\r\n'
    b'    Dim nCRT As Integer\r\n'
    b'    nCRT = IIf(rEmp.EOF, 1, Val(rEmp("CRT") & ""))\r\n'
    b'    rEmp.Close: Set rEmp = Nothing\r\n'
    b'\r\n'
    b'    \' 3. Converter CFOP entrada -> CFOP venda pelos ultimos 3 digitos\r\n'
    b'    \' x403 = ST ja pago (substituido)  -> 5405 / CSOSN 500 / CST 060\r\n'
    b'    \' x401 = ST substituto             -> 5401 / CSOSN 201 / CST 010\r\n'
    b'    \' x101 = industrializacao propria  -> 5101 / CSOSN 102 / CST 000\r\n'
    b'    \' demais (102 etc) = revenda normal -> 5102 / CSOSN 102 / CST 000\r\n'
    b'    Dim nUlt3 As Long\r\n'
    b'    nUlt3 = Val(rItem("CFOP") & "") Mod 1000\r\n'
    b'    Dim sCFOPVenda As String, sCSTVenda As String\r\n'
    b'    If nUlt3 = 403 Then\r\n'
    b'        sCFOPVenda = "5405": sCSTVenda = IIf(nCRT = 1, "500", "060")\r\n'
    b'    ElseIf nUlt3 = 401 Then\r\n'
    b'        sCFOPVenda = "5401": sCSTVenda = IIf(nCRT = 1, "201", "010")\r\n'
    b'    ElseIf nUlt3 = 101 Then\r\n'
    b'        sCFOPVenda = "5101": sCSTVenda = IIf(nCRT = 1, "102", "000")\r\n'
    b'    Else\r\n'
    b'        sCFOPVenda = "5102": sCSTVenda = IIf(nCRT = 1, "102", "000")\r\n'
    b'    End If\r\n'
    b'\r\n'
    b'    \' 4. Abrir e inicializar Produtos_Cadastro\r\n'
    b'    Load Produtos_Cadastro\r\n'
    b'    Produtos_Cadastro.SSTab1.Tab = 0\r\n'
    b'    Produtos_Cadastro.CriarNovoProduto\r\n'
    b'\r\n'
    b'    \' 5. Dados basicos\r\n'
    b'    If txtCodBarraSel.Text = "SEM GTIN" Or txtCodBarraSel.Text = "" Then\r\n'
    b'        Produtos_Cadastro.txtCodBarra.Text = ""\r\n'
    b'        Produtos_Cadastro.txtEAN.Text = ""\r\n'
    b'    Else\r\n'
    b'        Produtos_Cadastro.txtCodBarra.Text = txtCodBarraSel.Text\r\n'
    b'        Produtos_Cadastro.txtEAN.Text = txtCodBarraSel.Text\r\n'
    b'    End If\r\n'
    b'    Produtos_Cadastro.txtDescricao.Text = TirarEspaco(txtDescricaoSel.Text)\r\n'
    b'    Produtos_Cadastro.cboUnidMedida.Text = txtUnidMedSel.Text\r\n'
    b'    Produtos_Cadastro.txtNCM.Text = txtNCMSel.Text\r\n'
    b'    Produtos_Cadastro.txtCEST.Text = ValidateNull(rItem("CEST"))\r\n'
    b'\r\n'
    b'    \' 6. CFOP e CST convertidos (combos ja populados pelo Form_Load)\r\n'
    b'    Produtos_Cadastro.cboCFOP.Text = sCFOPVenda\r\n'
    b'    Produtos_Cadastro.cboCST.Text = sCSTVenda\r\n'
    b'\r\n'
    b'    \' 7. ICMS\r\n'
    b'    Produtos_Cadastro.txtICMSAliquota.Text = FormatNumber(ValidateNull(rItem("pICMS")), 2)\r\n'
    b'    Produtos_Cadastro.txtRedBCAliquota.Text = FormatNumber(ValidateNull(rItem("pRedBC")), 2)\r\n'
    b'\r\n'
    b'    \' 8. Substituicao Tributaria\r\n'
    b'    Produtos_Cadastro.txtMVA.Text = FormatNumber(ValidateNull(rItem("pMVAST")), 2)\r\n'
    b'    Produtos_Cadastro.txtSTAliq.Text = FormatNumber(ValidateNull(rItem("pICMSST")), 2)\r\n'
    b'    Produtos_Cadastro.txtRedBCST.Text = FormatNumber(ValidateNull(rItem("pRedBCST")), 2)\r\n'
    b'    Dim nModBC As Integer, nModBCST As Integer\r\n'
    b'    nModBC = IIf(IsNull(rItem("modBC")), 3, Val(rItem("modBC") & ""))\r\n'
    b'    nModBCST = IIf(IsNull(rItem("modBCST")), 4, Val(rItem("modBCST") & ""))\r\n'
    b'    If nModBC >= 0 And nModBC <= 3 Then Produtos_Cadastro.cboModBC.ListIndex = nModBC\r\n'
    b'    If nModBCST >= 0 And nModBCST <= 6 Then Produtos_Cadastro.cboModBCST.ListIndex = nModBCST\r\n'
    b'\r\n'
    b'    \' 9. PIS\r\n'
    b'    Produtos_Cadastro.txtPISCST.Text = ValidateNull(rItem("PISCST"))\r\n'
    b'    Produtos_Cadastro.txtPisAliquota.Text = FormatNumber(ValidateNull(rItem("PISpPIS")), 2)\r\n'
    b'\r\n'
    b'    \' 10. COFINS\r\n'
    b'    Produtos_Cadastro.txtCOFINSCST.Text = ValidateNull(rItem("COFINSCST"))\r\n'
    b'    Produtos_Cadastro.txtCofinsAliquota.Text = FormatNumber(ValidateNull(rItem("COFINSpCOFINS")), 2)\r\n'
    b'\r\n'
    b'    \' 11. IPI\r\n'
    b'    Produtos_Cadastro.txtIPICST.Text = ValidateNull(rItem("IPICST"))\r\n'
    b'    Produtos_Cadastro.txtIPIAliquota.Text = FormatNumber(ValidateNull(rItem("IPIpIPI")), 2)\r\n'
    b'\r\n'
    b'    \' 12. Reforma Tributaria: selecionar combo pelo prefixo de 2 digitos\r\n'
    b'    Dim sIBSCST As String, sISCST As String, k As Integer\r\n'
    b'    sIBSCST = Left(ValidateNull(rItem("IBSCBSCST")) & "  ", 2)\r\n'
    b'    If Trim(sIBSCST) = "" Then sIBSCST = "01"  \' default: tributado integralmente\r\n'
    b'    For k = 0 To Produtos_Cadastro.cboIBSCBSCST.ListCount - 1\r\n'
    b'        If Left(Produtos_Cadastro.cboIBSCBSCST.List(k), 2) = sIBSCST Then\r\n'
    b'            Produtos_Cadastro.cboIBSCBSCST.ListIndex = k: Exit For\r\n'
    b'        End If\r\n'
    b'    Next k\r\n'
    b'    Produtos_Cadastro.txtCBSpAliq.Text = FormatNumber(ValidateNull(rItem("CBSpAliq")), 4)\r\n'
    b'    Produtos_Cadastro.txtIBSUFpAliq.Text = FormatNumber(ValidateNull(rItem("IBSUFpAliq")), 4)\r\n'
    b'    Produtos_Cadastro.txtIBSMunpAliq.Text = FormatNumber(ValidateNull(rItem("IBSMunpAliq")), 4)\r\n'
    b'\r\n'
    b'    sISCST = Left(ValidateNull(rItem("ISCST")) & "  ", 2)\r\n'
    b'    If Trim(sISCST) = "" Then sISCST = "00"  \' default: nao incidente\r\n'
    b'    For k = 0 To Produtos_Cadastro.cboISCST.ListCount - 1\r\n'
    b'        If Left(Produtos_Cadastro.cboISCST.List(k), 2) = sISCST Then\r\n'
    b'            Produtos_Cadastro.cboISCST.ListIndex = k: Exit For\r\n'
    b'        End If\r\n'
    b'    Next k\r\n'
    b'    Produtos_Cadastro.txtISpIS.Text = FormatNumber(ValidateNull(rItem("ISpIS")), 4)\r\n'
    b'\r\n'
    b'    \' 13. Custo (margens ficam zeradas para o usuario preencher)\r\n'
    b'    Produtos_Cadastro.txtCusto.Text = txtValorSel.Text\r\n'
    b'    Produtos_Cadastro.txtMargemVV.Text = "0,00%"\r\n'
    b'    Produtos_Cadastro.txtMargemVP.Text = "0,00%"\r\n'
    b'    Produtos_Cadastro.txtMargemAV.Text = "0,00%"\r\n'
    b'    Produtos_Cadastro.txtMargemAP.Text = "0,00%"\r\n'
    b'    Produtos_Cadastro.txtValorVV.Text = "0,00"\r\n'
    b'    Produtos_Cadastro.txtValorVP.Text = "0,00"\r\n'
    b'    Produtos_Cadastro.txtValorAV.Text = "0,00"\r\n'
    b'    Produtos_Cadastro.txtValorAP.Text = "0,00"\r\n'
    b'\r\n'
    b'    rItem.Close\r\n'
    b'    Set rItem = Nothing\r\n'
    b'\r\n'
    b'    Produtos_Cadastro.Show\r\n'
    b'End If\r\n'
    b'End Sub\r\n'
)

c = data.count(old_sub)
print(f'cmdAtualProd_Click: count={c}')
if c == 1:
    data = data.replace(old_sub, new_sub)

data = data.replace(b'\r\n', b'\n').replace(b'\r', b'\n').replace(b'\n', b'\r\n')
open('OnlineCommerce/Forms/Entrada_Estoque.Frm', 'wb').write(data)
print('Salvo. Tamanho:', len(data))
