path = 'C:/projeto/OnlineCommerce/Forms/Entrada_Estoque.Frm'
data = open(path, 'rb').read().decode('windows-1252')

# --- old block (o que o fix anterior escreveu: 1 bloco coluna + 1 bloco SELECT, ambos com >24 continuacoes) ---
old = (
"'-- colunas\r\n"
"sSQL = \"INSERT INTO produtos_entrada (\" & _\r\n"
"       \"CODIGO, DATA_ENTRADA, HORA_ENTRADA, XML, \" & _\r\n"
"       \"CodigoNota, NumeroNota, SerieNF, ModeloNF, cCodigoNota, TipoDocumento, \" & _\r\n"
"       \"FinalidadeEmissaoNFe, TipoNota, ChavedeAcesso, ChavedeAcessoAdicional, \" & _\r\n"
"       \"DataEmissao, DataSaida, HoraSaida, \" & _\r\n"
"       \"NaturezaOperacao, IdentificadorDestino, ConsumidorFinal, IndicadorPresencaComprador, \" & _\r\n"
"       \"RazaoSocial, CNPJ_CPF, InscricaoEstadual, InscricaoMunicipal, Suframa, \" & _\r\n"
"       \"Logradouro, Numero, Complemento, Bairro, CodigoIBGE, Municipio, UF, CEP, CodigoPais, Pais, Telefone, \" & _\r\n"
"       \"IndicadorFormaPagamento, FormatoImpressaoDANFE, FormatoEmissaoNFe, IndicadorIEDestinatario, Origem, \" & _\r\n"
"       \"CodigoCorrentista, TranspCodigo, ValorFrete, ModFrete, TranspModFrete, \" & _\r\n"
"       \"TranspNome, TranspInscricaoEstadual, TranspEndereco, TranspUF, TranspMunicipio, TranspCNPJ_CPF, \" & _\r\n"
"       \"TranspValorServico, TranspBCRetencaoICMS, TranspAliquotaRetencaoICMS, TranspValorRetencaoICMS, \" & _\r\n"
"       \"TranspCFOP, TranspcMunFG, TranspPlaca, TranspPlacaUF, TranspRNTC, \" & _\r\n"
"       \"TranspReboquePlaca, TranspReboquePlacaUF, TranspReboqueRNTC, \" & _\r\n"
"       \"VolumeQuantidade, VolumeEspecie, VolumeMarca, VolumeNumeracao, VolumePesoLiquido, VolumePesoBruto, Lacres, \" & _\r\n"
"       \"ValorProdutos, ValorNota, ValorDesconto, ValorIPI, ValorICMS, ValorICMSST, \" & _\r\n"
"       \"BaseICMS, BaseICMSST, ValorSeguro, TipoDesconto, PercDesconto, ValorImportacao, \" & _\r\n"
"       \"ValorPIS, ValorCOFINS, ValorOutrasDespesas, ValorIsento, \" & _\r\n"
"       \"ValorServico, ValorBCISS, ValorISS, ValorPISISS, ValorPISCOFINS, \" & _\r\n"
"       \"ValorRetidoPIS, ValorRetidoCOFINS, ValorRetidoCSLL, ValorBCIRRF, ValorIRRF, \" & _\r\n"
"       \"ValorRetidoBCPrev, ValorRetidoPrev, ValorFunRural, \" & _\r\n"
"       \"ValorFCP, ValorFCPST, ValorFCPSTRet, ValorIPIDevol, \" & _\r\n"
"       \"vFCPUFDest, vICMSUFDest, vICMSUFRemet, \" & _\r\n"
"       \"qBCMono, vICMSMono, qBCMonoReten, vICMSMonoReten, qBCMonoRet, vICMSMonoRet, \" & _\r\n"
"       \"vNFTot, TotTributos, PagvPag, vBCSTRetTotal, vICMSSTRetTotal, vICMSSubstitutoTotal, \" & _\r\n"
"       \"TotIBSCBSvBC, TotIBSUFvDif, TotIBSUFvDevTrib, TotIBSUFvIBS, \" & _\r\n"
"       \"TotIBSMunvDif, TotIBSMunvDevTrib, TotIBSMunvIBS, \" & _\r\n"
"       \"TotIBSvIBS, TotIBSvCredPres, TotIBSvCredPresCondSus, \" & _\r\n"
"       \"TotCBSvDif, TotCBSvDevTrib, TotCBSvCBS, TotCBSvCredPres, TotCBSvCredPresCondSus, \" & _\r\n"
"       \"TotISvIS, TotIBSMonovIBSMono, TotIBSMonovCBSMono, \" & _\r\n"
"       \"TotIBSMonovIBSMonoReten, TotIBSMonovCBSMonoReten, TotIBSMonovIBSMonoRet, TotIBSMonovCBSMonoRet, \" & _\r\n"
"       \"NumeroFatura, ValorOriginalFatura, ValorDescontoFatura, ValorLiquidoFatura, \" & _\r\n"
"       \"NumeroDuplicata, VencimentoDuplicata, ValorDuplicata, \" & _\r\n"
"       \"InformacoesAdicionais, InformacoesComplementares, UFEmbarque, LocEmbarque, \" & _\r\n"
"       \"NumeroRecibo, DataHoraRecebimento, NumeroProtocolo, DataHoraProcotolo, \" & _\r\n"
"       \"Enviada, Cancelada, Denegada, Justificativa, EmProcessamento, \" & _\r\n"
"       \"CodigoObservacao, CanceladaProtocolo, CodigoNatureza, \" & _\r\n"
"       \"ContingenciaDataHora, ContingenciaJustificativa, Email, CodigoVenda) \"\r\n"
"'-- SELECT valores\r\n"
"sSQL = sSQL & _\r\n"
"       \"SELECT \" & VarCodEntradaNovo & \", \" & _\r\n"
"       \"CONVERT(DATETIME, '\" & sData & \"', 103), \" & _\r\n"
"       \"CONVERT(DATETIME, '\" & sHora & \"', 103), 1, \" & _\r\n"
"       \"e.CodigoNota, e.NumeroNota, e.SerieNF, e.ModeloNF, e.cCodigoNota, e.TipoDocumento, \" & _\r\n"
"       \"e.FinalidadeEmissaoNFe, e.TipoNota, e.ChavedeAcesso, e.ChavedeAcessoAdicional, \" & _\r\n"
"       \"e.DataEmissao, e.DataSaida, e.HoraSaida, \" & _\r\n"
"       \"e.NaturezaOperacao, e.IdentificadorDestino, e.ConsumidorFinal, e.IndicadorPresencaComprador, \" & _\r\n"
"       \"e.RazaoSocial, e.CNPJ_CPF, e.InscricaoEstadual, e.InscricaoMunicipal, e.Suframa, \" & _\r\n"
"       \"e.Logradouro, e.Numero, e.Complemento, e.Bairro, e.CodigoIBGE, e.Municipio, e.UF, e.CEP, e.CodigoPais, e.Pais, e.Telefone, \" & _\r\n"
"       \"e.IndicadorFormaPagamento, e.FormatoImpressaoDANFE, e.FormatoEmissaoNFe, e.IndicadorIEDestinatario, e.Origem, \" & _\r\n"
"       \"e.CodigoCorrentista, e.TranspCodigo, e.ValorFrete, e.ModFrete, e.TranspModFrete, \" & _\r\n"
"       \"e.TranspNome, e.TranspInscricaoEstadual, e.TranspEndereco, e.TranspUF, e.TranspMunicipio, e.TranspCNPJ_CPF, \" & _\r\n"
"       \"e.TranspValorServico, e.TranspBCRetencaoICMS, e.TranspAliquotaRetencaoICMS, e.TranspValorRetencaoICMS, \" & _\r\n"
"       \"e.TranspCFOP, e.TranspcMunFG, e.TranspPlaca, e.TranspPlacaUF, e.TranspRNTC, \" & _\r\n"
"       \"e.TranspReboquePlaca, e.TranspReboquePlacaUF, e.TranspReboqueRNTC, \" & _\r\n"
"       \"e.VolumeQuantidade, e.VolumeEspecie, e.VolumeMarca, e.VolumeNumeracao, e.VolumePesoLiquido, e.VolumePesoBruto, e.Lacres, \" & _\r\n"
"       \"e.ValorProdutos, e.ValorNota, e.ValorDesconto, e.ValorIPI, e.ValorICMS, e.ValorICMSST, \" & _\r\n"
"       \"e.BaseICMS, e.BaseICMSST, e.ValorSeguro, e.TipoDesconto, e.PercDesconto, e.ValorImportacao, \" & _\r\n"
"       \"e.ValorPIS, e.ValorCOFINS, e.ValorOutrasDespesas, e.ValorIsento, \" & _\r\n"
"       \"e.ValorServico, e.ValorBCISS, e.ValorISS, e.ValorPISISS, e.ValorPISCOFINS, \" & _\r\n"
"       \"e.ValorRetidoPIS, e.ValorRetidoCOFINS, e.ValorRetidoCSLL, e.ValorBCIRRF, e.ValorIRRF, \" & _\r\n"
"       \"e.ValorRetidoBCPrev, e.ValorRetidoPrev, e.ValorFunRural, \" & _\r\n"
"       \"e.ValorFCP, e.ValorFCPST, e.ValorFCPSTRet, e.ValorIPIDevol, \" & _\r\n"
"       \"e.vFCPUFDest, e.vICMSUFDest, e.vICMSUFRemet, \" & _\r\n"
"       \"e.qBCMono, e.vICMSMono, e.qBCMonoReten, e.vICMSMonoReten, e.qBCMonoRet, e.vICMSMonoRet, \" & _\r\n"
"       \"e.vNFTot, e.TotTributos, e.PagvPag, e.vBCSTRetTotal, e.vICMSSTRetTotal, e.vICMSSubstitutoTotal, \" & _\r\n"
"       \"e.TotIBSCBSvBC, e.TotIBSUFvDif, e.TotIBSUFvDevTrib, e.TotIBSUFvIBS, \" & _\r\n"
"       \"e.TotIBSMunvDif, e.TotIBSMunvDevTrib, e.TotIBSMunvIBS, \" & _\r\n"
"       \"e.TotIBSvIBS, e.TotIBSvCredPres, e.TotIBSvCredPresCondSus, \" & _\r\n"
"       \"e.TotCBSvDif, e.TotCBSvDevTrib, e.TotCBSvCBS, e.TotCBSvCredPres, e.TotCBSvCredPresCondSus, \" & _\r\n"
"       \"e.TotISvIS, e.TotIBSMonovIBSMono, e.TotIBSMonovCBSMono, \" & _\r\n"
"       \"e.TotIBSMonovIBSMonoReten, e.TotIBSMonovCBSMonoReten, e.TotIBSMonovIBSMonoRet, e.TotIBSMonovCBSMonoRet, \" & _\r\n"
"       \"e.NumeroFatura, e.ValorOriginalFatura, e.ValorDescontoFatura, e.ValorLiquidoFatura, \" & _\r\n"
"       \"e.NumeroDuplicata, e.VencimentoDuplicata, e.ValorDuplicata, \" & _\r\n"
"       \"e.InformacoesAdicionais, e.InformacoesComplementares, e.UFEmbarque, e.LocEmbarque, \" & _\r\n"
"       \"e.NumeroRecibo, e.DataHoraRecebimento, e.NumeroProtocolo, e.DataHoraProcotolo, \" & _\r\n"
"       \"e.Enviada, e.Cancelada, e.Denegada, e.Justificativa, e.EmProcessamento, \" & _\r\n"
"       \"e.CodigoObservacao, e.CanceladaProtocolo, e.CodigoNatureza, \" & _\r\n"
"       \"e.ContingenciaDataHora, e.ContingenciaJustificativa, e.Email, e.CodigoVenda \" & _\r\n"
"       \"FROM EntradaEstoque e WHERE e.CodigoNota = \" & lCompra & \";\"\r\n"
)

# --- new block: dividido em 6 partes, cada uma com max ~17 continuacoes ---
new = (
"'-- colunas: parte 1 de 3\r\n"
"sSQL = \"INSERT INTO produtos_entrada (CODIGO, DATA_ENTRADA, HORA_ENTRADA, XML, \" & _\r\n"
"       \"CodigoNota, NumeroNota, SerieNF, ModeloNF, cCodigoNota, TipoDocumento, \" & _\r\n"
"       \"FinalidadeEmissaoNFe, TipoNota, ChavedeAcesso, ChavedeAcessoAdicional, \" & _\r\n"
"       \"DataEmissao, DataSaida, HoraSaida, \" & _\r\n"
"       \"NaturezaOperacao, IdentificadorDestino, ConsumidorFinal, IndicadorPresencaComprador, \" & _\r\n"
"       \"RazaoSocial, CNPJ_CPF, InscricaoEstadual, InscricaoMunicipal, Suframa, \" & _\r\n"
"       \"Logradouro, Numero, Complemento, Bairro, CodigoIBGE, Municipio, UF, CEP, CodigoPais, Pais, Telefone, \" & _\r\n"
"       \"IndicadorFormaPagamento, FormatoImpressaoDANFE, FormatoEmissaoNFe, IndicadorIEDestinatario, Origem, \" & _\r\n"
"       \"CodigoCorrentista, TranspCodigo, ValorFrete, ModFrete, TranspModFrete, \"\r\n"
"'-- colunas: parte 2 de 3\r\n"
"sSQL = sSQL & _\r\n"
"       \"TranspNome, TranspInscricaoEstadual, TranspEndereco, TranspUF, TranspMunicipio, TranspCNPJ_CPF, \" & _\r\n"
"       \"TranspValorServico, TranspBCRetencaoICMS, TranspAliquotaRetencaoICMS, TranspValorRetencaoICMS, \" & _\r\n"
"       \"TranspCFOP, TranspcMunFG, TranspPlaca, TranspPlacaUF, TranspRNTC, \" & _\r\n"
"       \"TranspReboquePlaca, TranspReboquePlacaUF, TranspReboqueRNTC, \" & _\r\n"
"       \"VolumeQuantidade, VolumeEspecie, VolumeMarca, VolumeNumeracao, VolumePesoLiquido, VolumePesoBruto, Lacres, \" & _\r\n"
"       \"ValorProdutos, ValorNota, ValorDesconto, ValorIPI, ValorICMS, ValorICMSST, \" & _\r\n"
"       \"BaseICMS, BaseICMSST, ValorSeguro, TipoDesconto, PercDesconto, ValorImportacao, \" & _\r\n"
"       \"ValorPIS, ValorCOFINS, ValorOutrasDespesas, ValorIsento, \" & _\r\n"
"       \"ValorServico, ValorBCISS, ValorISS, ValorPISISS, ValorPISCOFINS, \" & _\r\n"
"       \"ValorRetidoPIS, ValorRetidoCOFINS, ValorRetidoCSLL, ValorBCIRRF, ValorIRRF, \" & _\r\n"
"       \"ValorRetidoBCPrev, ValorRetidoPrev, ValorFunRural, \" & _\r\n"
"       \"ValorFCP, ValorFCPST, ValorFCPSTRet, ValorIPIDevol, \" & _\r\n"
"       \"vFCPUFDest, vICMSUFDest, vICMSUFRemet, \"\r\n"
"'-- colunas: parte 3 de 3\r\n"
"sSQL = sSQL & _\r\n"
"       \"qBCMono, vICMSMono, qBCMonoReten, vICMSMonoReten, qBCMonoRet, vICMSMonoRet, \" & _\r\n"
"       \"vNFTot, TotTributos, PagvPag, vBCSTRetTotal, vICMSSTRetTotal, vICMSSubstitutoTotal, \" & _\r\n"
"       \"TotIBSCBSvBC, TotIBSUFvDif, TotIBSUFvDevTrib, TotIBSUFvIBS, \" & _\r\n"
"       \"TotIBSMunvDif, TotIBSMunvDevTrib, TotIBSMunvIBS, \" & _\r\n"
"       \"TotIBSvIBS, TotIBSvCredPres, TotIBSvCredPresCondSus, \" & _\r\n"
"       \"TotCBSvDif, TotCBSvDevTrib, TotCBSvCBS, TotCBSvCredPres, TotCBSvCredPresCondSus, \" & _\r\n"
"       \"TotISvIS, TotIBSMonovIBSMono, TotIBSMonovCBSMono, \" & _\r\n"
"       \"TotIBSMonovIBSMonoReten, TotIBSMonovCBSMonoReten, TotIBSMonovIBSMonoRet, TotIBSMonovCBSMonoRet, \" & _\r\n"
"       \"NumeroFatura, ValorOriginalFatura, ValorDescontoFatura, ValorLiquidoFatura, \" & _\r\n"
"       \"NumeroDuplicata, VencimentoDuplicata, ValorDuplicata, \" & _\r\n"
"       \"InformacoesAdicionais, InformacoesComplementares, UFEmbarque, LocEmbarque, \" & _\r\n"
"       \"NumeroRecibo, DataHoraRecebimento, NumeroProtocolo, DataHoraProcotolo, \" & _\r\n"
"       \"Enviada, Cancelada, Denegada, Justificativa, EmProcessamento, \" & _\r\n"
"       \"CodigoObservacao, CanceladaProtocolo, CodigoNatureza, \" & _\r\n"
"       \"ContingenciaDataHora, ContingenciaJustificativa, Email, CodigoVenda) \"\r\n"
"'-- SELECT: parte 1 de 3\r\n"
"sSQL = sSQL & _\r\n"
"       \"SELECT \" & VarCodEntradaNovo & \", \" & _\r\n"
"       \"CONVERT(DATETIME, '\" & sData & \"', 103), \" & _\r\n"
"       \"CONVERT(DATETIME, '\" & sHora & \"', 103), 1, \" & _\r\n"
"       \"e.CodigoNota, e.NumeroNota, e.SerieNF, e.ModeloNF, e.cCodigoNota, e.TipoDocumento, \" & _\r\n"
"       \"e.FinalidadeEmissaoNFe, e.TipoNota, e.ChavedeAcesso, e.ChavedeAcessoAdicional, \" & _\r\n"
"       \"e.DataEmissao, e.DataSaida, e.HoraSaida, \" & _\r\n"
"       \"e.NaturezaOperacao, e.IdentificadorDestino, e.ConsumidorFinal, e.IndicadorPresencaComprador, \" & _\r\n"
"       \"e.RazaoSocial, e.CNPJ_CPF, e.InscricaoEstadual, e.InscricaoMunicipal, e.Suframa, \" & _\r\n"
"       \"e.Logradouro, e.Numero, e.Complemento, e.Bairro, e.CodigoIBGE, e.Municipio, e.UF, e.CEP, e.CodigoPais, e.Pais, e.Telefone, \" & _\r\n"
"       \"e.IndicadorFormaPagamento, e.FormatoImpressaoDANFE, e.FormatoEmissaoNFe, e.IndicadorIEDestinatario, e.Origem, \" & _\r\n"
"       \"e.CodigoCorrentista, e.TranspCodigo, e.ValorFrete, e.ModFrete, e.TranspModFrete, \"\r\n"
"'-- SELECT: parte 2 de 3\r\n"
"sSQL = sSQL & _\r\n"
"       \"e.TranspNome, e.TranspInscricaoEstadual, e.TranspEndereco, e.TranspUF, e.TranspMunicipio, e.TranspCNPJ_CPF, \" & _\r\n"
"       \"e.TranspValorServico, e.TranspBCRetencaoICMS, e.TranspAliquotaRetencaoICMS, e.TranspValorRetencaoICMS, \" & _\r\n"
"       \"e.TranspCFOP, e.TranspcMunFG, e.TranspPlaca, e.TranspPlacaUF, e.TranspRNTC, \" & _\r\n"
"       \"e.TranspReboquePlaca, e.TranspReboquePlacaUF, e.TranspReboqueRNTC, \" & _\r\n"
"       \"e.VolumeQuantidade, e.VolumeEspecie, e.VolumeMarca, e.VolumeNumeracao, e.VolumePesoLiquido, e.VolumePesoBruto, e.Lacres, \" & _\r\n"
"       \"e.ValorProdutos, e.ValorNota, e.ValorDesconto, e.ValorIPI, e.ValorICMS, e.ValorICMSST, \" & _\r\n"
"       \"e.BaseICMS, e.BaseICMSST, e.ValorSeguro, e.TipoDesconto, e.PercDesconto, e.ValorImportacao, \" & _\r\n"
"       \"e.ValorPIS, e.ValorCOFINS, e.ValorOutrasDespesas, e.ValorIsento, \" & _\r\n"
"       \"e.ValorServico, e.ValorBCISS, e.ValorISS, e.ValorPISISS, e.ValorPISCOFINS, \" & _\r\n"
"       \"e.ValorRetidoPIS, e.ValorRetidoCOFINS, e.ValorRetidoCSLL, e.ValorBCIRRF, e.ValorIRRF, \" & _\r\n"
"       \"e.ValorRetidoBCPrev, e.ValorRetidoPrev, e.ValorFunRural, \" & _\r\n"
"       \"e.ValorFCP, e.ValorFCPST, e.ValorFCPSTRet, e.ValorIPIDevol, \" & _\r\n"
"       \"e.vFCPUFDest, e.vICMSUFDest, e.vICMSUFRemet, \"\r\n"
"'-- SELECT: parte 3 de 3\r\n"
"sSQL = sSQL & _\r\n"
"       \"e.qBCMono, e.vICMSMono, e.qBCMonoReten, e.vICMSMonoReten, e.qBCMonoRet, e.vICMSMonoRet, \" & _\r\n"
"       \"e.vNFTot, e.TotTributos, e.PagvPag, e.vBCSTRetTotal, e.vICMSSTRetTotal, e.vICMSSubstitutoTotal, \" & _\r\n"
"       \"e.TotIBSCBSvBC, e.TotIBSUFvDif, e.TotIBSUFvDevTrib, e.TotIBSUFvIBS, \" & _\r\n"
"       \"e.TotIBSMunvDif, e.TotIBSMunvDevTrib, e.TotIBSMunvIBS, \" & _\r\n"
"       \"e.TotIBSvIBS, e.TotIBSvCredPres, e.TotIBSvCredPresCondSus, \" & _\r\n"
"       \"e.TotCBSvDif, e.TotCBSvDevTrib, e.TotCBSvCBS, e.TotCBSvCredPres, e.TotCBSvCredPresCondSus, \" & _\r\n"
"       \"e.TotISvIS, e.TotIBSMonovIBSMono, e.TotIBSMonovCBSMono, \" & _\r\n"
"       \"e.TotIBSMonovIBSMonoReten, e.TotIBSMonovCBSMonoReten, e.TotIBSMonovIBSMonoRet, e.TotIBSMonovCBSMonoRet, \" & _\r\n"
"       \"e.NumeroFatura, e.ValorOriginalFatura, e.ValorDescontoFatura, e.ValorLiquidoFatura, \" & _\r\n"
"       \"e.NumeroDuplicata, e.VencimentoDuplicata, e.ValorDuplicata, \" & _\r\n"
"       \"e.InformacoesAdicionais, e.InformacoesComplementares, e.UFEmbarque, e.LocEmbarque, \" & _\r\n"
"       \"e.NumeroRecibo, e.DataHoraRecebimento, e.NumeroProtocolo, e.DataHoraProcotolo, \" & _\r\n"
"       \"e.Enviada, e.Cancelada, e.Denegada, e.Justificativa, e.EmProcessamento, \" & _\r\n"
"       \"e.CodigoObservacao, e.CanceladaProtocolo, e.CodigoNatureza, \" & _\r\n"
"       \"e.ContingenciaDataHora, e.ContingenciaJustificativa, e.Email, e.CodigoVenda \" & _\r\n"
"       \"FROM EntradaEstoque e WHERE e.CodigoNota = \" & lCompra & \";\"\r\n"
)

print('old found:', data.count(old))
data2 = data.replace(old, new, 1)
print('replaced:', data2 != data)
raw = data2.encode('windows-1252')
raw = raw.replace(b'\r\n', b'\n').replace(b'\r', b'\n').replace(b'\n', b'\r\n')
open(path, 'wb').write(raw)
print('ok')
