import sys
data = open('OnlineCommerce/Forms/NFe_Completa.frm', 'rb').read()

fixes = []

# ---- DistribuirFrete ----
old = (
    b'Private Sub DistribuirFrete()\r\n'
    b'Dim varQuantItens As Integer\r\n'
    b'Dim varValorTotalFrete As Currency\r\n'
    b'Dim varValorDividoFrete As Currency\r\n'
    b'\r\n'
    b'If txtCodNota.Text = "" Then Exit Sub\r\n'
    b'If GridNotasItens.rows <= 1 Then Exit Sub\r\n'
    b'\r\n'
    b'sSQL = "SELECT codigonota FROM NotaFiscalItens WHERE CodigoNota = " & Val(txtCodNota.Text)\r\n'
    b'RsOpen Tb, sSQL\r\n'
    b'\r\n'
    b'If Not Tb.EOF Then\r\n'
    b'    varQuantItens = Tb.RecordCount\r\n'
    b'Else\r\n'
    b'    varQuantItens = 0\r\n'
    b'End If\r\n'
    b'\r\n'
    b'If txtValorFrete.Text <> "0" And txtValorFrete.Text <> "" Then\r\n'
    b'    varValorTotalFrete = txtValorFrete.Text\r\n'
    b'Else\r\n'
    b'    varValorTotalFrete = 0\r\n'
    b'End If\r\n'
    b'\r\n'
    b'If varValorTotalFrete = 0 Or varQuantItens = 0 Then\r\n'
    b'    Exit Sub\r\n'
    b'Else\r\n'
    b'    varValorDividoFrete = varValorTotalFrete / varQuantItens\r\n'
    b'    \r\n'
    b'    sSQL = "UPDATE NotaFiscalItens SET " & _\r\n'
    b'           "valorfrete = " & FSQL(varValorDividoFrete, 2) & " FROM NotaFiscalItens WHERE CodigoNota = " & Val(txtCodNota.Text)\r\n'
    b'    SQLExecuta sSQL\r\n'
    b'End If\r\n'
    b'End Sub'
)
new = (
    b'Private Sub DistribuirFrete()\r\n'
    b'Dim varQuantItens       As Integer\r\n'
    b'Dim varValorTotalFrete  As Currency\r\n'
    b'Dim varValorDividoFrete As Currency\r\n'
    b'Dim varValorAjusteFrete As Currency\r\n'
    b'\r\n'
    b'If txtCodNota.Text = "" Then Exit Sub\r\n'
    b'If GridNotasItens.rows <= 1 Then Exit Sub\r\n'
    b'\r\n'
    b'sSQL = "SELECT codigonota FROM NotaFiscalItens WHERE CodigoNota = " & Val(txtCodNota.Text)\r\n'
    b'RsOpen Tb, sSQL\r\n'
    b'\r\n'
    b'If Not Tb.EOF Then\r\n'
    b'    varQuantItens = Tb.RecordCount\r\n'
    b'Else\r\n'
    b'    varQuantItens = 0\r\n'
    b'End If\r\n'
    b'\r\n'
    b'If txtValorFrete.Text <> "0" And txtValorFrete.Text <> "" Then\r\n'
    b'    varValorTotalFrete = txtValorFrete.Text\r\n'
    b'Else\r\n'
    b'    varValorTotalFrete = 0\r\n'
    b'End If\r\n'
    b'\r\n'
    b'If varValorTotalFrete = 0 Or varQuantItens = 0 Then\r\n'
    b'    Exit Sub\r\n'
    b'Else\r\n'
    b'    varValorDividoFrete = CCur(Format(varValorTotalFrete / varQuantItens, "0.00"))\r\n'
    b'    varValorAjusteFrete = varValorTotalFrete - (varValorDividoFrete * (varQuantItens - 1))\r\n'
    b'    \r\n'
    b'    sSQL = "UPDATE NotaFiscalItens SET valorfrete = " & FSQL(varValorDividoFrete, 2) & " WHERE CodigoNota = " & Val(txtCodNota.Text)\r\n'
    b'    SQLExecuta sSQL\r\n'
    b'    sSQL = "UPDATE TOP(1) NotaFiscalItens SET valorfrete = " & FSQL(varValorAjusteFrete, 2) & " WHERE CodigoNota = " & Val(txtCodNota.Text)\r\n'
    b'    SQLExecuta sSQL\r\n'
    b'End If\r\n'
    b'End Sub'
)
fixes.append((old, new))

# ---- DistribuirSeguro ----
old = (
    b'Private Sub DistribuirSeguro()\r\n'
    b'Dim varQuantItens As Integer\r\n'
    b'Dim vTotalSeguro As Currency\r\n'
    b'Dim vValorSeguroIndividual As Currency\r\n'
    b'\r\n'
    b'If txtCodNota.Text = "" Then Exit Sub\r\n'
    b'If GridNotasItens.rows <= 1 Then Exit Sub\r\n'
    b'\r\n'
    b'sSQL = "SELECT codigonota FROM NotaFiscalItens WHERE CodigoNota = " & Val(txtCodNota.Text)\r\n'
    b'RsOpen Tb, sSQL\r\n'
    b'\r\n'
    b'If Not Tb.EOF Then\r\n'
    b'    varQuantItens = Tb.RecordCount\r\n'
    b'Else\r\n'
    b'    varQuantItens = 0\r\n'
    b'End If\r\n'
    b'\r\n'
    b'If txtValorSeguro.Text <> "0" And txtValorSeguro.Text <> "" Then\r\n'
    b'    vTotalSeguro = txtValorSeguro.Text\r\n'
    b'Else\r\n'
    b'    vTotalSeguro = 0\r\n'
    b'End If\r\n'
    b'\r\n'
    b'If vTotalSeguro = 0 Or varQuantItens = 0 Then\r\n'
    b'    Exit Sub\r\n'
    b'Else\r\n'
    b'    vValorSeguroIndividual = vTotalSeguro / varQuantItens\r\n'
    b'    \r\n'
    b'    sSQL = "UPDATE NotaFiscalItens SET " & _\r\n'
    b'           "ValorSeguro = " & FSQL(vValorSeguroIndividual, 2) & " FROM NotaFiscalItens WHERE CodigoNota = " & Val(txtCodNota.Text)\r\n'
    b'    SQLExecuta sSQL\r\n'
    b'End If\r\n'
    b'End Sub'
)
new = (
    b'Private Sub DistribuirSeguro()\r\n'
    b'Dim varQuantItens          As Integer\r\n'
    b'Dim vTotalSeguro           As Currency\r\n'
    b'Dim vValorSeguroIndividual As Currency\r\n'
    b'Dim vValorSeguroAjuste     As Currency\r\n'
    b'\r\n'
    b'If txtCodNota.Text = "" Then Exit Sub\r\n'
    b'If GridNotasItens.rows <= 1 Then Exit Sub\r\n'
    b'\r\n'
    b'sSQL = "SELECT codigonota FROM NotaFiscalItens WHERE CodigoNota = " & Val(txtCodNota.Text)\r\n'
    b'RsOpen Tb, sSQL\r\n'
    b'\r\n'
    b'If Not Tb.EOF Then\r\n'
    b'    varQuantItens = Tb.RecordCount\r\n'
    b'Else\r\n'
    b'    varQuantItens = 0\r\n'
    b'End If\r\n'
    b'\r\n'
    b'If txtValorSeguro.Text <> "0" And txtValorSeguro.Text <> "" Then\r\n'
    b'    vTotalSeguro = txtValorSeguro.Text\r\n'
    b'Else\r\n'
    b'    vTotalSeguro = 0\r\n'
    b'End If\r\n'
    b'\r\n'
    b'If vTotalSeguro = 0 Or varQuantItens = 0 Then\r\n'
    b'    Exit Sub\r\n'
    b'Else\r\n'
    b'    vValorSeguroIndividual = CCur(Format(vTotalSeguro / varQuantItens, "0.00"))\r\n'
    b'    vValorSeguroAjuste     = vTotalSeguro - (vValorSeguroIndividual * (varQuantItens - 1))\r\n'
    b'    \r\n'
    b'    sSQL = "UPDATE NotaFiscalItens SET ValorSeguro = " & FSQL(vValorSeguroIndividual, 2) & " WHERE CodigoNota = " & Val(txtCodNota.Text)\r\n'
    b'    SQLExecuta sSQL\r\n'
    b'    sSQL = "UPDATE TOP(1) NotaFiscalItens SET ValorSeguro = " & FSQL(vValorSeguroAjuste, 2) & " WHERE CodigoNota = " & Val(txtCodNota.Text)\r\n'
    b'    SQLExecuta sSQL\r\n'
    b'End If\r\n'
    b'End Sub'
)
fixes.append((old, new))

# ---- DistribuirOutros ----
old = (
    b'Private Sub DistribuirOutros()\r\n'
    b'Dim varQuantItens As Integer\r\n'
    b'Dim vTotalOutros As Currency\r\n'
    b'Dim vValorOutrosIndividual As Currency\r\n'
    b'\r\n'
    b'If txtCodNota.Text = "" Then Exit Sub\r\n'
    b'If GridNotasItens.rows <= 1 Then Exit Sub\r\n'
    b'\r\n'
    b'sSQL = "SELECT codigonota FROM NotaFiscalItens WHERE CodigoNota = " & Val(txtCodNota.Text)\r\n'
    b'RsOpen Tb, sSQL\r\n'
    b'\r\n'
    b'If Not Tb.EOF Then\r\n'
    b'    varQuantItens = Tb.RecordCount\r\n'
    b'Else\r\n'
    b'    varQuantItens = 0\r\n'
    b'End If\r\n'
    b'\r\n'
    b'If txtValorOutrasDespesas.Text <> "0" And txtValorOutrasDespesas.Text <> "" Then\r\n'
    b'    vTotalOutros = txtValorOutrasDespesas.Text\r\n'
    b'Else\r\n'
    b'    vTotalOutros = 0\r\n'
    b'End If\r\n'
    b'\r\n'
    b'If vTotalOutros = 0 Or varQuantItens = 0 Then\r\n'
    b'    Exit Sub\r\n'
    b'Else\r\n'
    b'    vValorOutrosIndividual = vTotalOutros / varQuantItens\r\n'
    b'    \r\n'
    b'    sSQL = "UPDATE NotaFiscalItens SET " & _\r\n'
    b'           "ValorOutros = " & FSQL(vValorOutrosIndividual, 2) & " FROM NotaFiscalItens WHERE CodigoNota = " & Val(txtCodNota.Text)\r\n'
    b'    SQLExecuta sSQL\r\n'
    b'End If\r\n'
    b'End Sub'
)
new = (
    b'Private Sub DistribuirOutros()\r\n'
    b'Dim varQuantItens          As Integer\r\n'
    b'Dim vTotalOutros           As Currency\r\n'
    b'Dim vValorOutrosIndividual As Currency\r\n'
    b'Dim vValorOutrosAjuste     As Currency\r\n'
    b'\r\n'
    b'If txtCodNota.Text = "" Then Exit Sub\r\n'
    b'If GridNotasItens.rows <= 1 Then Exit Sub\r\n'
    b'\r\n'
    b'sSQL = "SELECT codigonota FROM NotaFiscalItens WHERE CodigoNota = " & Val(txtCodNota.Text)\r\n'
    b'RsOpen Tb, sSQL\r\n'
    b'\r\n'
    b'If Not Tb.EOF Then\r\n'
    b'    varQuantItens = Tb.RecordCount\r\n'
    b'Else\r\n'
    b'    varQuantItens = 0\r\n'
    b'End If\r\n'
    b'\r\n'
    b'If txtValorOutrasDespesas.Text <> "0" And txtValorOutrasDespesas.Text <> "" Then\r\n'
    b'    vTotalOutros = txtValorOutrasDespesas.Text\r\n'
    b'Else\r\n'
    b'    vTotalOutros = 0\r\n'
    b'End If\r\n'
    b'\r\n'
    b'If vTotalOutros = 0 Or varQuantItens = 0 Then\r\n'
    b'    Exit Sub\r\n'
    b'Else\r\n'
    b'    vValorOutrosIndividual = CCur(Format(vTotalOutros / varQuantItens, "0.00"))\r\n'
    b'    vValorOutrosAjuste     = vTotalOutros - (vValorOutrosIndividual * (varQuantItens - 1))\r\n'
    b'    \r\n'
    b'    sSQL = "UPDATE NotaFiscalItens SET ValorOutros = " & FSQL(vValorOutrosIndividual, 2) & " WHERE CodigoNota = " & Val(txtCodNota.Text)\r\n'
    b'    SQLExecuta sSQL\r\n'
    b'    sSQL = "UPDATE TOP(1) NotaFiscalItens SET ValorOutros = " & FSQL(vValorOutrosAjuste, 2) & " WHERE CodigoNota = " & Val(txtCodNota.Text)\r\n'
    b'    SQLExecuta sSQL\r\n'
    b'End If\r\n'
    b'End Sub'
)
fixes.append((old, new))

# ---- DistribuirDesconto ----
old = (
    b'Private Sub DistribuirDesconto()\r\n'
    b'Dim varQuantItens   As Integer\r\n'
    b'Dim vTotalDesc      As Currency\r\n'
    b'Dim vDescIndividual As Currency\r\n'
    b'\r\n'
    b'If txtCodNota.Text = "" Then Exit Sub\r\n'
    b'If GridNotasItens.rows <= 1 Then Exit Sub\r\n'
    b'\r\n'
    b'sSQL = "SELECT codigonota FROM NotaFiscalItens WHERE CodigoNota = " & Val(txtCodNota.Text)\r\n'
    b'RsOpen Tb, sSQL\r\n'
    b'\r\n'
    b'If Not Tb.EOF Then\r\n'
    b'    varQuantItens = Tb.RecordCount\r\n'
    b'Else\r\n'
    b'    varQuantItens = 0\r\n'
    b'End If\r\n'
    b'\r\n'
    b'If txtValorDesconto.Text <> "0" And txtValorDesconto.Text <> "" Then\r\n'
    b'    vTotalDesc = txtValorDesconto.Text\r\n'
    b'Else\r\n'
    b'    vTotalDesc = 0\r\n'
    b'End If\r\n'
    b'\r\n'
    b'If vTotalDesc = 0 Or varQuantItens = 0 Then\r\n'
    b'    Exit Sub\r\n'
    b'Else\r\n'
    b'    vDescIndividual = vTotalDesc / varQuantItens\r\n'
    b'    \r\n'
    b'    sSQL = "UPDATE NotaFiscalItens SET " & _\r\n'
    b'           "ValorDesconto = " & FSQL(vDescIndividual, 2) & " FROM NotaFiscalItens WHERE CodigoNota = " & Val(txtCodNota.Text)\r\n'
    b'    SQLExecuta sSQL\r\n'
    b'End If\r\n'
    b'End Sub'
)
new = (
    b'Private Sub DistribuirDesconto()\r\n'
    b'Dim varQuantItens   As Integer\r\n'
    b'Dim vTotalDesc      As Currency\r\n'
    b'Dim vDescIndividual As Currency\r\n'
    b'Dim vDescAjuste     As Currency\r\n'
    b'\r\n'
    b'If txtCodNota.Text = "" Then Exit Sub\r\n'
    b'If GridNotasItens.rows <= 1 Then Exit Sub\r\n'
    b'\r\n'
    b'sSQL = "SELECT codigonota FROM NotaFiscalItens WHERE CodigoNota = " & Val(txtCodNota.Text)\r\n'
    b'RsOpen Tb, sSQL\r\n'
    b'\r\n'
    b'If Not Tb.EOF Then\r\n'
    b'    varQuantItens = Tb.RecordCount\r\n'
    b'Else\r\n'
    b'    varQuantItens = 0\r\n'
    b'End If\r\n'
    b'\r\n'
    b'If txtValorDesconto.Text <> "0" And txtValorDesconto.Text <> "" Then\r\n'
    b'    vTotalDesc = txtValorDesconto.Text\r\n'
    b'Else\r\n'
    b'    vTotalDesc = 0\r\n'
    b'End If\r\n'
    b'\r\n'
    b'If vTotalDesc = 0 Or varQuantItens = 0 Then\r\n'
    b'    Exit Sub\r\n'
    b'Else\r\n'
    b'    vDescIndividual = CCur(Format(vTotalDesc / varQuantItens, "0.00"))\r\n'
    b'    vDescAjuste     = vTotalDesc - (vDescIndividual * (varQuantItens - 1))\r\n'
    b'    \r\n'
    b'    sSQL = "UPDATE NotaFiscalItens SET ValorDesconto = " & FSQL(vDescIndividual, 2) & " WHERE CodigoNota = " & Val(txtCodNota.Text)\r\n'
    b'    SQLExecuta sSQL\r\n'
    b'    sSQL = "UPDATE TOP(1) NotaFiscalItens SET ValorDesconto = " & FSQL(vDescAjuste, 2) & " WHERE CodigoNota = " & Val(txtCodNota.Text)\r\n'
    b'    SQLExecuta sSQL\r\n'
    b'End If\r\n'
    b'End Sub'
)
fixes.append((old, new))

for i, (old, new) in enumerate(fixes, 1):
    count = data.count(old)
    if count == 1:
        data = data.replace(old, new)
        print(f'{i} OK')
    else:
        print(f'{i} ERRO: encontrado {count} vezes')
        # Debug: find closest match
        sub_name = [b'DistribuirFrete', b'DistribuirSeguro', b'DistribuirOutros', b'DistribuirDesconto'][i-1]
        idx = data.find(b'Private Sub ' + sub_name)
        end = data.find(b'End Sub', idx) + 7
        print('  Atual no arquivo:')
        print(repr(data[idx:end]))

data = data.replace(b'\r\n', b'\n').replace(b'\r', b'\n').replace(b'\n', b'\r\n')
open('OnlineCommerce/Forms/NFe_Completa.frm', 'wb').write(data)
print('Salvo. Tamanho:', len(data))
