path = r'C:\Projeto\Compartilhado\Forms\Tags_Cadastro.frm'

layout = (
    'VERSION 5.00\r\n'
    'Object = "{5E9E78A0-531B-11CF-91F6-C2863C385E30}#1.0#0"; "msflxgrd.ocx"\r\n'
    'Begin VB.Form Tags_Cadastro \r\n'
    '   Caption         =   "CADASTRO DE TAGS"\r\n'
    '   ClientHeight    =   7200\r\n'
    '   ClientLeft      =   120\r\n'
    '   ClientTop       =   450\r\n'
    '   ClientWidth     =   9600\r\n'
    '   LinkTopic       =   "Form1"\r\n'
    '   ScaleHeight     =   7200\r\n'
    '   ScaleWidth      =   9600\r\n'
    '   StartUpPosition =   2  \'CenterScreen\r\n'
    '   Begin VB.Frame frmFiltros \r\n'
    '      Caption         =   "Filtros"\r\n'
    '      Height          =   855\r\n'
    '      Left            =   120\r\n'
    '      TabIndex        =   0\r\n'
    '      Top             =   120\r\n'
    '      Width           =   9360\r\n'
    '      Begin VB.Label lblFiltroTag \r\n'
    '         Caption         =   "Tag:"\r\n'
    '         Height          =   252\r\n'
    '         Left            =   120\r\n'
    '         TabIndex        =   1\r\n'
    '         Top             =   330\r\n'
    '         Width           =   480\r\n'
    '      End\r\n'
    '      Begin VB.TextBox txtFiltroTag \r\n'
    '         Height          =   315\r\n'
    '         Left            =   660\r\n'
    '         TabIndex        =   2\r\n'
    '         Top             =   300\r\n'
    '         Width           =   1800\r\n'
    '      End\r\n'
    '      Begin VB.Label lblFiltroCategoria \r\n'
    '         Caption         =   "Categoria:"\r\n'
    '         Height          =   252\r\n'
    '         Left            =   2580\r\n'
    '         TabIndex        =   3\r\n'
    '         Top             =   330\r\n'
    '         Width           =   840\r\n'
    '      End\r\n'
    '      Begin VB.ComboBox cboFiltroCategoria \r\n'
    '         Height          =   315\r\n'
    '         Left            =   3480\r\n'
    '         TabIndex        =   4\r\n'
    '         Top             =   300\r\n'
    '         Width           =   2400\r\n'
    '      End\r\n'
    '      Begin VB.CommandButton cmdLocalizar \r\n'
    '         Caption         =   "Localizar"\r\n'
    '         Height          =   375\r\n'
    '         Left            =   6000\r\n'
    '         TabIndex        =   5\r\n'
    '         Top             =   270\r\n'
    '         Width           =   1200\r\n'
    '      End\r\n'
    '      Begin VB.CommandButton cmdLimpar \r\n'
    '         Caption         =   "Limpar"\r\n'
    '         Height          =   375\r\n'
    '         Left            =   7320\r\n'
    '         TabIndex        =   6\r\n'
    '         Top             =   270\r\n'
    '         Width           =   1200\r\n'
    '      End\r\n'
    '   End\r\n'
    '   Begin MSFlexGridLib.MSFlexGrid grdTags \r\n'
    '      Height          =   4200\r\n'
    '      Left            =   120\r\n'
    '      TabIndex        =   7\r\n'
    '      Top             =   1080\r\n'
    '      Width           =   9360\r\n'
    '      _ExtentX        =   16510\r\n'
    '      _ExtentY        =   7408\r\n'
    '      Rows            =   2\r\n'
    '      Cols            =   3\r\n'
    '      FixedRows       =   1\r\n'
    '      FixedCols       =   0\r\n'
    '   End\r\n'
    '   Begin VB.Frame frmDados \r\n'
    '      Caption         =   "Dados"\r\n'
    '      Height          =   1440\r\n'
    '      Left            =   120\r\n'
    '      TabIndex        =   8\r\n'
    '      Top             =   5400\r\n'
    '      Width           =   9360\r\n'
    '      Begin VB.Label lblTag \r\n'
    '         Caption         =   "Tag:"\r\n'
    '         Height          =   252\r\n'
    '         Left            =   120\r\n'
    '         TabIndex        =   9\r\n'
    '         Top             =   300\r\n'
    '         Width           =   480\r\n'
    '      End\r\n'
    '      Begin VB.TextBox txtTag \r\n'
    '         Height          =   315\r\n'
    '         Left            =   660\r\n'
    '         TabIndex        =   10\r\n'
    '         Top             =   270\r\n'
    '         Width           =   2400\r\n'
    '      End\r\n'
    '      Begin VB.Label lblCategoria \r\n'
    '         Caption         =   "Categoria:"\r\n'
    '         Height          =   252\r\n'
    '         Left            =   3180\r\n'
    '         TabIndex        =   11\r\n'
    '         Top             =   300\r\n'
    '         Width           =   840\r\n'
    '      End\r\n'
    '      Begin VB.ComboBox cboCategoria \r\n'
    '         Height          =   315\r\n'
    '         Left            =   4080\r\n'
    '         TabIndex        =   12\r\n'
    '         Top             =   270\r\n'
    '         Width           =   2400\r\n'
    '      End\r\n'
    '      Begin VB.CommandButton cmdNovo \r\n'
    '         Caption         =   "Novo"\r\n'
    '         Height          =   375\r\n'
    '         Left            =   120\r\n'
    '         TabIndex        =   13\r\n'
    '         Top             =   870\r\n'
    '         Width           =   840\r\n'
    '      End\r\n'
    '      Begin VB.CommandButton cmdSalvar \r\n'
    '         Caption         =   "Salvar"\r\n'
    '         Height          =   375\r\n'
    '         Left            =   1080\r\n'
    '         TabIndex        =   14\r\n'
    '         Top             =   870\r\n'
    '         Width           =   840\r\n'
    '      End\r\n'
    '      Begin VB.CommandButton cmdExcluir \r\n'
    '         Caption         =   "Excluir"\r\n'
    '         Height          =   375\r\n'
    '         Left            =   2040\r\n'
    '         TabIndex        =   15\r\n'
    '         Top             =   870\r\n'
    '         Width           =   840\r\n'
    '      End\r\n'
    '   End\r\n'
    'End\r\n'
    'Attribute VB_Name = "Tags_Cadastro"\r\n'
    'Attribute VB_GlobalNameSpace = False\r\n'
    'Attribute VB_Creatable = False\r\n'
    'Attribute VB_PredeclaredId = True\r\n'
    'Attribute VB_Exposed = False\r\n'
)

code = (
    'Option Explicit\r\n'
    '\r\n'
    'Dim vTipo As String\r\n'
    'Dim vIDTags As Long\r\n'
    '\r\n'
    'Private Sub Form_Load()\r\n'
    '   vTipo = "Novo"\r\n'
    '   vIDTags = 0\r\n'
    '   CarregarGrid\r\n'
    'End Sub\r\n'
    '\r\n'
    'Private Sub CarregarGrid()\r\n'
    'Dim r As ADODB.Recordset\r\n'
    'Dim sSQL As String\r\n'
    'Dim sWhere As String\r\n'
    'Dim lRow As Long\r\n'
    '\r\n'
    'sWhere = " WHERE 1=1"\r\n'
    'If Trim(txtFiltroTag.Text) <> "" Then\r\n'
    '   sWhere = sWhere & " AND ct.Tags LIKE \'%" & Replace(Trim(txtFiltroTag.Text), "\'", "\'\'") & "%\'"\r\n'
    'End If\r\n'
    'If Trim(cboFiltroCategoria.Text) <> "" Then\r\n'
    '   sWhere = sWhere & " AND c.Categoria = \'" & Replace(Trim(cboFiltroCategoria.Text), "\'", "\'\'") & "\'"\r\n'
    'End If\r\n'
    '\r\n'
    'sSQL = "SELECT ct.ID_Tags, ct.Tags, c.Categoria FROM Categorias_Tags ct " & _\r\n'
    '       "INNER JOIN Categorias c ON ct.ID_Categoria = c.ID_Categoria" & _\r\n'
    '       sWhere & " ORDER BY c.Categoria, ct.Tags"\r\n'
    '\r\n'
    'With grdTags\r\n'
    '   .Redraw = False\r\n'
    '   .Clear\r\n'
    '   .Cols = 3\r\n'
    '   .Rows = 2\r\n'
    '   .ColWidth(0) = 0\r\n'
    '   .ColWidth(1) = 4200\r\n'
    '   .ColWidth(2) = 4200\r\n'
    '   .FixedRows = 1\r\n'
    '   .FixedCols = 0\r\n'
    '   .TextMatrix(0, 1) = "TAG"\r\n'
    '   .TextMatrix(0, 2) = "CATEGORIA"\r\n'
    '   .Row = 0\r\n'
    '   .Col = 0\r\n'
    '   .ColSel = .Cols - 1\r\n'
    '   .CellFontBold = True\r\n'
    '   .FillStyle = 1\r\n'
    '\r\n'
    '   Set r = dbData.OpenRecordset(sSQL)\r\n'
    '   Do While Not r.EOF\r\n'
    '      .TextMatrix(.Rows - 1, 0) = ValidateNull(r("ID_Tags"))\r\n'
    '      .TextMatrix(.Rows - 1, 1) = ValidateNull(r("Tags"))\r\n'
    '      .TextMatrix(.Rows - 1, 2) = ValidateNull(r("Categoria"))\r\n'
    '      r.MoveNext\r\n'
    '      .Rows = .Rows + 1\r\n'
    '   Loop\r\n'
    '   .Rows = .Rows - 1\r\n'
    '   If r.State <> 0 Then r.Close\r\n'
    '\r\n'
    '   For lRow = 1 To .Rows - 1\r\n'
    '      .Row = lRow\r\n'
    '      .Col = 0\r\n'
    '      .ColSel = .Cols - 1\r\n'
    '      If lRow Mod 2 = 0 Then\r\n'
    '         .CellBackColor = &HE0E0E0\r\n'
    '      Else\r\n'
    '         .CellBackColor = vbWhite\r\n'
    '      End If\r\n'
    '   Next lRow\r\n'
    '   .FillStyle = 0\r\n'
    '   .Redraw = True\r\n'
    'End With\r\n'
    'End Sub\r\n'
    '\r\n'
    'Private Sub cboFiltroCategoria_GotFocus()\r\n'
    'Dim vAnt As String\r\n'
    'vAnt = cboFiltroCategoria.Text\r\n'
    'cboFiltroCategoria.Clear\r\n'
    'Dim r As ADODB.Recordset\r\n'
    'Set r = dbData.OpenRecordset("SELECT Categoria FROM Categorias WHERE Tipo_Empresa = " & tipoEmpresa & " ORDER BY Categoria")\r\n'
    'Do While Not r.EOF\r\n'
    '   cboFiltroCategoria.AddItem ValidateNull(r("Categoria"))\r\n'
    '   r.MoveNext\r\n'
    'Loop\r\n'
    'If r.State <> 0 Then r.Close\r\n'
    'cboFiltroCategoria.Text = vAnt\r\n'
    'End Sub\r\n'
    '\r\n'
    'Private Sub cmdLocalizar_Click()\r\n'
    '   CarregarGrid\r\n'
    'End Sub\r\n'
    '\r\n'
    'Private Sub cmdLimpar_Click()\r\n'
    '   txtFiltroTag.Text = ""\r\n'
    '   cboFiltroCategoria.Text = ""\r\n'
    '   CarregarGrid\r\n'
    'End Sub\r\n'
    '\r\n'
    'Private Sub grdTags_Click()\r\n'
    '   If grdTags.Row < 1 Then Exit Sub\r\n'
    '   vIDTags = CLng(grdTags.TextMatrix(grdTags.Row, 0))\r\n'
    '   txtTag.Text = grdTags.TextMatrix(grdTags.Row, 1)\r\n'
    '   cboCategoria.Text = grdTags.TextMatrix(grdTags.Row, 2)\r\n'
    '   vTipo = "Edicao"\r\n'
    'End Sub\r\n'
    '\r\n'
    'Private Sub cboCategoria_GotFocus()\r\n'
    'Dim vAnt As String\r\n'
    'vAnt = cboCategoria.Text\r\n'
    'cboCategoria.Clear\r\n'
    'Dim r As ADODB.Recordset\r\n'
    'Set r = dbData.OpenRecordset("SELECT Categoria FROM Categorias WHERE Tipo_Empresa = " & tipoEmpresa & " ORDER BY Categoria")\r\n'
    'Do While Not r.EOF\r\n'
    '   cboCategoria.AddItem ValidateNull(r("Categoria"))\r\n'
    '   r.MoveNext\r\n'
    'Loop\r\n'
    'If r.State <> 0 Then r.Close\r\n'
    'cboCategoria.Text = vAnt\r\n'
    'End Sub\r\n'
    '\r\n'
    'Private Sub cmdNovo_Click()\r\n'
    '   vTipo = "Novo"\r\n'
    '   vIDTags = 0\r\n'
    '   txtTag.Text = ""\r\n'
    '   cboCategoria.Text = ""\r\n'
    '   txtTag.SetFocus\r\n'
    'End Sub\r\n'
    '\r\n'
    'Private Sub cmdSalvar_Click()\r\n'
    'Dim r As ADODB.Recordset\r\n'
    'Dim lCatID As Long\r\n'
    '\r\n'
    'If Trim(txtTag.Text) = "" Then\r\n'
    '   MsgBox "Digite o nome da Tag.", vbInformation, "Aviso"\r\n'
    '   txtTag.SetFocus\r\n'
    '   Exit Sub\r\n'
    'End If\r\n'
    'If Trim(cboCategoria.Text) = "" Then\r\n'
    '   MsgBox "Selecione a Categoria.", vbInformation, "Aviso"\r\n'
    '   cboCategoria.SetFocus\r\n'
    '   Exit Sub\r\n'
    'End If\r\n'
    '\r\n'
    'Set r = dbData.OpenRecordset("SELECT ID_Categoria FROM Categorias WHERE Categoria = \'" & Replace(cboCategoria.Text, "\'", "\'\'") & "\'")\r\n'
    'If Not r.EOF Then lCatID = CLng(r("ID_Categoria"))\r\n'
    'If r.State <> 0 Then r.Close\r\n'
    '\r\n'
    'If lCatID = 0 Then\r\n'
    '   MsgBox "Categoria n\xe3o encontrada.", vbInformation, "Aviso"\r\n'
    '   Exit Sub\r\n'
    'End If\r\n'
    '\r\n'
    'If vTipo = "Novo" Then\r\n'
    '   dbData.Execute "INSERT INTO Categorias_Tags (Tags, ID_Categoria) VALUES (\'" & Replace(Trim(txtTag.Text), "\'", "\'\'") & "\', " & lCatID & ");"\r\n'
    'Else\r\n'
    '   dbData.Execute "UPDATE Categorias_Tags SET Tags = \'" & Replace(Trim(txtTag.Text), "\'", "\'\'") & "\', ID_Categoria = " & lCatID & " WHERE ID_Tags = " & vIDTags & ";"\r\n'
    'End If\r\n'
    '\r\n'
    'cmdNovo_Click\r\n'
    'CarregarGrid\r\n'
    'End Sub\r\n'
    '\r\n'
    'Private Sub cmdExcluir_Click()\r\n'
    '   If vIDTags = 0 Then Exit Sub\r\n'
    '   If MsgBox("Excluir a tag \'" & txtTag.Text & "\'?", vbQuestion + vbYesNo, "Confirmar") = vbNo Then Exit Sub\r\n'
    '   dbData.Execute "DELETE FROM Categorias_Tags WHERE ID_Tags = " & vIDTags & ";"\r\n'
    '   cmdNovo_Click\r\n'
    '   CarregarGrid\r\n'
    'End Sub\r\n'
)

content = layout + code
with open(path, 'wb') as f:
    f.write(content.encode('windows-1252'))
print('Tags_Cadastro.frm gerado.')
