data = open(r'C:\Projeto\OnlineCommerce\Forms\NFe_Completa.frm', 'rb').read()
text = data.decode('windows-1252')

# ── Patch 1: substituir cmdConverterNFe_Click ────────────────────────────────
old1 = (
    'Private Sub cmdConverterNFe_Click()\r\n'
    'If vTipoEdicaoNFe = "Novo" Or vTipoEdicaoNFe = "Edicao" Then MsgBox "Existe uma NFe em aberto, salve ou cancele antes!", vbExclamation, "Online Commerce": Frm_NF.Tab = 0: Exit Sub\r\n'
    '\r\n'
    'Dim nMarcados As Integer, i As Integer\r\n'
    'For i = 1 To GridPedidos.rows - 1\r\n'
    '    If GridPedidos.RowData(i) = 1 And GridPedidos.TextMatrix(i, 2) <> "SIM" Then\r\n'
    '        nMarcados = nMarcados + 1\r\n'
    '    End If\r\n'
    'Next i\r\n'
    '\r\n'
    'If nMarcados = 0 Then MsgBox "Marque ao menos um pedido ainda n\xe3o convertido.", vbInformation, "Online Commerce": Exit Sub\r\n'
    'If ShowMsg("Deseja converter " & nMarcados & " pedido(s) em Nota Fiscal?", vbYesNo + vbQuestion + vbDefaultButton2) = vbNo Then Exit Sub\r\n'
    '\r\n'
    'picAguarde2.Visible = True\r\n'
    '\r\n'
    'For i = 1 To GridPedidos.rows - 1\r\n'
    '    If GridPedidos.RowData(i) = 1 And GridPedidos.TextMatrix(i, 2) <> "SIM" Then\r\n'
    '        txtCodPedido.Text = GridPedidos.TextMatrix(i, 1)\r\n'
    '        vTipoEdicaoNFe = "Edicao"\r\n'
    '        GravarPedido\r\n'
    '        AtualizarTotaisNota\r\n'
    '        Dim sInfAdd As String\r\n'
    '        sInfAdd = Trim(txtInfComple.Text)\r\n'
    '        If Len(sInfAdd) > 0 Then\r\n'
    '            sInfAdd = sInfAdd & " / PEDIDO: " & Format(CLng(txtCodPedido.Text), "0000")\r\n'
    '        Else\r\n'
    '            sInfAdd = "PEDIDO: " & Format(CLng(txtCodPedido.Text), "0000")\r\n'
    '        End If\r\n'
    "        SQLExecuta \"UPDATE NotaFiscal SET InformacoesAdicionais = '\" & Replace(sInfAdd, \"'\" , \"''\") & \"' WHERE CodigoNota = \" & Val(txtCodNota.Text)\r\n"
    '        txtInfComple.Text = sInfAdd\r\n'
    '    End If\r\n'
    'Next i\r\n'
    '\r\n'
    'picAguarde2.Visible = False\r\n'
    '\r\n'
    'cmdExibirPedidos_Click\r\n'
    '\r\n'
    'If nMarcados = 1 Then\r\n'
    '    cmdNovo.Enabled = False\r\n'
    '    cmdSalvar.Enabled = True\r\n'
    '    cmdCancelar.Enabled = True\r\n'
    '    frmNota.Enabled = True\r\n'
    '    frmDestinatario.Enabled = True\r\n'
    '    frmItens.Enabled = True\r\n'
    '    Tab_Totais.Enabled = True\r\n'
    '    Tab_Produtos.Enabled = True\r\n'
    '    cmdRecalcular_Click\r\n'
    '    Frm_NF.Tab = 0\r\n'
    'Else\r\n'
    '    vTipoEdicaoNFe = ""\r\n'
    '    cmdNovo.Enabled = True\r\n'
    '    cmdSalvar.Enabled = False\r\n'
    '    cmdCancelar.Enabled = False\r\n'
    '    frmNota.Enabled = False\r\n'
    '    frmDestinatario.Enabled = False\r\n'
    '    frmItens.Enabled = False\r\n'
    '    Tab_Totais.Enabled = False\r\n'
    '    Tab_Produtos.Enabled = False\r\n'
    'End If\r\n'
    'End Sub'
)

new1 = (
    'Private Sub cmdConverterNFe_Click()\r\n'
    'If vTipoEdicaoNFe = "Novo" Or vTipoEdicaoNFe = "Edicao" Then MsgBox "Existe uma NFe em aberto, salve ou cancele antes!", vbExclamation, "Online Commerce": Frm_NF.Tab = 0: Exit Sub\r\n'
    '\r\n'
    'Dim nMarcados As Integer, i As Integer\r\n'
    'For i = 1 To GridPedidos.rows - 1\r\n'
    '    If GridPedidos.RowData(i) = 1 And GridPedidos.TextMatrix(i, 2) <> "SIM" Then\r\n'
    '        nMarcados = nMarcados + 1\r\n'
    '    End If\r\n'
    'Next i\r\n'
    '\r\n'
    'If nMarcados = 0 Then MsgBox "Marque ao menos um pedido ainda n\xe3o convertido.", vbInformation, "Online Commerce": Exit Sub\r\n'
    '\r\n'
    'Dim bUnirEmUmaNota As Boolean\r\n'
    'bUnirEmUmaNota = False\r\n'
    '\r\n'
    'If nMarcados = 1 Then\r\n'
    '    If ShowMsg("Deseja converter 1 pedido em Nota Fiscal?", vbYesNo + vbQuestion + vbDefaultButton2) = vbNo Then Exit Sub\r\n'
    'Else\r\n'
    '    Dim iMode As Integer\r\n'
    '    iMode = MsgBox("Converter " & nMarcados & " pedidos:" & vbCrLf & vbCrLf & _\r\n'
    '        "SIM = Uma NF por pedido" & vbCrLf & _\r\n'
    '        "N\xc3O = Todos em uma \xfanica NF" & vbCrLf & _\r\n'
    '        "CANCELAR = N\xe3o converter", _\r\n'
    '        vbYesNoCancel + vbQuestion, "Online Commerce")\r\n'
    '    If iMode = vbCancel Then Exit Sub\r\n'
    '    bUnirEmUmaNota = (iMode = vbNo)\r\n'
    'End If\r\n'
    '\r\n'
    'picAguarde2.Visible = True\r\n'
    '\r\n'
    'If bUnirEmUmaNota Then\r\n'
    '    Dim bPrimeiro As Boolean\r\n'
    '    Dim sPedidosLista As String\r\n'
    '    Dim sInfAdd As String\r\n'
    '    bPrimeiro = True\r\n'
    '    sPedidosLista = ""\r\n'
    '    For i = 1 To GridPedidos.rows - 1\r\n'
    '        If GridPedidos.RowData(i) = 1 And GridPedidos.TextMatrix(i, 2) <> "SIM" Then\r\n'
    '            txtCodPedido.Text = GridPedidos.TextMatrix(i, 1)\r\n'
    '            If bPrimeiro Then\r\n'
    '                vTipoEdicaoNFe = "Edicao"\r\n'
    '                GravarPedido\r\n'
    '                bPrimeiro = False\r\n'
    '                sPedidosLista = Format(CLng(txtCodPedido.Text), "0000")\r\n'
    '            Else\r\n'
    '                AdicionarPedidoNaNota\r\n'
    '                sPedidosLista = sPedidosLista & ", " & Format(CLng(txtCodPedido.Text), "0000")\r\n'
    '            End If\r\n'
    '        End If\r\n'
    '    Next i\r\n'
    '    AtualizarTotaisNota\r\n'
    '    sInfAdd = Trim(txtInfComple.Text)\r\n'
    '    If Len(sInfAdd) > 0 Then\r\n'
    '        sInfAdd = sInfAdd & " / PEDIDO: " & sPedidosLista\r\n'
    '    Else\r\n'
    '        sInfAdd = "PEDIDO: " & sPedidosLista\r\n'
    '    End If\r\n'
    "    SQLExecuta \"UPDATE NotaFiscal SET InformacoesAdicionais = '\" & Replace(sInfAdd, \"'\" , \"''\") & \"' WHERE CodigoNota = \" & Val(txtCodNota.Text)\r\n"
    '    txtInfComple.Text = sInfAdd\r\n'
    'Else\r\n'
    '    Dim sInfAdd2 As String\r\n'
    '    For i = 1 To GridPedidos.rows - 1\r\n'
    '        If GridPedidos.RowData(i) = 1 And GridPedidos.TextMatrix(i, 2) <> "SIM" Then\r\n'
    '            txtCodPedido.Text = GridPedidos.TextMatrix(i, 1)\r\n'
    '            vTipoEdicaoNFe = "Edicao"\r\n'
    '            GravarPedido\r\n'
    '            AtualizarTotaisNota\r\n'
    '            sInfAdd2 = Trim(txtInfComple.Text)\r\n'
    '            If Len(sInfAdd2) > 0 Then\r\n'
    '                sInfAdd2 = sInfAdd2 & " / PEDIDO: " & Format(CLng(txtCodPedido.Text), "0000")\r\n'
    '            Else\r\n'
    '                sInfAdd2 = "PEDIDO: " & Format(CLng(txtCodPedido.Text), "0000")\r\n'
    '            End If\r\n'
    "            SQLExecuta \"UPDATE NotaFiscal SET InformacoesAdicionais = '\" & Replace(sInfAdd2, \"'\" , \"''\") & \"' WHERE CodigoNota = \" & Val(txtCodNota.Text)\r\n"
    '            txtInfComple.Text = sInfAdd2\r\n'
    '        End If\r\n'
    '    Next i\r\n'
    'End If\r\n'
    '\r\n'
    'picAguarde2.Visible = False\r\n'
    'cmdExibirPedidos_Click\r\n'
    '\r\n'
    'If nMarcados = 1 Or bUnirEmUmaNota Then\r\n'
    '    cmdNovo.Enabled = False\r\n'
    '    cmdSalvar.Enabled = True\r\n'
    '    cmdCancelar.Enabled = True\r\n'
    '    frmNota.Enabled = True\r\n'
    '    frmDestinatario.Enabled = True\r\n'
    '    frmItens.Enabled = True\r\n'
    '    Tab_Totais.Enabled = True\r\n'
    '    Tab_Produtos.Enabled = True\r\n'
    '    cmdRecalcular_Click\r\n'
    '    Frm_NF.Tab = 0\r\n'
    'Else\r\n'
    '    vTipoEdicaoNFe = ""\r\n'
    '    cmdNovo.Enabled = True\r\n'
    '    cmdSalvar.Enabled = False\r\n'
    '    cmdCancelar.Enabled = False\r\n'
    '    frmNota.Enabled = False\r\n'
    '    frmDestinatario.Enabled = False\r\n'
    '    frmItens.Enabled = False\r\n'
    '    Tab_Totais.Enabled = False\r\n'
    '    Tab_Produtos.Enabled = False\r\n'
    'End If\r\n'
    'End Sub'
)

# ── Patch 2: inserir AdicionarPedidoNaNota antes de GravarPedido ─────────────
old2 = 'Private Sub GravarPedido()\r\n'

new2 = (
    'Private Sub AdicionarPedidoNaNota()\r\n'
    'Dim VarCodNota As Integer\r\n'
    'VarCodNota = CInt(txtCodNota.Text)\r\n'
    '\r\n'
    'Dim sSQL2 As String\r\n'
    'sSQL2 = "INSERT INTO NotaFiscalItens ( " & _\r\n'
    '    "CodigoProduto, EAN, NomeProduto, CFOP, NCM, CST, " & _\r\n'
    '    "UnidadeComercial, ValorUnitarioComercializacao, ValorTotalBruto, " & _\r\n'
    '    "tipodesconto, desconto, Valordesconto, QuantidadeComercial, " & _\r\n'
    '    "pICMS, vBC, vICMS, item, CodigoNota, TipoProduto, Cod_Pedido, Item_pedido " & _\r\n'
    '    ") " & _\r\n'
    '    "SELECT pi.cod_produto, p.EAN, p.descricao, p.cfop, p.ncm, p.icmscst, " & _\r\n'
    '    "p.unid_medida, pi.preco, pi.Subtotal, 1, pi.desconto, pi.desconto, " & _\r\n'
    '    "pi.quantidade, 0, pi.Subtotal, 0, " & _\r\n'
    '    "(SELECT ISNULL(MAX(item), 0) FROM NotaFiscalItens WHERE CodigoNota = " & VarCodNota & ") + pi.item, " & _\r\n'
    '    VarCodNota & ", " & _\r\n'
    "    \"(CASE p.combustivel WHEN 1 THEN 'Combust\xedvel' ELSE '' END), \" & _\r\n"
    '    txtCodPedido.Text & ", pi.item " & _\r\n'
    '    "FROM produtos p " & _\r\n'
    '    "INNER JOIN pedidos_itens pi ON p.codigo = pi.cod_produto " & _\r\n'
    '    "INNER JOIN pedidos ped ON pi.cod_pedido = ped.cod_pedido " & _\r\n'
    '    "WHERE pi.COD_PEDIDO = " & txtCodPedido.Text\r\n'
    'dbData.Execute sSQL2\r\n'
    '\r\n'
    'Exibir_Itens\r\n'
    'End Sub\r\n'
    '\r\n'
    'Private Sub GravarPedido()\r\n'
)

c1 = text.count(old1)
c2 = text.count(old2)
print(f'Patch1: {c1}  Patch2: {c2}')

if c1 == 1 and c2 == 1:
    text = text.replace(old1, new1)
    text = text.replace(old2, new2)
    out = text.encode('windows-1252')
    out = out.replace(b'\r\n', b'\n').replace(b'\r', b'\n').replace(b'\n', b'\r\n')
    open(r'C:\Projeto\OnlineCommerce\Forms\NFe_Completa.frm', 'wb').write(out)
    print('OK')
else:
    print('ABORTADO')
