data = open(r'C:\Projeto\OnlineCommerce\Forms\NFe_Completa.frm', 'rb').read()
text = data.decode('windows-1252')

# ── Patch 1: cboIndicePedidos_GotFocus – adicionar CLIENTE+DATAS e CLIENTE+MENSAL ──
old1 = (
    'cboIndicePedidos.AddItem "PEDIDO"\r\n'
    'cboIndicePedidos.AddItem "CLIENTE"\r\n'
    'cboIndicePedidos.AddItem "DATAS"\r\n'
    'cboIndicePedidos.AddItem "MENSAL"'
)
new1 = (
    'cboIndicePedidos.AddItem "PEDIDO"\r\n'
    'cboIndicePedidos.AddItem "CLIENTE"\r\n'
    'cboIndicePedidos.AddItem "DATAS"\r\n'
    'cboIndicePedidos.AddItem "MENSAL"\r\n'
    'cboIndicePedidos.AddItem "CLIENTE + DATAS"\r\n'
    'cboIndicePedidos.AddItem "CLIENTE + MENSAL"'
)

# ── Patch 2: cboIndicePedidos_Click – reescrita completa ──
old2 = (
    'Sub cboIndicePedidos_Click()\r\n'
    'lblInicialPedidos.Visible = False\r\n'
    'mskInicialPedidos.Visible = False\r\n'
    'cmdCalPedidos1.Visible = False\r\n'
    'lblFinalPedidos.Visible = False\r\n'
    'mskFinalPedidos.Visible = False\r\n'
    'cmdCalPedidos2.Visible = False\r\n'
    'lblClientePedidos.Visible = False\r\n'
    'cboClientePedidos.Visible = False\r\n'
    'lblConsCodPedido.Visible = False\r\n'
    'txtConCodPedido.Visible = False\r\n'
    'lblMesPedidos.Visible = False\r\n'
    'cboMesPedidos.Visible = False\r\n'
    'lblAnoPedidos.Visible = False\r\n'
    'cboAnoPedidos.Visible = False\r\n'
    '\r\n'
    'If cboIndicePedidos.Text = "PEDIDO" Then\r\n'
    '    lblConsCodPedido.Visible = True\r\n'
    '    txtConCodPedido.Visible = True\r\n'
    'ElseIf cboIndicePedidos.Text = "CLIENTE" Then\r\n'
    '    lblClientePedidos.Visible = True\r\n'
    '    cboClientePedidos.Visible = True\r\n'
    'ElseIf cboIndicePedidos.Text = "DATAS" Then\r\n'
    '    lblInicialPedidos.Visible = True\r\n'
    '    mskInicialPedidos.Visible = True\r\n'
    '    cmdCalPedidos1.Visible = True\r\n'
    '    lblFinalPedidos.Visible = True\r\n'
    '    mskFinalPedidos.Visible = True\r\n'
    '    cmdCalPedidos2.Visible = True\r\n'
    'ElseIf cboIndicePedidos.Text = "MENSAL" Then\r\n'
    '    lblMesPedidos.Visible = True\r\n'
    '    cboMesPedidos.Visible = True\r\n'
    '    lblAnoPedidos.Visible = True\r\n'
    '    cboAnoPedidos.Visible = True\r\n'
    'Else\r\n'
    'End If\r\n'
    'End Sub'
)
new2 = (
    'Sub cboIndicePedidos_Click()\r\n'
    '\'Oculta tudo\r\n'
    'lblConsCodPedido.Visible = False\r\n'
    'txtConCodPedido.Visible = False\r\n'
    'txtCodClientePedidos.Visible = False\r\n'
    'mskInicialPedidos.Visible = False\r\n'
    'mskFinalPedidos.Visible = False\r\n'
    'cmdCalPedidos1.Visible = False\r\n'
    'cmdCalPedidos2.Visible = False\r\n'
    'lblInicialPedidos.Visible = False\r\n'
    'lblFinalPedidos.Visible = False\r\n'
    'lblClientePedidos.Visible = False\r\n'
    'cboClientePedidos.Visible = False\r\n'
    'lblMesPedidos.Visible = False\r\n'
    'cboMesPedidos.Visible = False\r\n'
    'lblAnoPedidos.Visible = False\r\n'
    'cboAnoPedidos.Visible = False\r\n'
    '\'Reposiciona controles de data para posi\xe7\xe3o simples\r\n'
    'lblMesPedidos.Left = 120\r\n'
    'cboMesPedidos.Left = 540: cboMesPedidos.Width = 1335\r\n'
    'lblAnoPedidos.Left = 1980\r\n'
    'cboAnoPedidos.Left = 2340: cboAnoPedidos.Width = 1155\r\n'
    'cboClientePedidos.Width = 3885\r\n'
    '\r\n'
    'Select Case cboIndicePedidos.Text\r\n'
    '    Case "PEDIDO"\r\n'
    '        lblClientePedidos.Caption = "C\xf3d. Pedido:"\r\n'
    '        cboClientePedidos.Clear\r\n'
    '        lblClientePedidos.Visible = True\r\n'
    '        cboClientePedidos.Visible = True\r\n'
    '\r\n'
    '    Case "CLIENTE"\r\n'
    '        lblClientePedidos.Caption = "Cliente:"\r\n'
    '        lblClientePedidos.Visible = True\r\n'
    '        cboClientePedidos.Visible = True\r\n'
    '\r\n'
    '    Case "DATAS"\r\n'
    '        lblMesPedidos.Caption = "Inicial:"\r\n'
    '        lblAnoPedidos.Caption = "Final:"\r\n'
    '        cboMesPedidos.Clear\r\n'
    '        cboAnoPedidos.Clear\r\n'
    '        lblMesPedidos.Visible = True\r\n'
    '        cboMesPedidos.Visible = True\r\n'
    '        lblAnoPedidos.Visible = True\r\n'
    '        cboAnoPedidos.Visible = True\r\n'
    '\r\n'
    '    Case "MENSAL"\r\n'
    '        lblMesPedidos.Caption = "M\xeas:"\r\n'
    '        lblAnoPedidos.Caption = "Ano:"\r\n'
    '        lblMesPedidos.Visible = True\r\n'
    '        cboMesPedidos.Visible = True\r\n'
    '        lblAnoPedidos.Visible = True\r\n'
    '        cboAnoPedidos.Visible = True\r\n'
    '\r\n'
    '    Case "CLIENTE + DATAS"\r\n'
    '        lblClientePedidos.Caption = "Cliente:"\r\n'
    '        cboClientePedidos.Width = 1500\r\n'
    '        lblMesPedidos.Caption = "Inicial:"\r\n'
    '        lblMesPedidos.Left = 2340\r\n'
    '        cboMesPedidos.Left = 2640: cboMesPedidos.Width = 900\r\n'
    '        lblAnoPedidos.Caption = "Final:"\r\n'
    '        lblAnoPedidos.Left = 3600\r\n'
    '        cboAnoPedidos.Left = 3960: cboAnoPedidos.Width = 1200\r\n'
    '        cboMesPedidos.Clear\r\n'
    '        cboAnoPedidos.Clear\r\n'
    '        lblClientePedidos.Visible = True\r\n'
    '        cboClientePedidos.Visible = True\r\n'
    '        lblMesPedidos.Visible = True\r\n'
    '        cboMesPedidos.Visible = True\r\n'
    '        lblAnoPedidos.Visible = True\r\n'
    '        cboAnoPedidos.Visible = True\r\n'
    '\r\n'
    '    Case "CLIENTE + MENSAL"\r\n'
    '        lblClientePedidos.Caption = "Cliente:"\r\n'
    '        cboClientePedidos.Width = 1500\r\n'
    '        lblMesPedidos.Caption = "M\xeas:"\r\n'
    '        lblMesPedidos.Left = 2340\r\n'
    '        cboMesPedidos.Left = 2640: cboMesPedidos.Width = 900\r\n'
    '        lblAnoPedidos.Caption = "Ano:"\r\n'
    '        lblAnoPedidos.Left = 3600\r\n'
    '        cboAnoPedidos.Left = 3960: cboAnoPedidos.Width = 1200\r\n'
    '        lblClientePedidos.Visible = True\r\n'
    '        cboClientePedidos.Visible = True\r\n'
    '        lblMesPedidos.Visible = True\r\n'
    '        cboMesPedidos.Visible = True\r\n'
    '        lblAnoPedidos.Visible = True\r\n'
    '        cboAnoPedidos.Visible = True\r\n'
    '\r\n'
    'End Select\r\n'
    'End Sub'
)

# ── Patch 3: cmdExibirPedidos_Click – reescrita completa ──
old3 = (
    'Sub cmdExibirPedidos_Click()\r\n'
    'If cboIndicePedidos.Text = "" Then Exit Sub\r\n'
    '\r\n'
    'Dim r As ADODB.Recordset\r\n'
    'Dim totalRegistros As Long\r\n'
    '   \r\n'
    'If cboIndicePedidos.Text = "PEDIDO" Then\r\n'
    '    If txtConCodPedido.Text = "" Then Exit Sub\r\n'
    '    sSQL = "SELECT cliente.codigo, pedidos.cod_cliente, cliente.nome as var_Nome, pedidos.tipo_pagamento AS var_tipoPGTO, pedidos.cod_pedido AS var_codped, pedidos.data_compra as var_DTCompra, pedidos.total AS var_total, (CASE WHEN NotaFiscal.cod_pedido = pedidos.cod_pedido THEN \'SIM\' ELSE \'N\xc3O\' END) AS Status " & _\r\n'
    '           "FROM cliente INNER JOIN pedidos ON cliente.codigo = pedidos.cod_cliente LEFT JOIN NotaFiscal ON NotaFiscal.cod_pedido = pedidos.cod_pedido WHERE pedidos.cod_pedido = " & txtConCodPedido & " AND (TIPO_PEDIDO <> \'OR\xc7AMENTO\') ;"\r\n'
    'ElseIf cboIndicePedidos.Text = "CLIENTE" Then\r\n'
    '    If txtCodClientePedidos.Text = "" Then Exit Sub\r\n'
    '    sSQL = "SELECT cliente.codigo, pedidos.cod_cliente, cliente.nome as var_Nome, pedidos.tipo_pagamento AS var_tipoPGTO, pedidos.cod_pedido AS var_codped, pedidos.data_compra as var_DTCompra, pedidos.total AS var_total, (CASE WHEN NotaFiscal.cod_pedido = pedidos.cod_pedido THEN \'SIM\' ELSE \'N\xc3O\' END) AS Status " & _\r\n'
    '           "FROM cliente INNER JOIN pedidos ON cliente.codigo = pedidos.cod_cliente LEFT JOIN NotaFiscal ON NotaFiscal.cod_pedido = pedidos.cod_pedido WHERE (cliente.codigo = " & txtCodClientePedidos.Text & ") AND (TIPO_PEDIDO <> \'OR\xc7AMENTO\') ORDER BY pedidos.cod_pedido;"\r\n'
    'ElseIf cboIndicePedidos.Text = "DATAS" Then\r\n'
    '    If IsDate(mskInicialPedidos) = False Or IsDate(mskFinalPedidos) = False Then Exit Sub\r\n'
    '    sSQL = "SELECT cliente.codigo, pedidos.cod_cliente, cliente.nome as var_Nome, pedidos.tipo_pagamento AS var_tipoPGTO, pedidos.cod_pedido AS var_codped, pedidos.data_compra as var_DTCompra, pedidos.total AS var_total, (CASE WHEN NotaFiscal.cod_pedido = pedidos.cod_pedido THEN \'SIM\' ELSE \'N\xc3O\' END) AS Status " & _\r\n'
    '           "FROM cliente INNER JOIN pedidos ON cliente.codigo = pedidos.cod_cliente LEFT JOIN NotaFiscal ON NotaFiscal.cod_pedido = pedidos.cod_pedido WHERE (pedidos.data_compra >= CONVERT(DATETIME, \'" & Format(mskInicialPedidos.Text, ocDATA) & "\', 103)) AND (pedidos.data_compra <= CONVERT(DATETIME, \'" & Format(mskFinalPedidos.Text, ocDATA) & "\', 103)) AND (TIPO_PEDIDO <> \'OR\xc7AMENTO\') ORDER BY pedidos.cod_pedido;"\r\n'
    'ElseIf cboIndicePedidos.Text = "MENSAL" Then\r\n'
    '    If cboMesPedidos.Text = "" Or cboAnoPedidos.Text = "" Then Exit Sub \'var_tipoPGTO\r\n'
    '    sSQL = "SELECT cliente.codigo, pedidos.cod_cliente, cliente.nome as var_Nome, pedidos.tipo_pagamento AS var_tipoPGTO, pedidos.cod_pedido AS var_codped, pedidos.data_compra as var_DTCompra, pedidos.total AS var_total, (CASE WHEN NotaFiscal.cod_pedido = pedidos.cod_pedido THEN \'SIM\' ELSE \'N\xc3O\' END) AS Status " & _\r\n'
    '           "FROM cliente INNER JOIN pedidos ON cliente.codigo = pedidos.cod_cliente LEFT JOIN NotaFiscal ON NotaFiscal.cod_pedido = pedidos.cod_pedido WHERE (MONTH(pedidos.data_compra) = " & cboMesPedidos.ListIndex + 1 & ") AND (YEAR(pedidos.data_compra) = " & cboAnoPedidos & ") ORDER BY pedidos.cod_pedido;"\r\n'
    'Else\r\n'
    '    sSQL = "SELECT cliente.codigo, pedidos.cod_cliente, cliente.nome as var_Nome, pedidos.tipo_pagamento AS var_tipoPGTO, pedidos.cod_pedido AS var_codped, pedidos.data_compra as var_DTCompra, pedidos.total AS var_total, (CASE WHEN NotaFiscal.cod_pedido = pedidos.cod_pedido THEN \'SIM\' ELSE \'N\xc3O\' END) AS Status " & _\r\n'
    '           "FROM cliente INNER JOIN pedidos ON cliente.codigo = pedidos.cod_cliente LEFT JOIN NotaFiscal ON NotaFiscal.cod_pedido = pedidos.cod_pedido WHERE pedidos.cod_pedido = \'0\';"\r\n'
    'End If'
)

# Shared SQL fragment helper
sSQL_base = (
    '"SELECT cliente.codigo, pedidos.cod_cliente, cliente.nome as var_Nome, '
    'pedidos.tipo_pagamento AS var_tipoPGTO, pedidos.cod_pedido AS var_codped, '
    'pedidos.data_compra as var_DTCompra, pedidos.total AS var_total, '
    '(CASE WHEN NotaFiscal.cod_pedido = pedidos.cod_pedido THEN \'SIM\' ELSE \'N\xc3O\' END) AS Status " & _\r\n'
    '           "FROM cliente INNER JOIN pedidos ON cliente.codigo = pedidos.cod_cliente '
    'LEFT JOIN NotaFiscal ON NotaFiscal.cod_pedido = pedidos.cod_pedido WHERE '
)

new3 = (
    'Sub cmdExibirPedidos_Click()\r\n'
    'If cboIndicePedidos.Text = "" Then Exit Sub\r\n'
    '\r\n'
    'Dim r As ADODB.Recordset\r\n'
    'Dim totalRegistros As Long\r\n'
    '\r\n'
    'Select Case cboIndicePedidos.Text\r\n'
    '\r\n'
    '    Case "PEDIDO"\r\n'
    '        If cboClientePedidos.Text = "" Then Exit Sub\r\n'
    '        sSQL = "SELECT cliente.codigo, pedidos.cod_cliente, cliente.nome as var_Nome, pedidos.tipo_pagamento AS var_tipoPGTO, pedidos.cod_pedido AS var_codped, pedidos.data_compra as var_DTCompra, pedidos.total AS var_total, (CASE WHEN NotaFiscal.cod_pedido = pedidos.cod_pedido THEN \'SIM\' ELSE \'N\xc3O\' END) AS Status " & _\r\n'
    '               "FROM cliente INNER JOIN pedidos ON cliente.codigo = pedidos.cod_cliente LEFT JOIN NotaFiscal ON NotaFiscal.cod_pedido = pedidos.cod_pedido " & _\r\n'
    '               "WHERE pedidos.cod_pedido = " & Val(cboClientePedidos.Text) & " AND (TIPO_PEDIDO <> \'OR\xc7AMENTO\');"\r\n'
    '\r\n'
    '    Case "CLIENTE"\r\n'
    '        If cboClientePedidos.Text = "" Then Exit Sub\r\n'
    '        sSQL = "SELECT cliente.codigo, pedidos.cod_cliente, cliente.nome as var_Nome, pedidos.tipo_pagamento AS var_tipoPGTO, pedidos.cod_pedido AS var_codped, pedidos.data_compra as var_DTCompra, pedidos.total AS var_total, (CASE WHEN NotaFiscal.cod_pedido = pedidos.cod_pedido THEN \'SIM\' ELSE \'N\xc3O\' END) AS Status " & _\r\n'
    '               "FROM cliente INNER JOIN pedidos ON cliente.codigo = pedidos.cod_cliente LEFT JOIN NotaFiscal ON NotaFiscal.cod_pedido = pedidos.cod_pedido " & _\r\n'
    '               "WHERE cliente.codigo = " & Val(cboClientePedidos.Text) & " AND (TIPO_PEDIDO <> \'OR\xc7AMENTO\') ORDER BY pedidos.cod_pedido;"\r\n'
    '\r\n'
    '    Case "DATAS"\r\n'
    '        If Not IsDate(cboMesPedidos.Text) Or Not IsDate(cboAnoPedidos.Text) Then\r\n'
    '            MsgBox "Informe datas v\xe1lidas nos campos Inicial e Final.", vbInformation, "Online Commerce"\r\n'
    '            Exit Sub\r\n'
    '        End If\r\n'
    '        sSQL = "SELECT cliente.codigo, pedidos.cod_cliente, cliente.nome as var_Nome, pedidos.tipo_pagamento AS var_tipoPGTO, pedidos.cod_pedido AS var_codped, pedidos.data_compra as var_DTCompra, pedidos.total AS var_total, (CASE WHEN NotaFiscal.cod_pedido = pedidos.cod_pedido THEN \'SIM\' ELSE \'N\xc3O\' END) AS Status " & _\r\n'
    '               "FROM cliente INNER JOIN pedidos ON cliente.codigo = pedidos.cod_cliente LEFT JOIN NotaFiscal ON NotaFiscal.cod_pedido = pedidos.cod_pedido " & _\r\n'
    '               "WHERE (pedidos.data_compra >= CONVERT(DATETIME,\'" & Format(CDate(cboMesPedidos.Text), ocDATA) & "\',103)) " & _\r\n'
    '               "AND (pedidos.data_compra <= CONVERT(DATETIME,\'" & Format(CDate(cboAnoPedidos.Text), ocDATA) & "\',103)) " & _\r\n'
    '               "AND (TIPO_PEDIDO <> \'OR\xc7AMENTO\') ORDER BY pedidos.cod_pedido;"\r\n'
    '\r\n'
    '    Case "MENSAL"\r\n'
    '        If cboMesPedidos.Text = "" Or cboAnoPedidos.Text = "" Then Exit Sub\r\n'
    '        sSQL = "SELECT cliente.codigo, pedidos.cod_cliente, cliente.nome as var_Nome, pedidos.tipo_pagamento AS var_tipoPGTO, pedidos.cod_pedido AS var_codped, pedidos.data_compra as var_DTCompra, pedidos.total AS var_total, (CASE WHEN NotaFiscal.cod_pedido = pedidos.cod_pedido THEN \'SIM\' ELSE \'N\xc3O\' END) AS Status " & _\r\n'
    '               "FROM cliente INNER JOIN pedidos ON cliente.codigo = pedidos.cod_cliente LEFT JOIN NotaFiscal ON NotaFiscal.cod_pedido = pedidos.cod_pedido " & _\r\n'
    '               "WHERE (MONTH(pedidos.data_compra) = " & cboMesPedidos.ListIndex + 1 & ") AND (YEAR(pedidos.data_compra) = " & cboAnoPedidos.Text & ") " & _\r\n'
    '               "AND (TIPO_PEDIDO <> \'OR\xc7AMENTO\') ORDER BY pedidos.cod_pedido;"\r\n'
    '\r\n'
    '    Case "CLIENTE + DATAS"\r\n'
    '        If cboClientePedidos.Text = "" Then Exit Sub\r\n'
    '        If Not IsDate(cboMesPedidos.Text) Or Not IsDate(cboAnoPedidos.Text) Then\r\n'
    '            MsgBox "Informe datas v\xe1lidas nos campos Inicial e Final.", vbInformation, "Online Commerce"\r\n'
    '            Exit Sub\r\n'
    '        End If\r\n'
    '        sSQL = "SELECT cliente.codigo, pedidos.cod_cliente, cliente.nome as var_Nome, pedidos.tipo_pagamento AS var_tipoPGTO, pedidos.cod_pedido AS var_codped, pedidos.data_compra as var_DTCompra, pedidos.total AS var_total, (CASE WHEN NotaFiscal.cod_pedido = pedidos.cod_pedido THEN \'SIM\' ELSE \'N\xc3O\' END) AS Status " & _\r\n'
    '               "FROM cliente INNER JOIN pedidos ON cliente.codigo = pedidos.cod_cliente LEFT JOIN NotaFiscal ON NotaFiscal.cod_pedido = pedidos.cod_pedido " & _\r\n'
    '               "WHERE cliente.codigo = " & Val(cboClientePedidos.Text) & " " & _\r\n'
    '               "AND (pedidos.data_compra >= CONVERT(DATETIME,\'" & Format(CDate(cboMesPedidos.Text), ocDATA) & "\',103)) " & _\r\n'
    '               "AND (pedidos.data_compra <= CONVERT(DATETIME,\'" & Format(CDate(cboAnoPedidos.Text), ocDATA) & "\',103)) " & _\r\n'
    '               "AND (TIPO_PEDIDO <> \'OR\xc7AMENTO\') ORDER BY pedidos.cod_pedido;"\r\n'
    '\r\n'
    '    Case "CLIENTE + MENSAL"\r\n'
    '        If cboClientePedidos.Text = "" Or cboMesPedidos.Text = "" Or cboAnoPedidos.Text = "" Then Exit Sub\r\n'
    '        sSQL = "SELECT cliente.codigo, pedidos.cod_cliente, cliente.nome as var_Nome, pedidos.tipo_pagamento AS var_tipoPGTO, pedidos.cod_pedido AS var_codped, pedidos.data_compra as var_DTCompra, pedidos.total AS var_total, (CASE WHEN NotaFiscal.cod_pedido = pedidos.cod_pedido THEN \'SIM\' ELSE \'N\xc3O\' END) AS Status " & _\r\n'
    '               "FROM cliente INNER JOIN pedidos ON cliente.codigo = pedidos.cod_cliente LEFT JOIN NotaFiscal ON NotaFiscal.cod_pedido = pedidos.cod_pedido " & _\r\n'
    '               "WHERE cliente.codigo = " & Val(cboClientePedidos.Text) & " " & _\r\n'
    '               "AND (MONTH(pedidos.data_compra) = " & cboMesPedidos.ListIndex + 1 & ") AND (YEAR(pedidos.data_compra) = " & cboAnoPedidos.Text & ") " & _\r\n'
    '               "AND (TIPO_PEDIDO <> \'OR\xc7AMENTO\') ORDER BY pedidos.cod_pedido;"\r\n'
    '\r\n'
    '    Case Else\r\n'
    '        sSQL = "SELECT cliente.codigo, pedidos.cod_cliente, cliente.nome as var_Nome, pedidos.tipo_pagamento AS var_tipoPGTO, pedidos.cod_pedido AS var_codped, pedidos.data_compra as var_DTCompra, pedidos.total AS var_total, (CASE WHEN NotaFiscal.cod_pedido = pedidos.cod_pedido THEN \'SIM\' ELSE \'N\xc3O\' END) AS Status " & _\r\n'
    '               "FROM cliente INNER JOIN pedidos ON cliente.codigo = pedidos.cod_cliente LEFT JOIN NotaFiscal ON NotaFiscal.cod_pedido = pedidos.cod_pedido WHERE pedidos.cod_pedido = \'0\';"\r\n'
    '\r\n'
    'End Select'
)

c1 = text.count(old1)
c2 = text.count(old2)
c3 = text.count(old3)
print(f'Patch1:{c1}  Patch2:{c2}  Patch3:{c3}')

if c1 == 1 and c2 == 1 and c3 == 1:
    text = text.replace(old1, new1)
    text = text.replace(old2, new2)
    text = text.replace(old3, new3)
    out = text.encode('windows-1252')
    out = out.replace(b'\r\n', b'\n').replace(b'\r', b'\n').replace(b'\n', b'\r\n')
    open(r'C:\Projeto\OnlineCommerce\Forms\NFe_Completa.frm', 'wb').write(out)
    print('OK - 3 patches aplicados')
else:
    print('ERRO - verificar contagens')
