path = r'C:\Projeto\OnlineCommerce\Forms\Produtos_Estoque_Simples.frm'
with open(path, 'rb') as f:
    data = f.read()
content = data.decode('windows-1252')

errors = []

def sub(label, old, new, c, replace_all=False):
    n = c.count(old)
    if replace_all:
        if n == 0:
            errors.append(f'{label}: count=0')
            return c
        print(f'{label} OK ({n}x)')
        return c.replace(old, new)
    if n != 1:
        errors.append(f'{label}: count={n}')
        return c
    print(f'{label} OK')
    return c.replace(old, new, 1)

# ── 1a: ColWidth(0) = 300 em Formatar_Grid_Fiscal ────────────────────────────
content = sub('ColWidth0 Fiscal=300',
    '      .Cols = 15\r\n'
    '      .rows = 2\r\n'
    '      \r\n'
    '      .ColWidth(0) = 0\r\n',

    '      .Cols = 15\r\n'
    '      .rows = 2\r\n'
    '      \r\n'
    '      .ColWidth(0) = 300\r\n',
    content)

# ── 1b: ColWidth(0) = 300 em Formatar_Grid ───────────────────────────────────
content = sub('ColWidth0 Grid=300',
    '      .Cols = 12\r\n'
    '      .rows = 2\r\n'
    '      \r\n'
    '      .ColWidth(0) = 0\r\n',

    '      .Cols = 12\r\n'
    '      .rows = 2\r\n'
    '      \r\n'
    '      .ColWidth(0) = 300\r\n',
    content)

# ── 2a: Inicializar col 0 (checkboxes) apos Formatar_Grid_Fiscal ─────────────
content = sub('col0 init Fiscal',
    '      picAguarde.Visible = False\r\n'
    '   End With\r\n'
    '\'Else\r\n'
    '\'End If\r\n'
    'End Sub\r\n'
    'Private Sub Formatar_Grid(',

    '      picAguarde.Visible = False\r\n'
    '   End With\r\n'
    '   Dim lChk As Long\r\n'
    '   For lChk = 1 To Grid.rows - 1\r\n'
    '      Grid.Row = lChk: Grid.Col = 0\r\n'
    '      Set Grid.CellPicture = imgDesmarcada.Picture\r\n'
    '      Grid.CellPictureAlignment = 4\r\n'
    '   Next lChk\r\n'
    '   ImgMarcadaTODAS.Visible = False\r\n'
    '   lblMarcarTodas.Caption = "Marcar todos"\r\n'
    '   AvaliarFrmEdicao\r\n'
    '\'Else\r\n'
    '\'End If\r\n'
    'End Sub\r\n'
    'Private Sub Formatar_Grid(',
    content)

# ── 2b: Inicializar col 0 (checkboxes) apos Formatar_Grid ────────────────────
content = sub('col0 init Grid',
    '      picAguarde.Visible = False\r\n'
    '   End With\r\n'
    '\'Else\r\n'
    '\'End If\r\n'
    'End Sub\r\n'
    '\r\n'
    'Public Function SomaGrid(',

    '      picAguarde.Visible = False\r\n'
    '   End With\r\n'
    '   Dim lChk As Long\r\n'
    '   For lChk = 1 To Grid.rows - 1\r\n'
    '      Grid.Row = lChk: Grid.Col = 0\r\n'
    '      Set Grid.CellPicture = imgDesmarcada.Picture\r\n'
    '      Grid.CellPictureAlignment = 4\r\n'
    '   Next lChk\r\n'
    '   ImgMarcadaTODAS.Visible = False\r\n'
    '   lblMarcarTodas.Caption = "Marcar todos"\r\n'
    '   AvaliarFrmEdicao\r\n'
    '\'Else\r\n'
    '\'End If\r\n'
    'End Sub\r\n'
    '\r\n'
    'Public Function SomaGrid(',
    content)

# ── 3: Grid_Click — adicionar Case 0 (toggle checkbox por linha) ──────────────
content = sub('Grid_Click Case 0',
    'If iCol < 3 Or iCol > ColLimite Then Exit Sub\r\n'
    '\r\n'
    'Select Case iCol',

    'If iCol = 0 Then\r\n'
    '   If iRow < 1 Then Exit Sub\r\n'
    '   If Grid.TextMatrix(iRow, 0) = "1" Then\r\n'
    '      Grid.TextMatrix(iRow, 0) = ""\r\n'
    '      Grid.Row = iRow: Grid.Col = 0\r\n'
    '      Set Grid.CellPicture = imgDesmarcada.Picture\r\n'
    '      Grid.CellPictureAlignment = 4\r\n'
    '   Else\r\n'
    '      Grid.TextMatrix(iRow, 0) = "1"\r\n'
    '      Grid.Row = iRow: Grid.Col = 0\r\n'
    '      Set Grid.CellPicture = ImgMarcada.Picture\r\n'
    '      Grid.CellPictureAlignment = 4\r\n'
    '   End If\r\n'
    '   AvaliarFrmEdicao\r\n'
    '   Exit Sub\r\n'
    'End If\r\n'
    'If iCol < 3 Or iCol > ColLimite Then Exit Sub\r\n'
    '\r\n'
    'Select Case iCol',
    content)

# ── 4: cmdLocalizar_Click — chamar AvaliarFrmEdicao ao final ─────────────────
content = sub('cmdLocalizar AvaliarFrmEdicao',
    'If optCodBarra.Value = True Then txtCodBarra_GotFocus\r\n'
    'If optNCM.Value = True Then txtCodBarra_GotFocus\r\n'
    'End Sub',

    'If optCodBarra.Value = True Then txtCodBarra_GotFocus\r\n'
    'If optNCM.Value = True Then txtCodBarra_GotFocus\r\n'
    'AvaliarFrmEdicao\r\n'
    'End Sub',
    content)

# ── 5: Inserir todos os novos subs antes de Form_Unload ──────────────────────
novos_subs = (
    'Private Sub optEICMS_Click()\r\n'
    '   lblEdicaoColetiva.Caption = "ICMS CST"\r\n'
    '   txtEdicaoColetiva.Visible = True\r\n'
    '   cmdEdicaoColetiva.Visible = True\r\n'
    '   cmdAtualizar.Visible = False\r\n'
    '   lblEdicaoColetiva.Visible = True\r\n'
    '   cboEdicaoColetiva.Visible = False\r\n'
    'End Sub\r\n'
    '\r\n'
    'Private Sub optENCM_Click()\r\n'
    '   lblEdicaoColetiva.Caption = "NCM"\r\n'
    '   txtEdicaoColetiva.Visible = True\r\n'
    '   cmdEdicaoColetiva.Visible = True\r\n'
    '   cmdAtualizar.Visible = False\r\n'
    '   lblEdicaoColetiva.Visible = True\r\n'
    '   cboEdicaoColetiva.Visible = False\r\n'
    'End Sub\r\n'
    '\r\n'
    'Private Sub optECFOP_Click()\r\n'
    '   lblEdicaoColetiva.Caption = "CFOP"\r\n'
    '   txtEdicaoColetiva.Visible = True\r\n'
    '   cmdEdicaoColetiva.Visible = True\r\n'
    '   cmdAtualizar.Visible = False\r\n'
    '   lblEdicaoColetiva.Visible = True\r\n'
    '   cboEdicaoColetiva.Visible = False\r\n'
    'End Sub\r\n'
    '\r\n'
    'Private Sub optECategoria_Click()\r\n'
    'Dim rE As ADODB.Recordset\r\n'
    '   lblEdicaoColetiva.Caption = "Categoria"\r\n'
    '   txtEdicaoColetiva.Visible = False\r\n'
    '   cboEdicaoColetiva.Clear\r\n'
    '   Set rE = dbData.OpenRecordset("SELECT DISTINCT Categoria FROM Categorias WHERE Tipo_Empresa = " & tipoEmpresa & " ORDER BY Categoria;")\r\n'
    '   Do While Not rE.EOF: cboEdicaoColetiva.AddItem ValidateNull(rE("Categoria")): rE.MoveNext: Loop\r\n'
    '   rE.Close: Set rE = Nothing\r\n'
    '   cboEdicaoColetiva.Visible = True\r\n'
    '   cmdEdicaoColetiva.Visible = True\r\n'
    '   cmdAtualizar.Visible = False\r\n'
    '   lblEdicaoColetiva.Visible = True\r\n'
    'End Sub\r\n'
    '\r\n'
    'Private Sub optETags_Click()\r\n'
    'Dim rE As ADODB.Recordset\r\n'
    '   lblEdicaoColetiva.Caption = "Tags"\r\n'
    '   txtEdicaoColetiva.Visible = False\r\n'
    '   cboEdicaoColetiva.Clear\r\n'
    '   Set rE = dbData.OpenRecordset("SELECT ct.Tags FROM Categorias_Tags ct INNER JOIN Categorias c ON ct.ID_Categoria = c.ID_Categoria WHERE c.Tipo_Empresa = " & tipoEmpresa & " ORDER BY c.Categoria, ct.Tags;")\r\n'
    '   Do While Not rE.EOF: cboEdicaoColetiva.AddItem ValidateNull(rE("Tags")): rE.MoveNext: Loop\r\n'
    '   rE.Close: Set rE = Nothing\r\n'
    '   cboEdicaoColetiva.Visible = True\r\n'
    '   cmdEdicaoColetiva.Visible = True\r\n'
    '   cmdAtualizar.Visible = False\r\n'
    '   lblEdicaoColetiva.Visible = True\r\n'
    'End Sub\r\n'
    '\r\n'
    'Private Sub cmdEdicaoColetiva_Click()\r\n'
    'Dim i As Integer\r\n'
    'Dim sVal As String\r\n'
    'Dim iColE As Integer\r\n'
    'Dim sSet As String\r\n'
    '\r\n'
    'If txtEdicaoColetiva.Visible Then\r\n'
    '   sVal = txtEdicaoColetiva.Text\r\n'
    'Else\r\n'
    '   sVal = cboEdicaoColetiva.Text\r\n'
    'End If\r\n'
    'If optETags.Value Or optECategoria.Value Then sVal = UCase(sVal)\r\n'
    '\r\n'
    'If optEICMS.Value Then\r\n'
    '   iColE = -1: sSet = "ICMSCST = \'" & sVal & "\'"\r\n'
    'ElseIf optENCM.Value Then\r\n'
    '   iColE = -1: sSet = "NCM = \'" & sVal & "\'"\r\n'
    'ElseIf optECFOP.Value Then\r\n'
    '   iColE = -1: sSet = "CFOP = " & sVal\r\n'
    'ElseIf optECategoria.Value Then\r\n'
    '   iColE = 7: sSet = "categoria = \'" & sVal & "\'"\r\n'
    'ElseIf optETags.Value Then\r\n'
    '   iColE = 8: sSet = "TAGS = \'" & sVal & "\'"\r\n'
    'Else\r\n'
    '   Exit Sub\r\n'
    'End If\r\n'
    '\r\n'
    'If Len(Trim(sSet)) = 0 Then Exit Sub\r\n'
    '\r\n'
    'Dim iExact As Integer\r\n'
    'iExact = 0\r\n'
    'If optENCM.Value Then iExact = 8\r\n'
    'If optECFOP.Value Then iExact = 4\r\n'
    'If optEICMS.Value Then iExact = 3\r\n'
    'If iExact > 0 Then\r\n'
    '   Dim k As Integer\r\n'
    '   Dim bNumOk As Boolean\r\n'
    '   bNumOk = (Len(sVal) = iExact)\r\n'
    '   If bNumOk Then\r\n'
    '      For k = 1 To Len(sVal)\r\n'
    '         If Mid(sVal, k, 1) < "0" Or Mid(sVal, k, 1) > "9" Then bNumOk = False: Exit For\r\n'
    '      Next k\r\n'
    '   End If\r\n'
    '   If Not bNumOk Then\r\n'
    '      MsgBox "Digite exatamente " & iExact & " d\xedgitos num\xe9ricos.", vbExclamation, "Edi\xe7\xe3o Coletiva"\r\n'
    '      txtEdicaoColetiva.SetFocus\r\n'
    '      Exit Sub\r\n'
    '   End If\r\n'
    'End If\r\n'
    '\r\n'
    'Dim bTemMarcadas As Boolean\r\n'
    'For i = 1 To Grid.rows - 1\r\n'
    '   If Grid.TextMatrix(i, 0) = "1" Then bTemMarcadas = True: Exit For\r\n'
    'Next i\r\n'
    '\r\n'
    'If optETags.Value Then\r\n'
    '   Dim iLinSemCat As Integer\r\n'
    '   For i = 1 To Grid.rows - 1\r\n'
    '      If bTemMarcadas And Grid.TextMatrix(i, 0) <> "1" Then GoTo ProxValCat\r\n'
    '      If Len(Trim(Grid.TextMatrix(i, 7))) = 0 Then iLinSemCat = iLinSemCat + 1\r\n'
    'ProxValCat:\r\n'
    '   Next i\r\n'
    '   If iLinSemCat > 0 Then\r\n'
    '      MsgBox iLinSemCat & " produto(s) sem categoria. Defina a categoria antes de aplicar a tag.", vbExclamation, "Tag sem categoria"\r\n'
    '      Exit Sub\r\n'
    '   End If\r\n'
    'End If\r\n'
    '\r\n'
    'picAguarde.Visible = True\r\n'
    'DoEvents\r\n'
    '\r\n'
    'For i = 1 To Grid.rows - 1\r\n'
    '   If bTemMarcadas And Grid.TextMatrix(i, 0) <> "1" Then GoTo ProximaLinha\r\n'
    '   If iColE >= 0 Then Grid.TextMatrix(i, iColE) = sVal\r\n'
    '   dbData.Execute "UPDATE produtos SET " & sSet & " WHERE codigo = " & Grid.TextMatrix(i, 2) & ";"\r\n'
    'ProximaLinha:\r\n'
    'Next i\r\n'
    '\r\n'
    'txtEdicaoColetiva.Text = ""\r\n'
    'cboEdicaoColetiva.Text = ""\r\n'
    'picAguarde.Visible = False\r\n'
    'ResetarMarcas\r\n'
    'optENCM.Value = False\r\n'
    'optECFOP.Value = False\r\n'
    'optEICMS.Value = False\r\n'
    'optECategoria.Value = False\r\n'
    'optETags.Value = False\r\n'
    'txtEdicaoColetiva.Visible = False\r\n'
    'cboEdicaoColetiva.Visible = False\r\n'
    'cmdEdicaoColetiva.Visible = False\r\n'
    'lblEdicaoColetiva.Visible = False\r\n'
    'cmdAtualizar.Visible = True\r\n'
    'End Sub\r\n'
    '\r\n'
    'Private Sub txtEdicaoColetiva_LostFocus()\r\n'
    'Dim s As String\r\n'
    's = Trim(txtEdicaoColetiva.Text)\r\n'
    'If optENCM.Value Then\r\n'
    '   s = Replace(s, ".", "")\r\n'
    '   s = Replace(s, " ", "")\r\n'
    'End If\r\n'
    'txtEdicaoColetiva.Text = s\r\n'
    'End Sub\r\n'
    '\r\n'
    'Private Sub cboEdicaoColetiva_KeyPress(KeyAscii As Integer)\r\n'
    '   If Not (optETags.Value Or optECategoria.Value) Then Exit Sub\r\n'
    '   If KeyAscii >= 97 And KeyAscii <= 122 Then\r\n'
    '      KeyAscii = KeyAscii - 32\r\n'
    '   ElseIf optETags.Value Then\r\n'
    '      If Not ((KeyAscii >= 65 And KeyAscii <= 90) Or KeyAscii = 8 Or KeyAscii = 32) Then\r\n'
    '         KeyAscii = 0\r\n'
    '      End If\r\n'
    '   End If\r\n'
    'End Sub\r\n'
    '\r\n'
    'Private Sub cboEdicaoColetiva_Change()\r\n'
    '   If Not (optETags.Value Or optECategoria.Value) Then Exit Sub\r\n'
    '   Dim pos As Integer\r\n'
    '   pos = cboEdicaoColetiva.SelStart\r\n'
    '   cboEdicaoColetiva.Text = UCase(cboEdicaoColetiva.Text)\r\n'
    '   cboEdicaoColetiva.SelStart = pos\r\n'
    'End Sub\r\n'
    '\r\n'
    'Private Sub cboEdicaoColetiva_LostFocus()\r\n'
    '   cboEdicaoColetiva.Text = Trim(cboEdicaoColetiva.Text)\r\n'
    'End Sub\r\n'
    '\r\n'
    'Private Sub ResetarMarcas()\r\n'
    'Dim i As Integer\r\n'
    'For i = 1 To Grid.rows - 1\r\n'
    '   Grid.TextMatrix(i, 0) = ""\r\n'
    '   Grid.Row = i: Grid.Col = 0\r\n'
    '   Set Grid.CellPicture = imgDesmarcada.Picture\r\n'
    '   Grid.CellPictureAlignment = 4\r\n'
    'Next i\r\n'
    'ImgMarcadaTODAS.Visible = False\r\n'
    'lblMarcarTodas.Caption = "Marcar todos"\r\n'
    'AvaliarFrmEdicao\r\n'
    'End Sub\r\n'
    '\r\n'
    'Private Sub AvaliarFrmEdicao()\r\n'
    'Dim j As Integer\r\n'
    'Dim bEnabled As Boolean\r\n'
    'For j = 1 To Grid.rows - 1\r\n'
    '   If Grid.TextMatrix(j, 0) = "1" Then bEnabled = True: Exit For\r\n'
    'Next j\r\n'
    'If Not bEnabled Then\r\n'
    '   If Not (optTodos.Value Or optCodBarra.Value Or optDesc.Value) Then\r\n'
    '      If Grid.rows > 1 Then bEnabled = True\r\n'
    '   End If\r\n'
    'End If\r\n'
    'frmAlterarGrupos.Enabled = bEnabled\r\n'
    'frmEdicao.Enabled = bEnabled\r\n'
    'frmEdicaoFiltros.Enabled = bEnabled\r\n'
    'End Sub\r\n'
    '\r\n'
    'Private Sub ImgMarcadaTODAS_Click()\r\n'
    'Dim i As Integer\r\n'
    'ImgMarcadaTODAS.Visible = False\r\n'
    'lblMarcarTodas.Caption = "Marcar todos"\r\n'
    'For i = 1 To Grid.rows - 1\r\n'
    '   Grid.TextMatrix(i, 0) = ""\r\n'
    '   Grid.Row = i: Grid.Col = 0\r\n'
    '   Set Grid.CellPicture = imgDesmarcada.Picture\r\n'
    '   Grid.CellPictureAlignment = 4\r\n'
    'Next i\r\n'
    'AvaliarFrmEdicao\r\n'
    'End Sub\r\n'
    '\r\n'
    'Private Sub lblMarcarTodas_Click()\r\n'
    'Dim i As Integer\r\n'
    'If ImgMarcadaTODAS.Visible Then\r\n'
    '   ImgMarcadaTODAS.Visible = False\r\n'
    '   lblMarcarTodas.Caption = "Marcar todos"\r\n'
    '   For i = 1 To Grid.rows - 1\r\n'
    '      Grid.TextMatrix(i, 0) = ""\r\n'
    '      Grid.Row = i: Grid.Col = 0\r\n'
    '      Set Grid.CellPicture = imgDesmarcada.Picture\r\n'
    '      Grid.CellPictureAlignment = 4\r\n'
    '   Next i\r\n'
    'Else\r\n'
    '   ImgMarcadaTODAS.Visible = True\r\n'
    '   lblMarcarTodas.Caption = "Desmarcar todos"\r\n'
    '   For i = 1 To Grid.rows - 1\r\n'
    '      Grid.TextMatrix(i, 0) = "1"\r\n'
    '      Grid.Row = i: Grid.Col = 0\r\n'
    '      Set Grid.CellPicture = ImgMarcada.Picture\r\n'
    '      Grid.CellPictureAlignment = 4\r\n'
    '   Next i\r\n'
    'End If\r\n'
    'AvaliarFrmEdicao\r\n'
    'End Sub\r\n'
    '\r\n'
)

content = sub('inserir novos subs',
    'Private Sub Form_Unload(Cancel As Integer)',
    novos_subs + 'Private Sub Form_Unload(Cancel As Integer)',
    content)

if errors:
    print('ERRORS:', errors)
else:
    content = content.replace('\r\n', '\n').replace('\r', '\n').replace('\n', '\r\n')
    with open(path, 'wb') as f:
        f.write(content.encode('windows-1252'))
    print('OK \x96 arquivo gravado.')
